### ISSUE TITLE
DistributionNotFound Python Traceback on stream open

### ISSUE THREAD

**Issue by andrewzwicky** [streamlink/streamlink#1056]
### Checklist

- [X] This is a bug report.
- [X] I have read the contribution guidelines.

### Description

When I attempt to open any stream, I receive the following traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 969, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 860, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (streamlink 0.7.0 (/home/andrew/.local/lib/python3.6/site-packages), Requirement.parse('streamlink==0.1.0'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/streamlink", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3037, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3021, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3050, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 855, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'streamlink==0.1.0' distribution was not found and is required by the application

```
### Expected / Actual behavior

stream starts

### Reproduction steps / Explicit stream URLs to test

1. install via pip in python 3.6
2. ```streamlink --version```

### Environment details

Operating system and version: **Fedora 26**
Streamlink and Python version: **Python 3.6.1**

installed packages:
```
bleach (2.0.0)
certifi (2017.4.17)
chardet (3.0.4)
cycler (0.10.0)
entrypoints (0.2.3)
html5lib (0.999999999)
ipykernel (4.6.1)
ipython (6.1.0)
ipython-genutils (0.2.0)
ipywidgets (6.0.0)
iso-639 (0.4.5)
iso3166 (0.8)
jedi (0.10.2)
Jinja2 (2.9.6)
jsonschema (2.6.0)
jupyter (1.0.0)
jupyter-client (5.1.0)
jupyter-console (5.1.0)
jupyter-core (4.3.0)
MarkupSafe (1.0)
matplotlib (2.0.2)
mistune (0.7.4)
nbconvert (5.2.1)
nbformat (4.3.0)
notebook (5.0.0)
numpy (1.13.0)
pandocfilters (1.4.1)
pexpect (4.2.1)
pickleshare (0.7.4)
prompt-toolkit (1.0.14)
ptyprocess (0.5.2)
pycryptodome (3.4.6)
Pygments (2.2.0)
pyparsing (2.2.0)
python-dateutil (2.6.0)
pyzmq (16.0.2)
qtconsole (4.3.0)
requests (2.18.1)
scipy (0.19.1)
simplegeneric (0.8.1)
streamlink (0.7.0)
terminado (0.6)
testpath (0.3.1)
tornado (4.5.1)
traitlets (4.3.2)
urllib3 (1.21.1)
virtualenv (15.1.0)
wcwidth (0.1.7)
webencodings (0.5.1)
widgetsnbextension (2.0.0)
```
Looks like this is the script that is created @ ```usr/bin/streamlink```:
```
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'streamlink==0.1.0','console_scripts','streamlink'
__requires__ = 'streamlink==0.1.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('streamlink==0.1.0', 'console_scripts', 'streamlink')()
    )
```

modifying the script to:
```
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'streamlink==0.7.0','console_scripts','streamlink'
__requires__ = 'streamlink==0.7.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('streamlink==0.7.0', 'console_scripts', 'streamlink')()
    )
```
resolves the problem, not sure about a long term solution.

**Comment by beardypig** [comment]
Looks like you installed 0.1.0 globally and then 0.7.0 locally (per user) and they are conflicting. You might be able to do `sudo pip uninstall streamlink` to resolve it. You might need to update `pip` first `sudo pip install -U pip`.

**Comment by mmetak** [comment]
> resolves the problem, not sure about a long term solution.

[Install the official package from fedora repos?](https://apps.fedoraproject.org/packages/python-streamlink)

The latest 0.7.0 version is already in testing for fc26 and should move to stable soon?

**Comment by gravyboat** [comment]
No discussion in a while and some options were provided, closing.
