### ISSUE TITLE
Unable to open Smashcast streams

### ISSUE THREAD

**Issue by Bazkip** [streamlink/streamlink#1078]
I get the following error whenever I try to open a Smashcast stream 

```
streamlink smashcast.tv/greatvaluesmash best
[cli][info] Found matching plugin hitbox for URL smashcast.tv/greatvaluesmash
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 15, in
 <module>
    main()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 103
8, in main
    handle_url()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 482
, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 394
, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", lin
e 345, in get_streams
    return self.streams(*args, **kwargs)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", lin
e 248, in streams
    ostreams = self._get_streams()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\hitbox.py", li
ne 181, in _get_streams
    if livestream["media_hosted_media"]:
KeyError: 'media_hosted_media'
```

Tried with multiple different streams and using a hitbox url instead of smashcast and it still occurs. It still works perfectly fine on Livestreamer, so I'm not really sure what's up. Asked a friend to test it out to see if it's not just me and he had the same error. 

Using the latest version (0.7.0) on Windows 7, and my friend was using Windows 8.1.

**Comment by gravyboat** [comment]
@Bazkip Thanks for the report, #1082 has been merged which should resolve this if you want to give the nightly build a shot.
