### ISSUE TITLE
[usrtream] streamlink crash on loading nasatv on ustream

### ISSUE THREAD

**Issue by www2000** [streamlink/streamlink#110]
The nasatv stream on ustream wond loading.
Crash log:
`$ streamlink http://www.ustream.tv/nasahdtv best
[cli][info] Found matching plugin ustreamtv for URL http://www.ustream.tv/nasahdtv
Traceback (most recent call last):
  File "/usr/bin/streamlink", line 9, in <module>
    load_entry_point('streamlink==0.0.2', 'console_scripts', 'streamlink')()
  File "/usr/share/streamlink/streamlink_cli/main.py", line 902, in main
    handle_url()
  File "/usr/share/streamlink/streamlink_cli/main.py", line 479, in handle_url
    streams = fetch_streams(plugin)
  File "/usr/share/streamlink/streamlink_cli/main.py", line 392, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/usr/lib/python2.7/dist-packages/streamlink/plugin/plugin.py", line 316, in get_streams
    return self.streams(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/streamlink/plugin/plugin.py", line 236, in streams
    ostreams = list(ostreams)
  File "/usr/lib/python2.7/dist-packages/streamlink/plugins/ustreamtv.py", line 550, in _get_live_streams
    streams = self._get_desktop_streams(channel_id)
  File "/usr/lib/python2.7/dist-packages/streamlink/plugins/ustreamtv.py", line 513, in _get_desktop_streams
    provider_url = provider["url"]
KeyError: 'url'
`

**Comment by stevek123** [comment]
See #58

**Comment by RosadinTV** [comment]
One alternative is limit result streams to mobile only (HLS), here the modified ustreamtv.py file:

[ustreamtv.txt](https://github.com/streamlink/streamlink/files/572846/ustreamtv.txt)

**Comment by stepshal** [comment]
@RosadinTV can you make a PR, so it can be marged?

**Comment by RosadinTV** [comment]
@stepshal Done

**Comment by gravyboat** [comment]
Closing this since #754 was merged.
