### ISSUE TITLE
Cant open a stream. Error Traceback

### ISSUE THREAD

**Issue by ChilliBoi** [streamlink/streamlink#1103]
----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

I try to run a stream, but it won't open and it gives me the following error lines.
Traceback (most recent call last):
File "C:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 15, in <module>
main()
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 1038, in main
handle_url()
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 502, in handle_url
handle_stream(plugin, streams, stream_name)
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 380, in handle_stream
return output_stream_http(plugin, streams)
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 138, in output_stream_http
quiet=not args.verbose_player)
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\output.py", line 91, in __init__
self.stdout = open(os.devnull, "w")
FileNotFoundError: [Errno 2] No such file or directory: 'nul'

### Reproduction steps / Explicit stream URLs to test

1. Open a stream

**Comment by beardypig** [comment]
Which version of Windows are you using? And which version streamlink?

**Comment by gravyboat** [comment]
What the command looks like would also be nice to see.

**Comment by gravyboat** [comment]
No response in months, closing.
