### ISSUE TITLE
Request for live.bilibili.com

### ISSUE THREAD

**Issue by caoli5288** [streamlink/streamlink#1162]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
https://live.bilibili.com/ still not supported
...

### Expected / Actual behavior
N/A

### Reproduction steps / Explicit stream URLs to test
N/A

### Environment details
N/A

### Comments, logs, screenshots, etc.
```
youtube-dl -v https://live.bilibili.com/404
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://live.bilibili.com/404']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.13
[debug] Python version 2.7.13 - MINGW64_NT-6.1-2.8.2-0.313-5-3-x86_64-64bit
[debug] exe versions: ffmpeg 3.2.2
[debug] Proxy map: {}
[generic] 404: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 404: Downloading webpage
[generic] 404: Extracting information
ERROR: Unsupported URL: https://live.bilibili.com/404
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 2103, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/lib/python2.7/site-packages/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/lib/python2.7/site-packages/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: mismatched tag: line 31, column 2
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 2976, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://live.bilibili.com/404
```

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by caoli5288** [comment]
ohhh sorry I open a issue wrong place
