### ISSUE TITLE
After the command is run, an error message appears

### ISSUE THREAD

**Issue by lki2019** [streamlink/streamlink#1184]
- [x] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

<pre><code>
streamlink --http-header "Referer=http://shida66.com/vide
o/detail_3118.html" --http-header "User-Agent=Mozilla/5.0 (iPad; CPU OS 8_1_3 li
ke Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B466 S
afari/600.1.4" "HLS://http://video.shida66.com/m3u8_sd/2017/08/23/D7730A33-4886-
ADD9-C379-CF080769B935.m3u8" best -o out.ts
[cli][info] Found matching plugin stream for URL HLS://http://video.shida66.com/
m3u8_sd/2017/08/23/D7730A33-4886-ADD9-C379-CF080769B935.m3u8
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "C:\Program Files\Streamlink\pkgs\streamlink\stream\segmented.py", line 1
60, in run
    self.write(segment, result)
  File "C:\Program Files\Streamlink\pkgs\streamlink\stream\hls.py", line 91, in
write
    sequence.num)
  File "C:\Program Files\Streamlink\pkgs\streamlink\stream\hls.py", line 52, in
create_decryptor
    return AES.new(self.key_data, AES.MODE_CBC, iv)
  File "C:\Program Files\Streamlink\pkgs\Crypto\Cipher\AES.py", line 260, in new

    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "C:\Program Files\Streamlink\pkgs\Crypto\Cipher\__init__.py", line 130, i
n _create_cipher
    return modes[mode](factory, **kwargs)
  File "C:\Program Files\Streamlink\pkgs\Crypto\Cipher\_mode_cbc.py", line 232,
in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "C:\Program Files\Streamlink\pkgs\Crypto\Cipher\AES.py", line 130, in _cr
eate_base_cipher
    raise ValueError("Incorrect AES key length (%d bytes)" % len(key))
ValueError: Incorrect AES key length (0 bytes)

[cli][error] Try 1/1: Could not open stream <HLSStream('http://video.shida66.com
/m3u8_sd/2017/08/23/D7730A33-4886-ADD9-C379-CF080769B935.m3u8')> (Failed to read
 data from stream: Read timeout)
error: Could not open stream <HLSStream('http://video.shida66.com/m3u8_sd/2017/0
8/23/D7730A33-4886-ADD9-C379-CF080769B935.m3u8')>, tried 1 times, exiting
[cli][info] Closing currently open stream...<pre><code>

what does it mean?

**Comment by lki2019** [comment]
The problem has been resolved,
