### ISSUE TITLE
Error while installing streamlink version 0.7.0

### ISSUE THREAD

**Issue by TheSneakySniper** [streamlink/streamlink#1191]
Everything worked fine installing up until this point:

Processing streamlink-0.7.0-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/streamlink-0.7.0-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/streamlink-0.7.0-py2.7.egg
Extracting streamlink-0.7.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
streamlink 0.7.0 is already the active version in easy-install.pth
Installing streamlink script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/streamlink-0.7.0-py2.7.egg
Processing dependencies for streamlink==0.7.0
Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    "Topic :: Utilities"])
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 414, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 644, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 695, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 740, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 837, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2497, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: requests 2.9.1 has no such extra feature 'socks'

(code tags are not working)
Does anyone know why this might be happening?

System Specs:
https://hastebin.com/ovopusolac.go

Running `streamlink` creates this error:
Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 837, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2497, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: requests 2.9.1 has no such extra feature 'socks'

**Comment by gravyboat** [comment]
I'm assuming since you closed this you fixed it?

**Comment by mrawji** [comment]
For anyone else stumbling across this, your 'requests' package is out of date:

```
$ sudo pip install -U requests
<snip>
      Successfully uninstalled requests-2.9.1
Successfully installed certifi-2017.7.27.1 chardet-3.0.4 idna-2.6 requests-2.18.4
```
This caused the following error (for me)
```
pkg_resources.DistributionNotFound: The 'PySocks!=1.5.7,>=1.5.6; extra == "socks"' distribution was not found and is required by requests
```
Simple fix:
```
$ sudo pip install -U PySocks
<snip>
  Running setup.py install for PySocks ... done
Successfully installed PySocks-1.6.7
```
