### ISSUE TITLE
Error when update to new 0.8.1

### ISSUE THREAD

**Issue by kesdoputr** [streamlink/streamlink#1219]
### Checklist

- [x] This is a bug report.

### Description
Hello everyone,i'm using win7SP1 64bit and i just update to 0.8.1,
but i found that i can't use streamlink to play stream(have tried twitch and douyu),
i get these message below:

Z:\>streamlink https://www.twitch.tv/wayne379
Traceback (most recent call last):
  File "C:\Python\Scripts\streamlink-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "c:\python\lib\site-packages\pkg_resources\__init__.py", line 3084, in <m
odule>
    @_call_aside
  File "c:\python\lib\site-packages\pkg_resources\__init__.py", line 3070, in _c
all_aside
    f(*args, **kwargs)
  File "c:\python\lib\site-packages\pkg_resources\__init__.py", line 3097, in _i
nitialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\python\lib\site-packages\pkg_resources\__init__.py", line 651, in _bu
ild_master
    ws.require(__requires__)
  File "c:\python\lib\site-packages\pkg_resources\__init__.py", line 952, in req
uire
    needed = self.resolve(parse_requirements(requirements))
  File "c:\python\lib\site-packages\pkg_resources\__init__.py", line 839, in res
olve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PySocks!=1.5.7,>=1.5.6' distribution wa
s not found and is required by requests

I use pip isnstall --upgrade streamlink to upgrade,is there a fix for new version?
Now i back to old 0.7.0 and it's work.

**Comment by skulblakka** [comment]
This is an issue with PIP and is being discussed over here #1195

**Comment by beardypig** [comment]
Maybe we should just circumvent the pip issue and add PySocks and a dependency directly..

**Comment by gravyboat** [comment]
Yeah I'm wondering the same @beardypig, who knows when they will actually fix it and if people will have updated pip.
