### ISSUE TITLE
TVPlayer plugin arguments bug

### ISSUE THREAD

**Issue by mtsmtsmts** [streamlink/streamlink#1227]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

TVPlayer doesn't work due to arguments problem

### Reproduction steps / Explicit stream URLs to test

Example command to check:  "streamlink https://tvplayer.com/watch/bbctwo best"

### Environment details

Operating system and version: Linux raspberrypi 4.9.35
Streamlink and Python version: Streamlink 0.8.1 Python 2.7

### Comments, logs, screenshots, etc.
```
streamlink https://tvplayer.com/watch/bbctwo best
[cli][info] Found matching plugin tvplayer for URL https://tvplayer.com/watch/bbctwo
Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 9, in <module>
    load_entry_point('streamlink==0.8.1', 'console_scripts', 'streamlink')()
  File "/usr/local/lib/python2.7/dist-packages/streamlink-0.8.1-py2.7.egg/streamlink_cli/main.py", line 1045, in main
    handle_url()
  File "/usr/local/lib/python2.7/dist-packages/streamlink-0.8.1-py2.7.egg/streamlink_cli/main.py", line 482, in handle_url
    streams = fetch_streams(plugin)
  File "/usr/local/lib/python2.7/dist-packages/streamlink-0.8.1-py2.7.egg/streamlink_cli/main.py", line 394, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/usr/local/lib/python2.7/dist-packages/streamlink-0.8.1-py2.7.egg/streamlink/plugin/plugin.py", line 385, in get_streams
    return self.streams(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/streamlink-0.8.1-py2.7.egg/streamlink/plugin/plugin.py", line 288, in streams
    ostreams = self._get_streams()
  File "/usr/local/lib/python2.7/dist-packages/streamlink-0.8.1-py2.7.egg/streamlink/plugins/tvplayer.py", line 100, in _get_streams
    stream_data = self._get_stream_data(**stream_attrs)
TypeError: _get_stream_data() takes at least 4 arguments (3 given)
```

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
Are you logged in? There is a slightly different page layout when logged in, I have a PR pending to fix it #1154.

**Comment by mtsmtsmts** [comment]
Hi! It looks like it has nothing to do with being logged in. I tried both with and without logging parameters.

**Comment by beardypig** [comment]
Alrighty maybe they have changed the site layout, I'll take a look at as soon as possible. Do any other channels work? Or do all of them give the same error?

**Comment by mtsmtsmts** [comment]
None of the TVPlayer's channels work and all of them give the same error. It seems that the plugin is broken now. I have no issues with other plugins. 
Thanks

**Comment by mtsmtsmts** [comment]
That's right! The issue #1228 has also solved my problem by using:
> pip install -U git+https://github.com/streamlink/streamlink.git

Thank you guys!

**Comment by gravyboat** [comment]
Good stuff, going to close this out then.
