### ISSUE TITLE
Does not work on OSX 10.12.6 (16G29)

### ISSUE THREAD

**Issue by SnowySailor** [streamlink/streamlink#1296]
When running any command with streamlink, I get this trace:

Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.macosx-10.10-intel/egg/pkg_resources/__init__.py", line 3095, in <module>
  File "build/bdist.macosx-10.10-intel/egg/pkg_resources/__init__.py", line 3081, in _call_aside
  File "build/bdist.macosx-10.10-intel/egg/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
  File "build/bdist.macosx-10.10-intel/egg/pkg_resources/__init__.py", line 658, in _build_master
  File "build/bdist.macosx-10.10-intel/egg/pkg_resources/__init__.py", line 959, in require
  File "build/bdist.macosx-10.10-intel/egg/pkg_resources/__init__.py", line 854, in resolve
  File "build/bdist.macosx-10.10-intel/egg/pkg_resources/__init__.py", line 2625, in requires
pkg_resources.UnknownExtra: requests 2.8.1 has no such extra feature 'socks'

I installed with `sudo pip install streamlink`
Same error with homebrew.

Solution:

- Cloned from source: http://docs.python-requests.org/en/master/user/install/#install
- `cd requests`
- `pip install .`
- rerun streamlink command and it works

**Comment by gravyboat** [comment]
Thanks for the report, this is actually an issue we are aware of with socks and how pip handles dependencies that we weren't expecting (https://github.com/streamlink/streamlink/issues/1195#issuecomment-327237963), typically only Windows users have reported this so I'll leave this open, we've discussed fixing this dependency issue here as well: https://github.com/streamlink/streamlink/issues/1217 @beardypig I just checked the pip issue where this is reported and there has been 0 movement on their side. I'm not 100% sure how we are going to fix up the setup.py to address this since the format of the deps append value here: https://github.com/streamlink/streamlink/blob/master/setup.py#L50 is correct.

**Comment by back-to** [comment]
This can be closed.
Fixed in https://github.com/streamlink/streamlink/pull/1317
