### ISSUE TITLE
Connectcast:  can't use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by stepshal** [streamlink/streamlink#151]
```
Traceback (most recent call last):
  File "/usr/bin/streamlink", line 11, in <module>
    load_entry_point('streamlink==0.0.2', 'console_scripts', 'streamlink')()
  File "/usr/lib/python3.4/site-packages/streamlink_cli/main.py", line 899, in m                                                                                                                ain
    handle_url()
  File "/usr/lib/python3.4/site-packages/streamlink_cli/main.py", line 479, in h                                                                                                                andle_url
    streams = fetch_streams(plugin)
  File "/usr/lib/python3.4/site-packages/streamlink_cli/main.py", line 392, in f                                                                                                                etch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/usr/lib/python3.4/site-packages/streamlink/plugin/plugin.py", line 316,                                                                                                                 in get_streams
    return self.streams(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/streamlink/plugin/plugin.py", line 230,                                                                                                                 in streams
    ostreams = self._get_streams()
  File "/usr/lib/python3.4/site-packages/streamlink/plugins/connectcast.py", lin                                                                                                                e 21, in _get_streams
    match = _stream_re.search(res.content)
TypeError: can't use a string pattern on a bytes-like object
```

**Comment by beardypig** [comment]
That's my bad...
