### ISSUE TITLE
Can not install streamlink pkg_resources.UnknownExtra: urllib3 1.7.1 has no such extra feature 'secure'

### ISSUE THREAD

**Issue by limiteddi** [streamlink/streamlink#1534]
Trying to run on Ubuntu 14.04

/usr/local/bin/streamlink
```
Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 633, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2299, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: urllib3 1.7.1 has no such extra feature 'secure'
```

pip install --upgrade streamlink

```
Requirement already up-to-date: streamlink in /usr/local/lib/python2.7/dist-packages/streamlink-0.10.0-py2.7.egg
Requirement already up-to-date: futures in /usr/local/lib/python2.7/dist-packages (from streamlink)
Downloading/unpacking urllib3[secure] from https://pypi.python.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl#md5=1c11e1c80371cc4e89911071010a98d1 (from streamlink)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB): 132kB downloaded
Requirement already up-to-date: singledispatch in /usr/local/lib/python2.7/dist-packages (from streamlink)
Downloading/unpacking requests!=2.12.0,!=2.12.1,!=2.16.0,!=2.16.1,!=2.16.2,!=2.16.3,!=2.16.4,!=2.16.5,!=2.17.1,<3.0,>=2.2 from https://pypi.python.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl#md5=eb9be71cc41fd73a51a7c9cd1adde5de (from streamlink)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB): 88kB downloaded
Requirement already up-to-date: pycryptodome<4,>=3.4.3 in /usr/local/lib/python2.7/dist-packages (from streamlink)
Requirement already up-to-date: backports.shutil_which in /usr/local/lib/python2.7/dist-packages (from streamlink)
Requirement already up-to-date: backports.shutil_get_terminal_size in /usr/local/lib/python2.7/dist-packages (from streamlink)
Requirement already up-to-date: iso-639 in /usr/local/lib/python2.7/dist-packages (from streamlink)
Requirement already up-to-date: iso3166 in /usr/local/lib/python2.7/dist-packages (from streamlink)
Requirement already up-to-date: websocket-client in /usr/local/lib/python2.7/dist-packages (from streamlink)
Requirement already up-to-date: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python2.7/dist-packages (from streamlink)
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1091, in prepare_files
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 811, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(self.req)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 564, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 436, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
IndexError: list index out of range

Storing debug log for failure in /root/.pip/pip.log
```

**Comment by gravyboat** [comment]
Try upgrading pip: `pip install --upgrade pip`, then run the Streamlink upgrade again.

**Comment by gravyboat** [comment]
@limiteddi Did that work?
