### ISSUE TITLE
vaughnlive plugin broken ? SOLVED

### ISSUE THREAD

**Issue by cirrusUK** [streamlink/streamlink#161]
streamlink http://vaughnlive.tv/crimecentral low  
[cli][info] Found matching plugin vaughnlive for URL http://vaughnlive.tv/crimecentral
Traceback (most recent call last):
  File "/usr/bin/streamlink", line 11, in <module>
    load_entry_point('streamlink==0.0.2', 'console_scripts', 'streamlink')()
  File "/usr/lib/python3.5/site-packages/streamlink_cli/main.py", line 902, in main
    handle_url()
  File "/usr/lib/python3.5/site-packages/streamlink_cli/main.py", line 479, in handle_url
    streams = fetch_streams(plugin)
  File "/usr/lib/python3.5/site-packages/streamlink_cli/main.py", line 392, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/usr/lib/python3.5/site-packages/streamlink/plugin/plugin.py", line 316, in get_streams
    return self.streams(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/streamlink/plugin/plugin.py", line 230, in streams
    ostreams = self._get_streams()
  File "/usr/lib/python3.5/site-packages/streamlink/plugins/vaughnlive.py", line 62, in _get_streams
    params["version"] = PLAYER_VERSION
NameError: name 'PLAYER_VERSION' is not defined
[1]    16561 exit 1     streamlink http://vaughnlive.tv/crimecentral low

**Comment by mmetak** [comment]
You're using the latest stable version 0.0.2 and I've sent two different fixes for vaughnlive.tv plugin since that release. You'll have to use stremlink from git if you want vaughnlive.tv to work. At least until 0.0.3 is released.

btw: vaughnlive.tv has 'best' and 'worst' stream quality, there's no 'low'. ;-)

**Comment by cirrusUK** [comment]
mmetak  cheers for the info sadly i didnt install the git build from AUR, doing it now.

**Comment by mmetak** [comment]
@cirrusUK I maintain both stable and -git versions of streamlink in AUR and if you need vaughnlive.tv plugin, I suggest you run the -git version. That vaughn site changes their live stream link and the plugin needs to be updated accordingly.

**Comment by cirrusUK** [comment]
mmetak cheers, have since installed streanlink-git and it works splendid, thanks for the info  ( and the code )

**Comment by cirrusUK** [comment]
@mmemtak   Just a heads up :  when installing both streamlink & streamlink-git using cower & makepkg, i had to pass updpkgsums to both.

**Comment by mmetak** [comment]
@cirrusUK Not sure why would you have to do that? Especially -git package since it's using git source. That one is in every -git package set to 'SKIP'. Even for me updpkgsums gives me the same sums and no one else reported anything about it.?

**Comment by cirrusUK** [comment]
@mmetak mmetak IDK but they would fail to install if i didnt updpkgsums,  maybe a misconfig on my machine.
