### ISSUE TITLE
Any way to have Twitch's reduced delay work on Streamlink?

### ISSUE THREAD

**Issue by KazukiMutou** [streamlink/streamlink#1676]
### Checklist

- [x] This is a feature request.
- [x] I have read the contribution guidelines.

### Description

Twitch now offers a "new" reduced delay option for broadcasters. But as of now, this only works when viewing on the website. Streamlink has an additional 5-8 second delay, regardless of what settings are used.

### Expected / Actual behavior

- 1-3 second stream delay for Twitch streams where the broadcaster has opted in for reduced delay.
- When viewing on the Twitch site, this works. However, with Streamlink it doesn't, even with hls-live-edge set to the minimal value.

### Reproduction steps / Explicit stream URLs to test

1. Open stream that has reduced delay on Twitch website.
2. Confirm it has reduced delay through the video stats.
3. Open same stream on Streamlink.
4. Streamlink stream has additional 5-8 second delay based on the settings picked.

### Comments, screenshots, etc.

I'm not sure if I'm just ill-informed and the ability is already there. I've tried changing a number of different settings from setting hls-live-edge to 1 and changing player-passthrough. None of the options I have tried reduce the delay from ~>7 seconds.

![reduceddelay](https://user-images.githubusercontent.com/7350221/40320292-74858d1a-5d2b-11e8-9606-3ce4f7f4445c.png)

**Comment by beardypig** [comment]
If anyone knows of a broadcaster using the low latency option frequently, let me know and I'll check it out. If i'm online on Gitter and you see a stream that is running low latency ping me.

**Comment by gravyboat** [comment]
@beardypig I checked a few streams this weekend and saw https://www.twitch.tv/lirik and https://www.twitch.tv/cohhcarnage using it.

**Comment by KazukiMutou** [comment]
@beardypig @back-to https://www.twitch.tv/elajjaz is currently live for another 6-7 hours as of this message with low latency enabled.

**Comment by beardypig** [comment]
Thanks @KazukiMutou, but it seems to be an HLS stream rather than a DASH stream. Maybe they just improved their infrastructure + player to provide lower latency... 

@bastimeyer where did you see they were using DASH?

There are a couple of improvements we could make to reduce the latency of the streams, we even tried before but it caused issues else where.

**Comment by bastimeyer** [comment]
I was referring to https://github.com/streamlink/streamlink/pull/1637#issuecomment-389300549
I'm usually not using the Twitch website, but that is indeed a HLS stream. I should have checked it myself first, sorry about that.

Looks like the m3u8 playlist doesn't contain the #EXT-X-TWITCH-PREFETCH data when loaded via Streamlink. Also, the number of segments is lower.
```
$ curl (streamlink twitch.tv/elajjaz best --stream-url)
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:3162
#EXT-X-TWITCH-ELAPSED-SECS:6324.000
#EXT-X-TWITCH-TOTAL-SECS:6336.000
#EXTINF:2.000,live
https://video-edge-c67d54.fra02.hls.ttvnw.net/v1/segment/CooDMPeoC9yY45Dj3B8xTuc14-ZTKMAPTU5MKtV3ps_Lewnx66KynF-9BKU9VJZSONoZCx7N3722HbebPJBbNqoIJ4RbZeD59wrbr7NF3xawr_4Q-hu_0f8vWIrfvScvctcaNsb0jjqlTSV0_MtHuIyyhl0Gq-cnEs6nL77spugfWV2XcjgHSahb1lorONp3bT8PUi1E7QamuM4bH_nlUzAyH3hybTasPGgMajkUjZ53oqljr1Jxs8XV-VzjYtXFIOChCfiuDSu88Q990A14m_lBbq_gMSIWUgpW-XxmBl7KfAzUkJKaEWCNAHwm_JwX3UfG5NkaKa2wTqF-Mgjy-p34PgjIAR_7RC00q3VUP2nUXsCW_snDUHZJYfxfppGz6zvLEdSqEcqUCtizf4jZ8m3iqDa5NU55Fi6XCHGMY6vnM4zSuVq9I2xcBGF16SKM8Af5sBDyguHC_B6J7PEuHGuYMBdjVOxmGUhcG0eCM9iNN6GjBu6cUJsXu_woJQuKn4coINET2tahol3bXhIQ3OeloCSyqMKDPtHjDn-95hoMtBEIoUp2cPNGYbPK.ts
#EXTINF:2.000,live
https://video-edge-c67d54.fra02.hls.ttvnw.net/v1/segment/CooDEHcqqsfLz1eRj6QYF6Lu5iNa-cdmxrLg7VcFq1yMHsZfE91C7RwYzrghJqV4mHCHGgsLRwyGqyQ0rvej_FMQujxjHxt4MLh4i2UQ2Z59rPxi6I_tCOs7yWlCGw0Y6SYYAHNvdr7nW3KEm3dJaqZd84Vsak0TbQWwRINGjw9NOO9Gljf6Bm4tHp_RZ7_Ci6YiQulPnnWojPztUFimcQWioKlx87moY_o1O-dtBlKrRwetjXchDMyZJyfVnyibYrSKmQejldb8c0Zj6qVezSw04-WMDZmINrdL4R39tKNNRKXz1KZTBF5xQkPT5eTGITL_gSnz4USireisIhbghzucd5Mwzpy96HfTBYkJxh51bUDi5wfZy3s3U6k1ZlUGPoZkFvG2CT1KSUDUIyCVD1BOKuX2bYDpR_3-nd-qRrI21MjOwfD0RxlYsQWVTmP5dWrBmBwqdd78gQ6dC-IOzjTN6PP9WMDCjKW_h0UuYhIpUjIUnoklxFY6Htq0bHGaF75ZY32-ZXvw8ay_9BIQ-xdGWyuTxarY0y1r-P_lVxoMf41XZdC9dKKAkCs_.ts
#EXTINF:2.000,live
https://video-edge-c67d54.fra02.hls.ttvnw.net/v1/segment/CooDhajSl3KLwJyvGrg8xnmISzHbhKAhjqje_fNqxxxe_V_Fa7nAugzT0cPnmj48ts3PdnkLzaxPpDqGJOEVZLg_VVQsu8pA9flu1K3rHap2HY_f5lbzuGF4swmGBgV1Ijx8ZfIrK8KmDWgmcJQbbLSqJCH3pxAkVZc64F9XbEQfUtMv0UfEHzNBrPJJr9tM8KF9jFxt5m4bkZ2unaM9U8NWqbjtSM95aUFh2OmrrLmt-keeRgvpdLROMPDCLtmIw8n4ODJSs8f6K7CCOCVghiOw4dx_aTW6aWZMIcjHW83LtVR8QlbSSFEv3d3NTE8aO9sW5tWBYpW_v7VcNZ1n2O6ESOCDlnd_oKl1KUHdTWAqrdDaW74__Pd06tnsqWlAXTCkEXQKvXDTpCYnokZnLpByuJOilf6WQ_-M5RD-A0YeUr7jTXDCid9NApu1zVNDRxWnh3gUaldHbfy8TM2vy9I9qFBkE6RZx1V68rn2GgJVfRTpo29NNtCsU6A4lZ8ycP-nz4HP5ulvAcOFfhIQaf2IVJHFVGaTFL2RFkKV2BoMD6XB__OTVlRd6dkV.ts
#EXTINF:2.000,live
https://video-edge-c67d54.fra02.hls.ttvnw.net/v1/segment/CooDg3-1pG6t5NNtAS-p4lyJBCQfLH1cbJSKo2IVc1npXfyCvAft01e812-6GgJycyKEgWvMtylS0oD0ne-EOpS1Ws4OgQv7zqJzT6B-iDiuyvjjb7h29eQ_6VrRZQk5OGsCa5OMt9QmQBz-Q5wMbMtiadnamU1sThRWx1iF-R6-jlMB-b0f8AYZipGGFoCN048vHKqzoeEh4If943Tp-UasIhHry8GZLR2kUQ-Cau8VgjL5iHg2WEe_k3QzTSrj_BVhQIYOIWjz3y36iMhG2D6VhXkzvG6dnCij5a4IPCn0XY1I7Rr5rZr2Rx0NSp45ZeiNPv81RNWD8tbAG5pquQdSvGkxxcFZatr59DrX8E6VIshbRC9fDRnwcDEO-IDqF6j2adXUKPVCK-u7RLNvBDB5Da4flsdxd2PapnTnLfLreCROOgwQG9AGFWgRLxcdu5P0L-Ndj8wa3Y5aqldDgxOBeEaIU5-SkqO96WVTB5ur5NKX12KeDI9sPCk-xcgPXxIyq6PYvlw0wYW-qRIQ4K7pl8wGqtb9KzswwGOSuhoMrDTr7gLaKlpXt4Wu.ts
#EXTINF:2.000,live
https://video-edge-c67d54.fra02.hls.ttvnw.net/v1/segment/CooDueUXKN84fqaropS7QttSVhvIEfIimR_TShAjWFSPodyrSTNGfYqCGBWs08aaOGAQGHREhg5xlunR_jM9pLq-Flra4AOrzVSYOM0q2PgaTupGeuPG2vugXv9COEPglbfZvzNE6JzL3_gwoBGxkkwITQfVd4YVtSdaZL1EXVYvG1JdpGLmFmi8J0vd3zJi2wIyUBi0Os4gfRktSkyedmYl7-3j_H2o90ae5c-PGieELdLpeZrW7x_b35L4P_z4nwGflGLGqEPAqj1GB9B3FuHmpS4lXI5Lqowqu1Bm7An-aQcYflCAQU40pPjpd-LTmxBuIQU7lvxgpMAz3JrZeYjkNH3OFCehUc52xuHIrcxkjW-i6Mk6G9nqpk7sRbwNvByYlEtHfyGpQj5kOJp71qF5W6TKIWcN4XtHHQlku3YYBPYcMAv7WbgF2WzAMcuHYseFdCKDsTi_MVQcO_iyUg5zsYi4lzIQxiz7nGCklFegFuyVO2UGjcBokAKW5SPSH-ZruHIdR5RdbBVG8xIQtm8zhn23hkiOql37qvAmnRoMhOdyuX9twJesEsgU.ts
#EXTINF:2.000,live
https://video-edge-c67d54.fra02.hls.ttvnw.net/v1/segment/CooDHDFgFm6uQnp0bgUN7VTRZ5mqBHOpr_yMTnjEJN2kSzfSB45x9wr2M8JBjmOfkQGvxmQd0e09yyanv1m1Nuu2vzro-3p6Rd8iOs1F7chDc0wMYPJs8kFRuV6lI-mcZ23nZyi2EJbEDh0Yvjl7Zz7pOm2AFoUhS1tmiDbsAFmyUYX2V6ilSpEBKf0K3P32lK2VUIYcLov--pRh0JjGz_xp8AklAUE2QXhxli4oAIi1xdg_3rSFDZiLDSxo9ZaVOxbKe1OUjww_n_zkoZ3n62dx1NScZ6NpUrq3jmhYWueBqAYaG3LNATz96wgeGvhMwJegRM0NsAP91XHSHXkLeFPXC3kfGy0p9OhzEOqG8WSJvYvYDU60s7ZQAy1L6So4xhGyhboQUKy82yB0nnoyMuIExjNZcD0w_FD8GUfk2DxQKlU1yTXMgxv7s_xm-xivVa0H4pTcXXqTXhk-sOVG8g70kpAC65Sr5yczajLW6Uy3dEs-7qj8eNhd3sBHmWy8f58T70768GUa_kxkrxIQv-hz64BqajcEBfMx9hSCbRoMGCsGgmk41ui1If7L.ts
```

**Comment by beardypig** [comment]
Ah true, could be an extra api parameter. I didn’t try the m3u8 playlist returned on the website for the low latency broadcaster. 
Any idea prefetch tags are, probably have to go digging around in the twitch source :)

**Comment by Hakkin** [comment]
I believe they're using something similar to [Periscope's "LHLS"](https://medium.com/@periscopecode/introducing-lhls-media-streaming-eb6212948bef)
The low-latency manifests can be obtained by including the `fast_bread=true` parameter when obtaining the master playlist. Streams that have low-latency enabled will have the `FUTURE="true"` tag in the master playlist.

**Comment by bastimeyer** [comment]
Thanks, @Hakkin.
So that explains why there's a higher number of (future-) segments and why the buffer length on their web player can be smaller than the length of each independent segment.

**Comment by gravyboat** [comment]
Huh very interesting. Sorry @beardypig I didn't realize they were just doing a workaround to make this happen as pointed out by Hakkin... I should have checked more thoroughly.

**Comment by beardypig** [comment]
Small update on this; with my new segmented downloader code I have managed to get Streamlink in-sync with Twitch for non-low latency videos, using `--hls-live-edge 1`. I am still working on low latency streams. 

However, Streamlink will likely never be able to reduce the delay to the same as Twitch. This is because the Twitch player _speeds up_ the video if it is lagging behind and it has sufficient future video buffered. Using Streamlink, if you experience any buffering that's it, you will lag behind until you restart the stream. I do not think this is avoidable as it is the job of the player to control the playback speed.

**Comment by kuon** [comment]
@beardypig Wouldn't be possible for streamlink to jump ahead instead of speeding up the video? A threshold could be used, for example 5 seconds. If streamlink has more than 5 seconds of future video buffered, it drops 5 second of video and makes the player jump ahead. This is of course just an idea, I don't know if it is feasible. But as I user, I wouldn't mind this behavior (if it is an option I can configure).

**Comment by beardypig** [comment]
@kuon good idea :) It might work - entire segments would have to be skipped. In twitch’s case that would be a second or two. The problem is that it might corrupt the stream and cause issues for some players, but if it is an option with sufficient warnings that should be up to the user. (Of course, there will always be people that don’t read those warnings...)
It is unlikely that streamlink will have extra video buffered though, is more likely the case that twitch has got ahead because one segment of video took a bit longer than expected to download and he video paused for a second. But, future I downloaded segments could be skipped to catch up - to maintain the live edge.

**Comment by h1z1** [comment]
Adjusting the playback speed of video is a bit stupid, I'd hope if that ever became something in streamlink it remained an option and off by default.  

Part of the issue with this is streamlink doesn't do connection pipeline like a browser would, there is a cost to establish a connection and tear it down.   I'm surprised they aren't running into serious buffering problems, or maybe they are.  

Buffers are there for a reason, otherwise they should be using chunked encoding or allow rtmp to clients.  _injest_ is however a completely different thing especially with IRL.  Bit OT for here though.

Fun fact, not all players can handel discontinuity in stream.  Timestamps for example confuse mpv/ffmpeg.  How bad depends on where it happened but three common ones are packets out of order, packets delayed and packets with the same timestamps.  All of which can happen due to multipathing on the Internet.   They aren't lost.

ex

```
V: 00:00:04 / 00:01:16 (3%) A-V:  2.461 ct:  0.246
[ffmpeg] NULL: illegal reordering_of_pic_nums_idc 9
Invalid audio PTS: 7.314286 -> 6.432000
[ffmpeg] NULL: illegal reordering_of_pic_nums_idc 9
[ffmpeg] NULL: illegal reordering_of_pic_nums_idc 9
[ffmpeg] NULL: illegal reordering_of_pic_nums_idc 9
[ffmpeg] NULL: illegal reordering_of_pic_nums_idc 9
[ffmpeg] NULL: illegal reordering_of_pic_nums_idc 9
[ffmpeg] NULL: illegal reordering_of_pic_nums_idc 9
[ffmpeg] NULL: illegal reordering_of_pic_nums_idc 9
AV: 00:00:04 / 00:01:16 (5%) A-V:  1.333 ct:  0.246
Invalid video timestamp: 6.920000 -> 6.503000
```

Same TS, completely valid.
```
AV: 00:00:23 / 00:05:25 (7%) A-V:  0.000
Invalid video timestamp: 23.975000 -> 23.975000
AV: 00:00:25 / 00:05:25 (7%) A-V:  0.000
Invalid video timestamp: 25.141000 -> 25.141000
```

etc.   Point is while Twitch's own players may handle these issues needlessly decreasing buffers can cause other problems.

**Comment by Francesco149** [comment]
I managed to achieve latency less than 1 second worse than the browser player with these settings

good enough for me, but it would be nice to tune it further

```
player=mpv --cache=no
hls-segment-threads=10
hds-segment-threads=10
stream-segment-threads=10
hls-live-edge=1
player-passthrough=hls,http
```

**Comment by bastimeyer** [comment]
@Francesco149 

> player-passthrough=hls

By using this parameter, you're just passing through the resolved HLS master playlist URL to MPV and using it as its input parameter. MPV is then downloading the stream segments by itself instead of reading a concatenated stream from Streamlink, which means that both the `hls-segment-threads` and `hls-live-edge` parameters of Streamlink become pointless. It's basically the same as running
```bash
mpv --cache=no "$(streamlink --stream-url URL QUALITY)"
```
The other parameters you've listed are unrelated to viewing Twitch streams...

The reason why you're having a slightly lower delay by using this method is because you've disabled (minimized) MPV's network cache value and you're not using Streamlink's additional caching layer and its default configuration like when you're piping the concatenated stream to the player process:
https://mpv.io/manual/stable/#options-cache

However, if you properly set Streamlink's parameters, you'll see that there's almost no difference in streaming delay. It mostly just depends on the timing and availability of the HLS playlist/segments while launching the stream.
```bash
streamlink -p mpv -a '--cache=no {filename}' --hls-live-edge 1 --hls-segment-threads 2 URL QUALITY
```

You can compare it like this:
```bash
#!/usr/bin/env bash
CHANNEL="name"
streamlink -p mpv -a '--cache=no --title "With Streamlink" {filename}' --hls-live-edge 1 --hls-segment-threads 2 "twitch.tv/${CHANNEL}" best & \
mpv --cache=no --title "Without Streamlink" "$(streamlink --stream-url "twitch.tv/${CHANNEL}" best)"
```

Since MPV doesn't support Twitch's custom HLS implementation, you won't be able to beat their web player for now, but if this gets implemented in Streamlink some day in the future, you should hopefully be able to see a lower delay than just using MPV.

**Comment by Francesco149** [comment]
yep, i imagined it would bypass all the other settings, i just included them cause i wasn't 100% sure.

hls-live-edge 1 by itsef is indeed lower latency but I guess my internet is too bad cause it buffers after like 1 seconds and falls behind in delay

**Comment by KazukiMutou** [comment]
Getting an error trying to load the plugin. Using latest streamlink.

```
[plugin.twitch][warning] Test Plugin - Low Latency
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 18, in <module>
    main()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 1002, in main
    handle_url()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 533, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 413, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 431, in get_streams
    return self.streams(*args, **kwargs)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 333, in streams
    ostreams = self._get_streams()
  File "C:\Users\wolka\AppData\Roaming\streamlink\plugins\twitch.py", line 960, in _get_streams
    return self._get_hls_streams("live")
  File "C:\Users\wolka\AppData\Roaming\streamlink\plugins\twitch.py", line 923, in _get_hls_streams
    force_restart=not stream_type == "live")
  File "C:\Users\wolka\AppData\Roaming\streamlink\plugins\twitch.py", line 256, in parse_variant_playlist
    parser = hls_playlist_load(res.text, base_uri=res.url, parser=TwitchM3U8Parser)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls_playlist.py", line 276, in load
    return parser(base_uri).parse(data)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls_playlist.py", line 242, in parse
    self.parse_line(lineno, line)
TypeError: parse_line() takes 2 positional arguments but 3 were given

**Comment by back-to** [comment]
> TypeError: parse_line() takes 2 positional arguments but 3 were given

This won't work with `0.14.2`

**Nightly version** of Streamlink is required or a version with this changes https://github.com/streamlink/streamlink/commit/2122ebf401eb868718a0a15c7167c83d4b0b6467

[Installer](
https://bintray.com/streamlink/streamlink-nightly/streamlink/_latestVersion/#files) or [Portable](https://github.com/beardypig/streamlink-portable)

**Comment by KazukiMutou** [comment]
Cool, seems to work pretty fine! Very happy to see this working with streamlink! Looking forward to when this gets fixed up and implemented officially. But for now, thank you very much for this!


![oboqpc7](https://user-images.githubusercontent.com/7350221/47041486-2f5aba80-d189-11e8-9a42-77be3acb8fb3.jpg)

**Comment by michaelK545** [comment]
The Low latency plugin is insane... im ahead of the browser with streamlink using mpv and no additional cache. Thanks 
![4](https://user-images.githubusercontent.com/23260755/50046954-69bad800-00a4-11e9-9ecb-bb46429b41b9.png)

**Comment by Jaid** [comment]
Thanks a lot, @back-to! Had to increase `--hls-live-edge` to 2 to avoid micro-buffering, but besides that it is working perfectly and indeed faster (less delay) than the HTML5 player.

Here is the command I currently use for watching and recording (Windows 10, VLC player, git-bash):

```bash
"$HOME/AppData/Local/Streamlink/bin/streamlink.exe" \
$TWITCH_CHANNEL_URL --twitch-oauth-token=$TWITCH_OAUTH_TOKEN \
--default-stream=best --retry-open=6 --retry-streams=6 --retry-max=10 \
--ringbuffer-size=256M --hls-live-edge=2 \
--stdout \
| tee "$RECORDING_PATH" \
| vlc --meta-title=$TWITCH_CHANNEL_URL --qt-minimal-view \
--mmdevice-volume="0.2" --qt-max-volume=200 --no-volume-save -
```

**Comment by VenusMan** [comment]
Hello,

I am completely out of loop how to setup the low latency plugin. I have read the tutorials, but they are pain in the ass to even understand them. It can't be that hard to just watch low latency streams via streamlink without additional latency.

I am using the Streamlink Twitch GUI, because I couldn't bothered to type commands just to watch streams. But I would still like to know how and if it is possible to make the plugin work with the GUI somehow in its settings.

Thank you.

**Comment by bastimeyer** [comment]
@VenusMan 
Just follow the instructions from the comment above, it's not that difficult. I think @back-to has explained it very well already:
https://github.com/streamlink/streamlink/issues/1676#issuecomment-430304591

But before this thread gets spammed with further questions, let me try to explain it a bit more in detail.

Also please note that there is no guarantee that this test plugin will work for all streams. It's a test plugin which hasn't been submitted as a pull request to be merged into Streamlink, because it requires a custom HLS implementation for Twitch's low latency streaming.

----

1. **Streamlink setup**
   Install the latest Streamlink version from the master branch / nightly build / etc.  
   https://streamlink.github.io/install.html
2. **Custom plugin setup**
   Download the test plugin from the link above (or [here](https://gist.github.com/back-to/8e9ed3c60e5932d8c7a67ccd43b906d0/)) as `twitch.py` and put it into [the directory described in the documentation's sideloading section](https://streamlink.github.io/cli.html#sideloading-plugins). Streamlink will pick up custom plugins stored there automatically. The sideloading path depends on your operating system:
   - Linux/macOS 
     `${XDG_CONFIG_HOME:-${HOME}/.config}/streamlink/plugins`
   - Windows
     `%APPDATA%\streamlink\plugins`  
     (default `%APPDATA%` path is `C:\Users\%USERNAME%\AppData\Roaming`)

   If you don't like this directory, you can also set the [`--plugin-dirs DIRECTORY`](https://streamlink.github.io/cli.html#cmdoption-plugin-dirs) parameter, either in your (global) Streamlink [config file](https://streamlink.github.io/cli.html#configuration-file), or by manually specifying it. If you're using the Twitch GUI, enable advanced settings in the main settings menu first, then go to the streaming menu and add it to Streamlink's custom parameters.

3. **Streamlink config**
   Set Streamlink's [`--hls-live-edge`](https://streamlink.github.io/cli.html#cmdoption-hls-live-edge) value to `1` (or `2` if your connection isn't good enough).  
   In the Twitch GUI, go to the streaming settings menu in order to do that.

4. **Player config**
   Remove (or reduce) any buffering on the player-side. The player options for that (may) depend on the selected stream transport method, since it decides where the player will read the stream data from.
   If you're using MPV, simply set the `--no-cache` player parameter. The Twitch GUI also has a checkbox for that in its MPV player preset.

**Comment by VenusMan** [comment]
@bastimeyer 
Thank you, I got the plugin running, somewhat, now if I try to open a stream this error appears (no error if I remove the plugin):
![error](https://user-images.githubusercontent.com/23454820/51518418-76121d80-1e26-11e9-9401-165e97989e9e.PNG)

It seems like error in the code? But could as well be error on my side. 
I have set "Streamlink" as streaming provider in the GUI and "MPV" as the predefined player.

Strange fact, twitch streams on VLC run at 0%-0.5% CPU load, while streams on MPV run at 5%-10% CPU load 🤔.

**Comment by gravyboat** [comment]
I will lock it @bastimeyer. There is more than enough help and explanation in this thread.
