### ISSUE TITLE
Facebook plugin broke again?

### ISSUE THREAD

**Issue by Twilight0** [streamlink/streamlink#1761]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Was testing some live streams today from facebook with both regular CLI implementation and the streamlink tester I made for Kodi.

### Expected / Actual behavior

With the latest 0.13.0 streams should have been playing fine

### Reproduction steps / Explicit stream URLs to test

https://www.facebook.com/nba/videos/10156603019383463/

### Logs

_Logs are always required for a bug report, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l)
Make sure to **remove username and password**
You can upload your logs to https://gist.github.com/ or_

```
PS C:\Users\Twilight> streamlink.exe -l debug https://www.facebook.com/nba/videos/10156603019383463/ best
[console][debug] OS:         Windows 10
[console][debug] Python:     2.7.15
[console][debug] Streamlink: 0.13.0
[console][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.48.0)
[console][info] Found matching plugin facebook for URL https://www.facebook.com/nba/videos/10156603019383463/
[plugin.facebook][debug] Falling back to playlist regex
error: No playable streams found on this URL: https://www.facebook.com/nba/videos/10156603019383463/
```

### Comments, screenshots, etc.

None

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
Do you need to login for that video?

**Comment by Twilight0** [comment]
No I don't, its public. It must have been something random I guess, but from my tests I am still getting errors.

Error Type: <class 'streamlink.exceptions.PluginError'>
                                            Error Contents: Unable to parse XML: 'NoneType' object is not callable ('<?xml version="1.0"?>\n\n<MPD\n  t ...)
                                            Traceback (most recent call last):
                                              File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\plugin.video.streamlink-tester\main.py", line 27, in <module>
                                                player.play(url)
                                              File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\plugin.video.streamlink-tester\resources\lib\modules\player.py", line 92, in play
                                                stream = router(url)
                                              File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\plugin.video.streamlink-tester\resources\lib\modules\player.py", line 38, in router
                                                streams = plugin.streams()
                                              File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\script.module.streamlink.base\resources\lib\streamlink\plugin\plugin.py", line 301, in streams
                                                ostreams = self._get_streams()
                                              File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\script.module.streamlink.base\resources\lib\streamlink\plugins\facebook.py", line 31, in _get_streams
                                                streams.update(DASHStream.parse_manifest(self.session, stream_url))
                                              File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\script.module.streamlink.base\resources\lib\streamlink\stream\dash.py", line 163, in parse_manifest
                                                mpd = MPD(session.http.xml(res, ignore_ns=False), base_url=urlunparse(urlp), url=url)
                                              File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\script.module.streamlink.base\resources\lib\streamlink\plugin\api\http_session.py", line 108, in xml
                                                return parse_xml(res.text, *args, **kwargs)
                                              File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\script.module.streamlink.base\resources\lib\streamlink\utils\__init__.py", line 98, in parse_xml
                                                raise exception("Unable to parse {0}: {1} ({2})".format(name, err, snippet))
                                            PluginError: Unable to parse XML: 'NoneType' object is not callable ('<?xml version="1.0"?>\n\n<MPD\n  t ...)

**Comment by Twilight0** [comment]
No I don't, its public. It must have been something random I guess, but from my tests I am still getting errors.

    Error Type: <class 'streamlink.exceptions.PluginError'>
    Error Contents: Unable to parse XML: 'NoneType' object is not callable ('<?xml version="1.0"?>\n\n<MPD\n  t ...)
    Traceback (most recent call last):
    File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\plugin.video.streamlink-tester\main.py", line 27, in <module>
    player.play(url)
    File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\plugin.video.streamlink-tester\resources\lib\modules\player.py", line 92, in play
    stream = router(url)
    File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\plugin.video.streamlink-tester\resources\lib\modules\player.py", line 38, in router
    streams = plugin.streams()
    File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\script.module.streamlink.base\resources\lib\streamlink\plugin\plugin.py", line 301, in streams
    ostreams = self._get_streams()
    File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\script.module.streamlink.base\resources\lib\streamlink\plugins\facebook.py", line 31, in _get_streams
    streams.update(DASHStream.parse_manifest(self.session, stream_url))
    File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\script.module.streamlink.base\resources\lib\streamlink\stream\dash.py", line 163, in parse_manifest
    mpd = MPD(session.http.xml(res, ignore_ns=False), base_url=urlunparse(urlp), url=url)
    File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\script.module.streamlink.base\resources\lib\streamlink\plugin\api\http_session.py", line 108, in xml
    return parse_xml(res.text, *args, **kwargs)
    File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\script.module.streamlink.base\resources\lib\streamlink\utils\__init__.py", line 98, in parse_xml
    raise exception("Unable to parse {0}: {1} ({2})".format(name, err, snippet))
   PluginError: Unable to parse XML: 'NoneType' object is not callable ('<?xml version="1.0"?>\n\n<MPD\n  t ...)

**Comment by Twilight0** [comment]
I cleaned up python's cache and it appears ok now.

**Comment by beardypig** [comment]
Cool, I just tested it and it worked fine too.
