### ISSUE TITLE
ImportError: cannot import name __version__

### ISSUE THREAD

**Issue by ryanjgillies** [streamlink/streamlink#1801]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

I've been using the PPA version of streamlink provided by WebUpd8, but realised (today of all days, just before the World Cup) that it's still on 0.9.0 and Streamlink has progressed to 0.13.0 since then.

So I uninstalled and attempted a manual installation (pip encountered far too many problems last time I tried. However the manual installation is just not happy! There was a requests version conflict at first, I resolved that, but now I'm getting this, and I can't figure out where the issue lies...

```
manager@Cellar:~/streamlink$ streamlink -V
Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 9, in <module>
    load_entry_point('streamlink==0.13.0+31.g5a36e51', 'console_scripts', 'streamlink')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/streamlink-0.13.0+31.g5a36e51-py2.7.egg/streamlink_cli/main.py", line 19, in <module>
    from websocket import __version__ as websocket_version
ImportError: cannot import name __version__
```
Can anyone help me trace the problem?
I attempted the solution for a similar problem from #1307, but no luck. 

Running Lubuntu 16.04.4 LTS, Python 2.7.12

**Comment by ryanjgillies** [comment]
I have no idea what the issue was, but this can be closed now.

I uninstalled streamlink and reinstalled via pip. After a brief cffi version mismatch issue, the problem has now been resolved and everything is functioning perfectly again!
