### ISSUE TITLE
Audio Spanish

### ISSUE THREAD

**Issue by Toni195** [streamlink/streamlink#1917]
I don't hear this video in Spanish, why?,  Is there any way I can keep it from being heard in English?
```
https://www.atresplayer.com/antena3/series/el-cuento-de-la-criada/temporada-1/capitulo-6-el-lugar-de-la-mujer_5b364bee7ed1a8dd360b5b7b/
```

### Logs

```
"C:\Program Files (x86)\Streamlink\bin\streamlink.exe" h
ttps://www.atresplayer.com/antena3/series/el-cuento-de-la-criada/temporada-1/cap
itulo-6-el-lugar-de-la-mujer_5b364bee7ed1a8dd360b5b7b/ best --player ffplay -l d
ebug
[cli][debug] OS:         Windows 7
[cli][debug] Python:     3.5.2
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin atresplayer for URL https://www.atresplayer.co
m/antena3/series/el-cuento-de-la-criada/temporada-1/capitulo-6-el-lugar-de-la-mu
jer_5b364bee7ed1a8dd360b5b7b/
[plugin.atresplayer][debug] API URL: https://api.atresplayer.com/client/v1/playe
r/episode/5b364bee7ed1a8dd360b5b7b
[plugin.atresplayer][debug] Stream source: https://geodeswowa3player.akamaized.n
et/vcg/_definst_/assets4/2018/06/29/7875368D-BF45-4012-9EBC-C4F78984B672/hls.smi
l/playlist.m3u8?pulse=assets4%2F2018%2F06%2F29%2F7875368D-BF45-4012-9EBC-C4F7898
4B672%2F%7C1531195580%7Cb6e79f7291966a25070a79138cd19cb9 (application/vnd.apple.
mpegurl)
[stream.hls][debug] Using external audio tracks for stream 1080p (language=es, n
ame=Spanish)
[stream.hls][debug] Using external audio tracks for stream 720p (language=es, na
me=Spanish)
[stream.hls][debug] Using external audio tracks for stream 480p (language=es, na
me=Spanish)
[stream.hls][debug] Using external audio tracks for stream 360p (language=es, na
me=Spanish)
[stream.hls][debug] Using external audio tracks for stream 240p (language=es, na
me=Spanish)
[plugin.atresplayer][debug] Stream source: https://geodeswowa3player.akamaized.n
et/vcg/_definst_/assets4/2018/06/29/7875368D-BF45-4012-9EBC-C4F78984B672/dash.sm
il/manifest_mvlist.mpd (application/dash+xml)
[cli][info] Available streams: 240p (worst), 240p+a128k, 360p, 360p+a128k, 480p,
 480p+a128k, 720p, 720p+a128k, 1080p, 1080p+a128k (best)
[cli][info] Starting player: ffplay
....................
....................
....................
```

**Comment by Toni195** [comment]
@beardypig
It doesn't work.

MPD: English.
M3U8: Without audio.
Link atresplayer.com: English.
F4M: Spanish.

**Comment by back-to** [comment]
> M3U8

```
[stream.hls][debug] Download of segment 17 complete
[stream.hls][debug] Adding segment 39 to queue
[stream.hls][debug] Download of segment 18 complete
[stream.hls][debug] Adding segment 40 to queue
[stream.hls][debug] Cutting off 12 bytes of garbage before decrypting
Exception in thread Thread-HLSStreamWriter:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "src/streamlink/stream/segmented.py", line 167, in run
    self.write(segment, result)
  File "src/streamlink/stream/hls.py", line 135, in write
    self.reader.buffer.write(pkcs7_decode(decrypted_chunk))
  File "src/streamlink/stream/hls.py", line 31, in pkcs7_decode
    raise StreamError("Input is not padded or padding is corrupt, got padding size of {0}".format(val))
streamlink.exceptions.StreamError: Input is not padded or padding is corrupt, got padding size of 188
```

that may be because of my geographical location,
could you post a log of your Issue with the m3u8 stream.

but they are probably not fixable https://github.com/streamlink/streamlink/issues/1898

---

> MPD

it is english because the first stream gets overwritten by the 2nd with the same name.

https://github.com/streamlink/streamlink/blob/577617a2383cc75c6c94160b36aeccd7bd3b4bcf/src/streamlink/stream/dash.py#L207

this could be easily added, there are some solutions
- **ugly** , `_alt` for the 2nd stream
- **better**, `--locale` only show the first stream or your selected language

---

you could also use the mpd url directly in VLC, it works there.

**Comment by beardypig** [comment]
We should consider the locale when picking the audio stream :)

**Comment by beardypig** [comment]
@Toni195 can you try the `m3u8` version and add the `--ffmpeg-verbose` option?

**Comment by Toni195** [comment]
The mpd link works in vlc without any problem, it gives me the option to choose the English and Spanish language from the "Audio > Audio Track" tab.

The link that I have published in this topic has been removed from atresplayer, I have taken another chapter of the same series that also has English and Spanish language.

Link to the video:
```
https://www.atresplayer.com/antena3/series/el-cuento-de-la-criada/temporada-1/capitulo-8-el-jezabel_5b3f9be87ed1a839c9fb9e0d/
```

Logs:
```
streamlink https://geodeswowa3player.akamaized.net/vcg/_definst_/assets4/2018/07/06/83CCD249-2559-4D35-8454-C29093277ECA/hls.smil/playlist.m3u8?pulse=assets4%2F2018%2F07%2F06%2F83CCD249-2559-4D35-8454-C29093277ECA%2F%7C1531405106%7Cdc239936c9322585e5cec8280aea39a6 best --player ffplay --ffmpeg-verbose
[cli][info] Found matching plugin hls for URL https://geodeswowa3player.akamaized.net/vcg/_definst_/assets4/2018/07/06/83CCD249-2559-4D35-8454-C29093277ECA/hls.smil/playlist.m3u8?pulse=assets4%2F2018%2F07%2F06%2F83CCD249-2559-4D35-8454-C29093277ECA%2F%7C1531405106%7Cdc239936c9322585e5cec8280aea39a6
[cli][info] Available streams: 240p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Starting player: ffplay
[cli][info] Got HTTP request from Lavf/58.17.101
[cli][info] Opening stream: 1080p (hls-multi)
ffmpeg version N-91449-g09628cb1b4 Copyright (c) 2000-2018 the FFmpeg developers

  built with gcc 7.3.1 (GCC) 20180710
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --e
nable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libblur
ay --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-
libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enab
le-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-li
bvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --en
able-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-
libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enabl
e-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enabl
e-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enab
le-dxva2 --enable-avisynth
  libavutil      56. 18.102 / 56. 18.102
  libavcodec     58. 21.104 / 58. 21.104
  libavformat    58. 17.101 / 58. 17.101
  libavdevice    58.  4.101 / 58.  4.101
  libavfilter     7. 25.100 /  7. 25.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
  libpostproc    55.  2.100 / 55.  2.100
Input #0, mpegts, from '\\.\pipe\ffmpeg-3784-575':
  Duration: N/A, start: 0.080000, bitrate: N/A
  Program 1
    Stream #0:0[0x102]: Data: timed_id3 (ID3  / 0x20334449)
    Stream #0:1[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(pro
gressive), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
Input #1, mpegts, from '\\.\pipe\ffmpeg-3784-697':
  Duration: N/A, start: 0.000000, bitrate: 119 kb/s
  Program 1
    Stream #1:0[0x102]: Data: timed_id3 (ID3  / 0x20334449)
    Stream #1:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, ster
eo, fltp, 119 kb/s
Output #0, mpegts, to 'pipe:1':
  Metadata:
    encoder         : Lavf58.17.101
    Stream #0:0: Data: timed_id3 (ID3  / 0x20334449)
    Stream #0:1: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressiv
e), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
    Stream #0:3: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, flt
p, 119 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
  Stream #1:0 -> #0:2 (copy)
  Stream #1:1 -> #0:3 (copy)
Press [q] to stop, [?] for help
[mpegts @ 0000000000582d00] Thread message queue blocking; consider raising the
thread_queue_size option (current value: 8)
[cli][info] HTTP connection closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by beardypig** [comment]
Thanks @Toni195, this should be fixed by #1926.

**Comment by Toni195** [comment]
```
streamlink hls://https://www.atresplayer.com/antena3/series/el-cuento-de-la-criada/temporada-1/capitulo-8-el-jezabel_5b3f9be87ed1a839c9fb9e0d/ best --player ffplay
[cli][info] Found matching plugin hls for URL hls://https://www.atresplayer.com/antena3/series/el-cuento-de-la-criada/temporada-1/capitulo-8-el-jezabel_5b3f9be87ed1a839c9fb9e0d/
error: Failed to parse playlist: Missing #EXTM3U header
```

**Comment by Toni195** [comment]
Many thanks to everyone who has made it possible for Spanish audio to work on mpd, f4m, m3u8 and atresplayer.com links ;)

MPD:
```
streamlink https://geodeswowa3player.akamaized.net/vcg/_definst_/assets4/2018/07/06/83CCD249-2559-4D35-8454-C29093277ECA/dash.smil/manifest_mvlist.mpd best --player ffplay 
```

M3U8:
```
streamlink https://geodeswowa3player.akamaized.net/vcg/_definst_/assets4/2018/07/06/83CCD249-2559-4D35-8454-C29093277ECA/hls.smil/playlist.m3u8?pulse=assets4%2F2018%2F07%2F06%2F83CCD249-2559-4D35-8454-C29093277ECA%2F%7C1531415455%7C95291c5710c66d150bb8d869c063a368 best --player ffplay 
```

F4M:
```
streamlink http://geodeswowsmootha3player.antena3.com/vcgsm/_definst_/smil:assets4/2018/07/06/83CCD249-2559-4D35-8454-C29093277ECA/dash.smil/manifest.f4m best --player ffplay 
```

atresplayer.com:
```
streamlink https://www.atresplayer.com/antena3/series/el-cuento-de-la-criada/temporada-1/capitulo-8-el-jezabel_5b3f9be87ed1a839c9fb9e0d/ best --player ffplay
```

You can close this issue.

Greetings from Spain.

**Comment by beardypig** [comment]
@Toni195 no problem. We'll close this when #1926 is merged :)
