### ISSUE TITLE
fails to build on archlinux [AUR makepkg]

### ISSUE THREAD

**Issue by cirrusUK** [streamlink/streamlink#2002]
treamlink-git 0.14.2.r85.g2cfa2110-1 fails to build on archlinux using makepkg

### Expected / Actual behavior

i expec it to build as it has done so in the past

### Reproduction steps / Explicit stream URLs to test

1. ... build streamlink-git from aur using makepkg
2. ...
3. ...

### Log output

```
======================================================================
FAIL: test_itertags_multi_attrs (tests.test_plugin_utils.TestPluginUtil)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cirrus/build/aur/streamlink-git/src/streamlink/tests/test_plugin_utils.py", line 54, in test_itertags_multi_attrs
    self.assertEqual(metas[0].text, None)
AssertionError: 'Title' != None

======================================================================
FAIL: test_no_end_tag (tests.test_plugin_utils.TestPluginUtil)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cirrus/build/aur/streamlink-git/src/streamlink/tests/test_plugin_utils.py", line 75, in test_no_end_tag
    self.assertEqual(links[0].text, None)
AssertionError: '' != None

----------------------------------------------------------------------
Ran 817 tests in 14.240s

FAILED (failures=2, skipped=12)
Test failed: <unittest.runner.TextTestResult run=817 errors=0 failures=2>
error: Test failed: <unittest.runner.TextTestResult run=817 errors=0 failures=2>
==> ERROR: A failure occurred in check().
    Aborting...
==> Removing installed dependencies...

```

### Additional comments, screenshots, etc.

it might well be a problem with the archlinux aur packager/ maintainer, if so, sorry fot the noise

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
@cirrusUK see #1999 :)

**Comment by back-to** [comment]
closing, the current git version works again.
