### ISSUE TITLE
i get this error when i run streamlink

### ISSUE THREAD

**Issue by Joseph65** [streamlink/streamlink#2004]
$ streamlink
Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 7, in <module>
    from streamlink_cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/streamlink_cli/main.py", line 21, in <module>
    from streamlink import __version__ as streamlink_version
  File "/usr/local/lib/python2.7/dist-packages/streamlink/__init__.py", line 86, in <module>
    from .api import streams
  File "/usr/local/lib/python2.7/dist-packages/streamlink/api.py", line 1, in <module>
    from .session import Streamlink
  File "/usr/local/lib/python2.7/dist-packages/streamlink/session.py", line 9, in <module>
    from streamlink.logger import StreamlinkLogger, Logger
  File "/usr/local/lib/python2.7/dist-packages/streamlink/logger.py", line 7, in <module>
    from streamlink.compat import is_py2
  File "/usr/local/lib/python2.7/dist-packages/streamlink/compat.py", line 48, in <module>
    from backports.shutil_which import which
  File "/usr/local/lib/python2.7/dist-packages/backports/shutil_which.py", line 12, in <module>
    def backport_which(cmd, mode=os.F_OK | os.X_OK, path=None):
AttributeError: 'module' object has no attribute 'F_OK'

**Comment by gravyboat** [comment]
We're going to need more details than what you have provided. What version of Streamlink are you running? How did you install Streamlink? Have you tried uninstalling and then reinstalling it? Is this the first time you've installed Streamlink and you're now getting issues?

**Comment by bastimeyer** [comment]
Closing, as there haven't been any responses during the past week.

Please try re-installing Streamlink
https://streamlink.github.io/install.html

**Comment by lucavb** [comment]
If you don't mind, I'd like to reopen this issue as I am facing it as well. I am running macOS High Sierra 10.13.6 and streamlink 0.14.2 installed from homebrew. I have tried reinstalling view brew remove streamlink and brew install streamlink, the error keeps persisting. And the issue has occurred since maybe a couple of days. Do you need anything else? I've included my traceback. 
[trace.txt](https://github.com/streamlink/streamlink/files/2307586/trace.txt)

**Comment by bastimeyer** [comment]
@lucavb Please open a new issue and include the log output in there (in the post itself). Thanks
