### ISSUE TITLE
Module has no attribute 'F_OK'

### ISSUE THREAD

**Issue by lucavb** [streamlink/streamlink#2025]
## Bug Report

- [x ] This is a bug report and I have read the contribution guidelines.

### Description

So the bug basically occurs every time I try to open up a twitch stream. It pretty much immediately fails to the attached error. I am running version 0.14.2 installed via homebrew for Mac on 10.13.6. 

`streamlink twitch.tv/playoverwatch best`

### Expected / Actual behavior

Streamlink opening up the VLC player as expected and starting the stream.

### Reproduction steps / Explicit stream URLs to test

1. Install streamlink via homebrew
2. start a twitch stream with the command above

### Log output

```
Traceback (most recent call last):
  File "/usr/local/Cellar/streamlink/0.14.2/libexec/bin/streamlink", line 11, in <module>
    load_entry_point('streamlink==0.14.2', 'console_scripts', 'streamlink')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2707, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2325, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2331, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Cellar/streamlink/0.14.2/libexec/lib/python2.7/site-packages/streamlink_cli/main.py", line 21, in <module>
    from streamlink import __version__ as streamlink_version
  File "/usr/local/Cellar/streamlink/0.14.2/libexec/lib/python2.7/site-packages/streamlink/__init__.py", line 86, in <module>
    from .api import streams
  File "/usr/local/Cellar/streamlink/0.14.2/libexec/lib/python2.7/site-packages/streamlink/api.py", line 1, in <module>
    from .session import Streamlink
  File "/usr/local/Cellar/streamlink/0.14.2/libexec/lib/python2.7/site-packages/streamlink/session.py", line 9, in <module>
    from streamlink.logger import StreamlinkLogger, Logger
  File "/usr/local/Cellar/streamlink/0.14.2/libexec/lib/python2.7/site-packages/streamlink/logger.py", line 7, in <module>
    from streamlink.compat import is_py2
  File "/usr/local/Cellar/streamlink/0.14.2/libexec/lib/python2.7/site-packages/streamlink/compat.py", line 48, in <module>
    from backports.shutil_which import which
  File "/usr/local/Cellar/streamlink/0.14.2/libexec/vendor/lib/python2.7/site-packages/backports/shutil_which.py", line 12, in <module>
    def backport_which(cmd, mode=os.F_OK | os.X_OK, path=None):
AttributeError: 'module' object has no attribute 'F_OK'
```

### Additional comments, screenshots, etc.

I tried reinstalling streamlink via homebrew and also removed the python2.7 installation from homebrew and then reinstalled streamlink. No luck.

[traceback.txt](https://github.com/streamlink/streamlink/files/2314625/traceback.txt)

**Comment by bastimeyer** [comment]
Does the same issue occor after installing Streamlink via python-pip?

**Comment by lucavb** [comment]
I just managed to get it installed with python2.7/pip2 and the error does not occur.

**Comment by back-to** [comment]
you can find similar issues on the Homebrew issue tracker,
most of the time it's an issue with **multiple installed python versions** which is an User error.

closing as you solved it already
and _Homebrew packaging_ looks like a common issue over there.
