### ISSUE TITLE
Problems with filmon

### ISSUE THREAD

**Issue by LustigesBassgebrumm** [streamlink/streamlink#2034]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

Hello,
I have some problems with the plugin Filmon. All streams end after a few minutes. The length to standstill is different. Can someone tell me what I need to do to fix the bugs? The debug output provides the following:

root@vusolo2:~# /usr/sbin/streamlinksrv manualstart
[streamlinksrv][info] Sun Aug 26 16:12:33 2018 Server (1.1.0) started
[streamlinksrv][info] Host:          vusolo2
[streamlinksrv][info] Port:          8088
[streamlinksrv][info] OS:            Linux-3.13.5-mips-with-glibc2.0
[streamlinksrv][info] Python:        2.7.9
[streamlinksrv][info] Streamlink:    0.14.2 / 06.07.2018
[streamlinksrv][info] Requests(2.12.4), Websocket(0.48.0)
[streamlinksrv][info] Processing URL: https://www.filmon.com/tv/itv1
[streamlinksrv][info] Found matching plugin filmon for URL https://www.filmon.com/tv/itv1
[streamlinksrv][info] Available streams:
low (worst), high (best)
[streamlinksrv][info] Opening stream: high (hls-filmon)
[streamlinksrv][error] Got exception: Read timeout
['Traceback (most recent call last):', '  File "/usr/sbin/streamlinksrv", line 207, in Stream', '    shutil.copyfileobj(fd, http.wfile)', '  File "/usr/lib/python2.7/shutil.py", line 49, in copyfileobj', '    buf = fsrc.read(length)', '  File "/usr/lib/python2.7/site-packages/streamlink/stream/segmented.py", line 207, in read', '    timeout=self.timeout)', '  File "/usr/lib/python2.7/site-packages/streamlink/buffers.py", line 111, in read', '    raise IOError("Read timeout")', 'IOError: Read timeout']
[streamlinksrv][info] Stream ended
[streamlinksrv][info] Closing currently open stream...

[streamlinksrv][info] Processing URL: https://www.filmon.com/tv/itv2
[streamlinksrv][info] Found matching plugin filmon for URL https://www.filmon.com/tv/itv2
[streamlinksrv][info] Available streams:
low (worst), high (best)
[streamlinksrv][info] Opening stream: high (hls-filmon)
[stream.hls][warning] Failed to reload playlist: Unable to open URL: https://edge-1165-ch-gv.filmon.com/live/67.high.stream/playlist.m3u8?id=035bca1a71b11fce016d28acd3dbe
a51cbc96ddfe5b9ed3f8fe3286df6a738d3644657a9ef0048b105a7e83b4da96b9221a7eab05727c4c69cbeabc4560e8b48bbd0afa2214aa8bc665f417d3517269b347d5fcdf6dbb2bfbcb37a8137899934aa5ddf4
b990b3a14e5064f13f2501cd60f6cd2cf7b42563e1a49c465cc5ed69dc969fb71a2106c1a4f6b259eebe36a25a732ae492d96b6af (403 Client Error: Forbidden for url: https://edge-1165-ch-gv.fi
lmon.com/live/67.high.stream/playlist.m3u8?id=035bca1a71b11fce016d28acd3dbea51cbc96ddfe5b9ed3f8fe3286df6a738d3644657a9ef0048b105a7e83b4da96b9221a7eab05727c4c69cbeabc4560e
8b48bbd0afa2214aa8bc665f417d3517269b347d5fcdf6dbb2bfbcb37a8137899934aa5ddf4b990b3a14e5064f13f2501cd60f6cd2cf7b42563e1a49c465cc5ed69dc969fb71a2106c1a4f6b259eebe36a25a732ae
492d96b6af)
[streamlinksrv][error] Got exception: Read timeout
['Traceback (most recent call last):', '  File "/usr/sbin/streamlinksrv", line 207, in Stream', '    shutil.copyfileobj(fd, http.wfile)', '  File "/usr/lib/python2.7/shut
il.py", line 49, in copyfileobj', '    buf = fsrc.read(length)', '  File "/usr/lib/python2.7/site-packages/streamlink/stream/segmented.py", line 207, in read', '    timeo
ut=self.timeout)', '  File "/usr/lib/python2.7/site-packages/streamlink/buffers.py", line 111, in read', '    raise IOError("Read timeout")', 'IOError: Read timeout']
[streamlinksrv][info] Stream ended
[streamlinksrv][info] Closing currently open stream...

Each stream stops sometime. But until the demolition they run excellently.

Thank you for your help and this ingenious program!

**Comment by bastimeyer** [comment]
You're getting a `403 Client Error: Forbidden for url` error, which usually means that an access token or so has expired. This might be a plugin issue, but since you're using a Streamlink wrapper script/application, it could also be a different issue. Please use Streamlink directly and provide proper debug logs.

**Comment by LustigesBassgebrumm** [comment]
Unfortunately, I do not know how to start Streamlink directly on the VU + Solo2 (Enigma2). That's why I tried it under Win 10. Here are the debug logs of 2 attempts. Error 403 also happens occasionally but the stream is not interrupted. The streams stop for another reason.

On Windows it's much better. I have written the following in the file config.filmon:

hls-segment-timeout=20.0
hls-playlist-reload-attempts=10
hls-timeout=80.0
loglevel=debug

However, this was not useful on the VU +.

[Logfile Filmon 2.txt](https://github.com/streamlink/streamlink/files/2329694/Logfile.Filmon.2.txt)

**Comment by Billy2011** [comment]
I've made a [Pull request #2037](https://github.com/streamlink/streamlink/pull/2037/files) for this issue and you could test on your VU if it works better with it. Your Filmon configuration should not be used, except for the `loglevel`.

**Comment by LustigesBassgebrumm** [comment]
Many thanks for your effort, Billy2011 ! I have described the file hls.py in the path \usr\lib\python2.7\site-packages\streamlink\stream\ with the contents of the pull request (attached file). I get this error:

   Welcome on your Vu+ !
root@vusolo2:~ /usr/sbin/streamlinksrv manualstart
Traceback (most recent call last):
  File "/usr/sbin/streamlinksrv", line 29, in <module>
    from streamlink.stream.ffmpegmux import MuxedStream
  File "/usr/lib/python2.7/site-packages/streamlink/stream/__init__.py", line 6, in <module>
    from streamlink.stream.hls import HLSStream
  File "/usr/lib/python2.7/site-packages/streamlink/stream/hls.py", line 489
    return streams
SyntaxError: 'return' outside function
root@vusolo2:~





[hls.py.txt](https://github.com/streamlink/streamlink/files/2332936/hls.py.txt)

**Comment by Billy2011** [comment]
In line 489, 8 spaces are missing at the beginning of the line :)
[hls.py.txt](https://github.com/streamlink/streamlink/files/2333164/hls.py.txt)

**Comment by LustigesBassgebrumm** [comment]
Oh, The Hateful Eight ...   Sorry

The first attempt (ITV 1) was already over after 2 minutes. But the second try (with ITV 2) has been going on for almost an hour. This looks very good. I will continue testing it and get back to you. Can take a while, because the streams are supposed to run for a long time. ;-)

1000 thanks

**Comment by LustigesBassgebrumm** [comment]
Okay, it works much better with these changes. Nevertheless, streams still often stop. The behavior is different. Some sometimes jump back about half a minute, but continue to play. 
[Logfile Filmon 4.txt](https://github.com/streamlink/streamlink/files/2343410/Logfile.Filmon.4.txt)

**Comment by Billy2011** [comment]
It's not possible to fix the remaining issues within Streamlink as they affect both the player and the Filmon servers. Playback via VLC or MPV is much more stable.

**Comment by LustigesBassgebrumm** [comment]
Yes, Thank you
