### ISSUE TITLE
Issue with Steam Broadcasting plugin

### ISSUE THREAD

**Issue by strich** [streamlink/streamlink#2039]
## Plugin Issue
- [x ] This is a plugin issue and I have read the contribution guidelines.

### Description
I downloaded and compiled `streamlink 0.14.2+92.gc7bef14b` as the Steam Broadcast plugin has an unpatched fixed issue (https://github.com/streamlink/streamlink/issues/1977).
Unfortunately I got the following errors in the output. VLC did not pop up, however with debug loglevel it looks like it is still downloading the segments?

### Reproduction steps / Explicit stream URLs to test

1. The log includes the params used. But just basic use of the plugin should hopefully cause it.

### Log output

```
PS C:\> streamlink https://steamcommunity.com/broadcast/watch/76561198856493976 best --loglevel debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.7.0
[cli][debug] Streamlink: 0.14.2+92.gc7bef14b
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.51.0)
[cli][info] Found matching plugin steam for URL https://steamcommunity.com/broadcast/watch/76561198856493976
[plugin.steam][debug] Getting broadcast stream: sessionid=3abfd7be119cfb41a7801fb1
[utils.l10n][debug] Language code: en_GB
[stream.dash][debug] Available languages for DASH audio streams: und (using: und)
[cli][info] Available streams: 360p (worst), 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (dash)
[stream.dash][debug] Opening DASH reader for: 1 (video/mp4)
[stream.dash][debug] Opening DASH reader for: 1 (audio/mp4)
[stream.dash_manifest][debug] Generating segment numbers for dynamic playlist (id=video)
[stream.dash_manifest][debug] Generating segment numbers for dynamic playlist (id=audio)
[stream.dash][debug] Download of segment: https://valve403.steamcontent.com/broadcast/1850833243818213947/segment/video/1/init/?broadcast_origin=br3-fra1.broadcast.steamcontent.com:80 complete
[cli][error] Try 1/1: Could not open stream <Stream()> (Could not open stream: cannot use FFMPEG)
[stream.ffmpegmux][debug] Closing ffmpeg thread
error: Could not open stream <Stream()>, tried 1 times, exiting
[stream.dash][debug] Download of segment: https://valve403.steamcontent.com/broadcast/1850833243818213947/segment/audio/1/init/?broadcast_origin=br3-fra1.broadcast.steamcontent.com:80 complete
Exception in thread Thread-DASHStreamWorker:
Traceback (most recent call last):
  File "C:\Users\name\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\name\appdata\local\programs\python\python37\lib\site-packages\streamlink-0.14.2+92.gc7bef14b-py3.7.egg\streamlink\stream\segmented.py", line 62, in run
    self.writer.put(segment)
  File "c:\users\name\appdata\local\programs\python\python37\lib\site-packages\streamlink-0.14.2+92.gc7bef14b-py3.7.egg\streamlink\stream\segmented.py", line 118, in put
    retries=self.retries)
  File "C:\Users\name\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 153, in submit
    raise RuntimeError('cannot schedule new futures after'
RuntimeError: cannot schedule new futures afterinterpreter shutdown

[stream.dash][debug] Waiting for segment:  (1.9s)
[stream.dash][debug] Download of segment: https://valve403.steamcontent.com/broadcast/1850833243818213947/segment/audio/1/4720/?broadcast_origin=br3-fra1.broadcast.steamcontent.com:80 complete
[stream.dash][debug] Waiting for segment:  (1.2s)
[stream.dash][debug] Download of segment: https://valve403.steamcontent.com/broadcast/1850833243818213947/segment/video/1/4720/?broadcast_origin=br3-fra1.broadcast.steamcontent.com:80 complete
Exception in thread Thread-DASHStreamWorker:
Traceback (most recent call last):
  File "C:\Users\name\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "c:\users\name\appdata\local\programs\python\python37\lib\site-packages\streamlink-0.14.2+92.gc7bef14b-py3.7.egg\streamlink\stream\segmented.py", line 62, in run
    self.writer.put(segment)
  File "c:\users\name\appdata\local\programs\python\python37\lib\site-packages\streamlink-0.14.2+92.gc7bef14b-py3.7.egg\streamlink\stream\segmented.py", line 118, in put
    retries=self.retries)
  File "C:\Users\name\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 153, in submit
    raise RuntimeError('cannot schedule new futures after'
RuntimeError: cannot schedule new futures afterinterpreter shutdown

[stream.dash][debug] Waiting for segment:  (2.0s)
[stream.dash][debug] Download of segment: https://valve403.steamcontent.com/broadcast/1850833243818213947/segment/audio/1/4721/?broadcast_origin=br3-fra1.broadcast.steamcontent.com:80 complete
[stream.dash][debug] Waiting for segment:  (0.7s)
[stream.dash][debug] Download of segment: https://valve403.steamcontent.com/broadcast/1850833243818213947/segment/video/1/4721/?broadcast_origin=br3-fra1.broadcast.steamcontent.com:80 complete
[stream.dash][debug] Waiting for segment:  (1.9s)
[stream.dash][debug] Download of segment: https://valve403.steamcontent.com/broadcast/1850833243818213947/segment/audio/1/4722/?broadcast_origin=br3-fra1.broadcast.steamcontent.com:80 complete
[stream.dash][debug] Waiting for segment:  (0.0s)
[stream.dash][debug] Download of segment: https://valve403.steamcontent.com/broadcast/1850833243818213947/segment/video/1/4722/?broadcast_origin=br3-fra1.broadcast.steamcontent.com:80 complete
[stream.dash][debug] Waiting for segment:  (1.6s)
[stream.dash][debug] Download of segment: https://valve403.steamcontent.com/broadcast/1850833243818213947/segment/audio/1/4723/?broadcast_origin=br3-fra1.broadcast.steamcontent.com:80 complete
[stream.dash][debug] Download of segment: https://valve403.steamcontent.com/broadcast/1850833243818213947/segment/video/1/4723/?broadcast_origin=br3-fra1.broadcast.steamcontent.com:80 complete
```

**Comment by bastimeyer** [comment]
> OS: Windows 10
> Streamlink: 0.14.2+92.gc7bef14b
> Could not open stream: cannot use FFMPEG

https://github.com/streamlink/streamlink/blob/master/src/streamlink/stream/ffmpegmux.py#L83

DASH streams require FFmpeg in order to mux both video and audio stream segments. If you've installed Streamlink on Windows without using the installer, you need to also download ffmpeg and point Streamlink towards it via the `--ffmpeg-ffmpeg path/to/ffmpeg.exe` parameter if it can't be found in one of the paths of your `PATH` system env var:
https://streamlink.github.io/cli.html#cmdoption-ffmpeg-ffmpeg

**Comment by strich** [comment]
Yep that was it. Cheers.
