### ISSUE TITLE
Streamlink broken after Windows 1803 Update

### ISSUE THREAD

**Issue by the-nothingman** [streamlink/streamlink#2064]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

After forced windows update to version 1803, streamlink seems to fail even after uninstall and reinstalling

### Expected / Actual behavior

expected behavior after install streamlink should work, however attempting to open a stream using cmd kicks an error.

### Reproduction steps / Explicit stream URLs to test

1. ...Install stable build 0.14.2
2. ...attempt to start any stream from cmd (this also fails with trying from streamlink portable builds)
3. ...stream fails with the error logged below

### Log output

```
C:\WINDOWS\system32>streamlink twitch.tv/twitchpresents 720p
[cli][info] Found matching plugin twitch for URL twitch.tv/twitchpresents
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p_alt, 720p (best)
[cli][info] Opening stream: 720p (hls)
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 982, in emit
  File "encodings\cp437.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u20ac' in position 31: character maps to <undefined>
Call stack:
  File "C:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 18, in <module>
    main()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 1002, in main
    handle_url()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 553, in handle_url
    handle_stream(plugin, streams, stream_name)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 403, in handle_stream
    success = output_stream(stream)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 278, in output_stream
    output = create_output()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 103, in create_output
    log.info("Starting player: {0}", args.player)
  File "logging\__init__.py", line 1279, in info
  File "logging\__init__.py", line 1415, in _log
  File "logging\__init__.py", line 1425, in handle
  File "logging\__init__.py", line 1487, in callHandlers
  File "logging\__init__.py", line 855, in handle
  File "logging\__init__.py", line 986, in emit
Message: 'Starting player: {0}'
Arguments: ('"â\u20acªC:\\Users\\xxxx\\OneDrive\\Desktop\\mpv\\mpv.exe" --cache 8192',)
[cli][info] Closing currently open stream...
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 281, in output_stream
    output.open()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\output.py", line 23, in open
    self._open()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\output.py", line 124, in _open
    self._open_subprocess()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\output.py", line 142, in _open_subprocess
    stderr=self.stderr)
  File "subprocess.py", line 947, in __init__
  File "subprocess.py", line 1224, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 18, in <module>
    main()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 1002, in main
    handle_url()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 553, in handle_url
    handle_stream(plugin, streams, stream_name)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 403, in handle_stream
    success = output_stream(stream)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 285, in output_stream
    args.player, err)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\console.py", line 94, in exit
    self.msg(u"{0}", msg)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\console.py", line 70, in msg
    self.output.write(formatted)
  File "encodings\cp437.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u20ac' in position 33: character maps to <undefined>

```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by the-nothingman** [comment]
Never mind found the issue myself, windows is/was inserting characters when copy/pasting that while normal to the eye cause problems in streamlink
