### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by fireattack** [streamlink/streamlink#2158]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

Can't run due to error: `ModuleNotFoundError: No module named 'Crypto'`

### Expected / Actual behavior

Play normally

### Reproduction steps / Explicit stream URLs to test

Try to play any stream from Twitch

### Log output

```
C:\Users\Administrator>streamlink twitch.tv/pgl_dota2en4 best
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\streamlink.exe\__main__.py", line 5, in <module>
  File "c:\python37\lib\site-packages\streamlink_cli\main.py", line 26, in <modu
le>
    from streamlink.stream import StreamProcess
  File "c:\python37\lib\site-packages\streamlink\stream\__init__.py", line 6, in
 <module>
    from streamlink.stream.hls import HLSStream
  File "c:\python37\lib\site-packages\streamlink\stream\hls.py", line 6, in <mod
ule>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

C:\Users\Administrator>streamlink twitch.tv/pgl_dota2en4 best --loglevel debug
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\streamlink.exe\__main__.py", line 5, in <module>
  File "c:\python37\lib\site-packages\streamlink_cli\main.py", line 26, in <modu
le>
    from streamlink.stream import StreamProcess
  File "c:\python37\lib\site-packages\streamlink\stream\__init__.py", line 6, in
 <module>
    from streamlink.stream.hls import HLSStream
  File "c:\python37\lib\site-packages\streamlink\stream\hls.py", line 6, in <mod
ule>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
```

**Comment by beardypig** [comment]
@fireattack in this case virtualenvs are your friend, not just for streamlink but for any Python project. I'm sure how easy they are to use on Windows, but there are many scripts to extend shells like bash, zsh, and fish with better virtualenv support.

**Comment by fireattack** [comment]
Thanks for the kind reminder!
