### ISSUE TITLE
ustream plugin error (AttributeError: 'MuxedHLSStream' object has no attribute 'url')

### ISSUE THREAD

**Issue by dbogatev** [streamlink/streamlink#2161]
## Issue

- [x ] I have read the contribution guidelines.

### Description

Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/streamlink_cli/main.py", line 1002, in main
    handle_url()
  File "/usr/local/lib/python2.7/dist-packages/streamlink_cli/main.py", line 533, in handle_url
    streams = fetch_streams(plugin)
  File "/usr/local/lib/python2.7/dist-packages/streamlink_cli/main.py", line 413, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/usr/local/lib/python2.7/dist-packages/streamlink/plugin/plugin.py", line 431, in get_streams
    return self.streams(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/streamlink/plugin/plugin.py", line 339, in streams
    ostreams = list(ostreams)
  File "/usr/local/lib/python2.7/dist-packages/streamlink/plugins/ustreamtv.py", line 261, in _get_streams
    for s in self._api_get_streams(media_id, application):
  File "/usr/local/lib/python2.7/dist-packages/streamlink/plugins/ustreamtv.py", line 187, in _api_get_streams
    for s in self._do_poll(media_id, application, cluster, referrer, retries):
  File "/usr/local/lib/python2.7/dist-packages/streamlink/plugins/ustreamtv.py", line 201, in _do_poll
    referrer, retries):
  File "/usr/local/lib/python2.7/dist-packages/streamlink/plugins/ustreamtv.py", line 218, in handle_module_info
    yield q, UStreamHLSStream(self.session, s.url, self.api)
AttributeError: 'MuxedHLSStream' object has no attribute 'url'

### Expected / Actual behavior

Playback should start

### Reproduction steps / Explicit stream URLs to test

1. Run streamlink http://www.ustream.tv/hipodromopanama?html5ui best -l debug
OR
Run streamlink http://www.ustream.tv/embed/1524?html5ui best -l debug

### Logs

```
streamlink http://www.ustream.tv/hipodromopanama best -l debug

[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-4.10.0-37-generic-x86_64-with-Ubuntu-16.04-xenial
[cli][debug] Python:     2.7.12
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.46.0)
[cli][info] Found matching plugin ustreamtv for URL http://www.ustream.tv/hipodromopanama
[plugin.ustreamtv][debug] Searching for media ID on the page
[plugin.ustreamtv][debug] Connecting to UStream API: media_id=23530652, application=channel, referrer=http://www.ustream.tv/hipodromopanama, cluster=live, app_id=11, app_ver=2
[plugin.ustream.apiclient][debug] Got new host=http://c742ec8f-lp-omega.ums.ustream.tv, and connectionId=q6l036l3hqdd2u16o7oa4vp0k2-20
[plugin.ustream.apiclient][debug] poll took 0.88s
[stream.hls][debug] Using external audio tracks for stream 356p (language=es, name=Spanish)
[stream.hls][debug] Using external audio tracks for stream 480p (language=es, name=Spanish)
[stream.hls][debug] Using external audio tracks for stream 248p (language=es, name=Spanish)
Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/streamlink_cli/main.py", line 1002, in main
    handle_url()
  File "/usr/local/lib/python2.7/dist-packages/streamlink_cli/main.py", line 533, in handle_url
    streams = fetch_streams(plugin)
  File "/usr/local/lib/python2.7/dist-packages/streamlink_cli/main.py", line 413, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/usr/local/lib/python2.7/dist-packages/streamlink/plugin/plugin.py", line 431, in get_streams
    return self.streams(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/streamlink/plugin/plugin.py", line 339, in streams
    ostreams = list(ostreams)
  File "/usr/local/lib/python2.7/dist-packages/streamlink/plugins/ustreamtv.py", line 261, in _get_streams
    for s in self._api_get_streams(media_id, application):
  File "/usr/local/lib/python2.7/dist-packages/streamlink/plugins/ustreamtv.py", line 187, in _api_get_streams
    for s in self._do_poll(media_id, application, cluster, referrer, retries):
  File "/usr/local/lib/python2.7/dist-packages/streamlink/plugins/ustreamtv.py", line 201, in _do_poll
    referrer, retries):
  File "/usr/local/lib/python2.7/dist-packages/streamlink/plugins/ustreamtv.py", line 218, in handle_module_info
    yield q, UStreamHLSStream(self.session, s.url, self.api)
AttributeError: 'MuxedHLSStream' object has no attribute 'url'
```

**Comment by bastimeyer** [comment]
Duplicate of #1767

> [cli][debug] Streamlink: 0.14.2

You need to use the latest development build:
https://streamlink.github.io/install.html

**Comment by gravyboat** [comment]
@bastimeyer We should probably do a new release, it's been a while...

**Comment by dbogatev** [comment]
Issue resolved after installed latest development build.
