### ISSUE TITLE
Missing 'futures' distribution on macOS Sierra

### ISSUE THREAD

**Issue by Zsub** [streamlink/streamlink#240]
On macOS sierra, when starting streamlink, it prints a trace and complains the 'futures' distribution can't be found, even though that should be installed:

```
$ streamlink http://www.ustream.tv/channel/iss-hdev-payload/pop-out
Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3081, in _call_aside
    f(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 959, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 846, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'futures' distribution was not found and is required by streamlink
```

And the futures package:

```
$ sudo -H pip install futures
Password:
Requirement already satisfied: futures in /private/var/root/Library/Python/2.7/lib/python/site-packages
```

**Comment by beardypig** [comment]
How did you install streamlink? I also use Sierra, but I have installed streamlink in to a virtualenv rather than in the system python path.

**Comment by Brainzyy** [comment]
I could be completely wrong here, but could it be because of python2? Maybe try to do sudo pip3 install streamlink and try that way.

**Comment by dehesselle** [comment]
No, it's not because of python2. I'm using Streamlink in a non-default (portable!) location without problems. One has to carefully take care of dependencies, though.

My guess is you haven't installed and/or setup your environment correctly and that's why the dependency cannot be found. Retrace your steps from the start: did you use `pip` to install Streamlink into a custom location? Are you setting `PYTHONPATH` correctly? Maybe it helps if you compare what you're doing with what I'm doing, check my installation in [build.sh](https://github.com/dehesselle/chatty/blob/macos/macos/build.sh) and invocation in [livestreamer.sh](https://github.com/dehesselle/chatty/blob/macos/macos/livestreamer.sh).

**Comment by gravyboat** [comment]
No updates in a while so I'm going to close this for now.
