### ISSUE TITLE
UnicodeDecodeError when opening streams with non-ascii characters in the title

### ISSUE THREAD

**Issue by 4AM-Campfire** [streamlink/streamlink#2444]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

When opening a stream with a non-ascii character in the stream title there is a “UnicodeDecodeError” and the stream doesn’t open.

The steam I tried to open had an ‘ö’ in the title, but trying other streams with non-ascii characters gave the same error (tested on random Korean streams). Other streams opened as expected.

### Expected / Actual behavior

Expect: Stream to open.
Actual: It doesn’t.

### Reproduction steps / Explicit stream URLs to test

1. Find a stream with a non-ascii title and attempt to open it.

### Log output

```
		OS: macOS 10.14.2
		Python: 2.7.14
		Streamlink: 1.1.1
		Requests(2.21.0), Socks(1.6.7), Websocket(0.47.0)
		Found matching plugin twitch for URL twitch.tv/quickybaby
		Plugin specific arguments:
		--twitch-oauth-token=******** (oauth_token)
		--twitch-disable-hosting=True (disable_hosting)
		--twitch-disable-ads=True (disable_ads)
		Getting live HLS streams for quickybaby
		Attempting to authenticate using OAuth token
		Successfully logged in as DELETE
		[utils.l10n][debug] Language code: en_US
		Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
		Opening stream: 1080p60 (hls)
		Starting player: /Applications/mpv.app/Contents/MacOS/mpv
		Traceback (most recent call last):
		File "/usr/local/bin/streamlink", line 11, in <module>
		load_entry_point('streamlink==1.1.1', 'console_scripts', 'streamlink')()
		File "/usr/local/lib/python2.7/site-packages/streamlink-1.1.1-py2.7.egg/streamlink_cli/main.py", line 1033, in main
		handle_url()
		File "/usr/local/lib/python2.7/site-packages/streamlink-1.1.1-py2.7.egg/streamlink_cli/main.py", line 594, in handle_url
		handle_stream(plugin, streams, stream_name)
		File "/usr/local/lib/python2.7/site-packages/streamlink-1.1.1-py2.7.egg/streamlink_cli/main.py", line 437, in handle_stream
		success = output_stream_passthrough(plugin, stream)
		File "/usr/local/lib/python2.7/site-packages/streamlink-1.1.1-py2.7.egg/streamlink_cli/main.py", line 262, in output_stream_passthrough
		output.open()
		File "/usr/local/lib/python2.7/site-packages/streamlink-1.1.1-py2.7.egg/streamlink_cli/output.py", line 24, in open
		self._open()
		File "/usr/local/lib/python2.7/site-packages/streamlink-1.1.1-py2.7.egg/streamlink_cli/output.py", line 219, in _open
		self._open_call()
		File "/usr/local/lib/python2.7/site-packages/streamlink-1.1.1-py2.7.egg/streamlink_cli/output.py", line 234, in _open_call
		log.debug(u"Calling: {0}".format(fargs))
		UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 141: ordinal not in range(128)
```

### Additional comments, screenshots, etc.
I can't link to a stream that will give an error as titles always change, but it should be easy enough to find a Korean stream, and they usually have Korean titles.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by DJ4ddi** [comment]
Hi there.
Noticed this bug on Elementary OS 0.4.1 (based on Ubuntu 16.04.2). It can easily be reproduced by using the title parameter, e.g.
`streamlink -t "★" ((any stream url)) best`

When using Streamlink Twitch GUI, go to Settings > Player > Window title and disable the custom title option as a temporary workaround.

Regards,
Addi

**Comment by back-to** [comment]
**can't reproduce** on ubuntu 18.10 / python2

---

easiest fix is to use **python3** instead of python2
