### ISSUE TITLE
BBC iplayer keyerror: goto

### ISSUE THREAD

**Issue by werid** [streamlink/streamlink#2607]
### Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

When trying to connect to bbc iplayer, live stream of bbc channel, it crashes with KeyError: 'goto'

### Reproduction steps / Explicit stream URLs to test

1. i updated streamlink to latest from github: pip-3.6 install --user git+https://github.com/streamlink/streamlink.git
2. i ran the following cmd: streamlink --loglevel debug --http-no-ssl-verify --bbciplayer-username "username" --bbciplayer-password password --player-external-http --player-external-http-port 3280 https://www.bbc.co.uk/iplayer/live/bbctwo best

### Log output

```
[cli][debug] OS:         FreeBSD-12.0-RELEASE-p3-amd64-64bit-ELF
[cli][debug] Python:     3.6.8
[cli][debug] Streamlink: 1.2.0+12.g1fb9391
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.50.0)
[cli][info] Found matching plugin bbciplayer for URL https://www.bbc.co.uk/iplayer/live/bbctwo
[cli][debug] Plugin specific arguments:
[cli][debug]  --bbciplayer-username=***@*** (username)
[cli][debug]  --bbciplayer-password=******** (password)
[plugin.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence
Traceback (most recent call last):
  File "/home/username/bin/streamlink", line 11, in <module>
    load_entry_point('streamlink==1.2.0+12.g1fb9391', 'console_scripts', 'streamlink')()
  File "/home/username/.local/lib/python3.6/site-packages/streamlink_cli/main.py", line 1038, in main
    handle_url()
  File "/home/username/.local/lib/python3.6/site-packages/streamlink_cli/main.py", line 578, in handle_url
    streams = fetch_streams(plugin)
  File "/home/username/.local/lib/python3.6/site-packages/streamlink_cli/main.py", line 458, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/home/username/.local/lib/python3.6/site-packages/streamlink/plugin/plugin.py", line 323, in streams
    ostreams = list(ostreams)
  File "/home/username/.local/lib/python3.6/site-packages/streamlink/plugins/bbciplayer.py", line 225, in _get_streams
    if not self.login(self.url):
  File "/home/username/.local/lib/python3.6/site-packages/streamlink/plugins/bbciplayer.py", line 199, in login
    http_nonce = self._extract_nonce(session_res)
  File "/home/username/.local/lib/python3.6/site-packages/streamlink/plugins/bbciplayer.py", line 112, in _extract_nonce
    final_url = urlparse(last_redirect_query['goto'])
KeyError: 'goto'

```

**Comment by busseyluke** [comment]
I get the same issue on a Windows 10 based system when trying to access BBC News. The issue started happening today. I updated Streamlink to the latest version but this did not change anything.

> [cli][info] Found matching plugin bbciplayer for URL www.bbc.co.uk/iplayer/live/bbcnews
> [plugin.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence
> Traceback (most recent call last):
>   File "runpy.py", line 193, in _run_module_as_main
>   File "runpy.py", line 85, in _run_code
>   File "C:\Program Files (x86)\Streamlink\bin\streamlink.exe\__main__.py", line 18, in <module>
>   File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 1038, in main
>     handle_url()
>   File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 578, in handle_url
>     streams = fetch_streams(plugin)
>   File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 458, in fetch_streams
>     sorting_excludes=args.stream_sorting_excludes)
>   File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 323, in streams
>     ostreams = list(ostreams)
>   File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\bbciplayer.py", line 228, in _get_streams
>     if not self.login(self.url):
>   File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\bbciplayer.py", line 202, in login
>     http_nonce = self._extract_nonce(session_res)
>   File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\bbciplayer.py", line 115, in _extract_nonce
>     final_url = urlparse(last_redirect_query['goto'])
> KeyError: 'goto'

>

**Comment by mkbloke** [comment]
Yup, same here too.  I also updated to the latest git release via pip.

# streamlink --config /home/mythtv-iptv-setup/conf/streamlinkrc -O bbc.co.uk/iplayer/live/bbcone 396p > /tmp/test.ts
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin bbciplayer for URL bbc.co.uk/iplayer/live/bbcone
[plugin.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence
Traceback (most recent call last):
  File "/home/mythtv-iptv-setup/utils/streamlink/bin/streamlink", line 10, in <module>
    sys.exit(main())
  File "/home/mythtv-iptv-setup/utils/streamlink/local/lib/python2.7/site-packages/streamlink_cli/main.py", line 1038, in main
    handle_url()
  File "/home/mythtv-iptv-setup/utils/streamlink/local/lib/python2.7/site-packages/streamlink_cli/main.py", line 578, in handle_url
    streams = fetch_streams(plugin)
  File "/home/mythtv-iptv-setup/utils/streamlink/local/lib/python2.7/site-packages/streamlink_cli/main.py", line 458, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/home/mythtv-iptv-setup/utils/streamlink/local/lib/python2.7/site-packages/streamlink/plugin/plugin.py", line 323, in streams
    ostreams = list(ostreams)
  File "/home/mythtv-iptv-setup/utils/streamlink/local/lib/python2.7/site-packages/streamlink/plugins/bbciplayer.py", line 225, in _get_streams
    if not self.login(self.url):
  File "/home/mythtv-iptv-setup/utils/streamlink/local/lib/python2.7/site-packages/streamlink/plugins/bbciplayer.py", line 199, in login
    http_nonce = self._extract_nonce(session_res)
  File "/home/mythtv-iptv-setup/utils/streamlink/local/lib/python2.7/site-packages/streamlink/plugins/bbciplayer.py", line 112, in _extract_nonce
    final_url = urlparse(last_redirect_query['goto'])
KeyError: 'goto'

**Comment by beardypig** [comment]
Appears to be an issue with the login flow.

**Comment by tmatthews5511** [comment]
streamlink -V
streamlink 1.2.0+12.g1fb9391
OS: Linux Mint 19.2

streamlink http://www.bbc.co.uk/iplayer/live/bbcone 540p --bbciplayer-username xxxxx --bbciplayer-password xxxxx

[cli][info] Found matching plugin bbciplayer for URL http://www.bbc.co.uk/iplayer/live/bbcone
[plugin.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence
Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 11, in <module>
    load_entry_point('streamlink==1.2.0+12.g1fb9391', 'console_scripts', 'streamlink')()
  File "/usr/local/lib/python2.7/dist-packages/streamlink-1.2.0+12.g1fb9391-py2.7.egg/streamlink_cli/main.py", line 1038, in main
    handle_url()
  File "/usr/local/lib/python2.7/dist-packages/streamlink-1.2.0+12.g1fb9391-py2.7.egg/streamlink_cli/main.py", line 578, in handle_url
    streams = fetch_streams(plugin)
  File "/usr/local/lib/python2.7/dist-packages/streamlink-1.2.0+12.g1fb9391-py2.7.egg/streamlink_cli/main.py", line 458, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/usr/local/lib/python2.7/dist-packages/streamlink-1.2.0+12.g1fb9391-py2.7.egg/streamlink/plugin/plugin.py", line 323, in streams
    ostreams = list(ostreams)
  File "/usr/local/lib/python2.7/dist-packages/streamlink-1.2.0+12.g1fb9391-py2.7.egg/streamlink/plugins/bbciplayer.py", line 225, in _get_streams
    if not self.login(self.url):
  File "/usr/local/lib/python2.7/dist-packages/streamlink-1.2.0+12.g1fb9391-py2.7.egg/streamlink/plugins/bbciplayer.py", line 199, in login
    http_nonce = self._extract_nonce(session_res)
  File "/usr/local/lib/python2.7/dist-packages/streamlink-1.2.0+12.g1fb9391-py2.7.egg/streamlink/plugins/bbciplayer.py", line 112, in _extract_nonce
    final_url = urlparse(last_redirect_query['goto'])
KeyError: 'goto'

**Comment by mkbloke** [comment]
The attached patch for bbciplayer.py seems to fix it.  I'm not suggesting it's the ideal solution, but it does work for me.

[bbciplayer.py.patch.txt](https://github.com/streamlink/streamlink/files/3563371/bbciplayer.py.patch.txt)

**Comment by tmatthews5511** [comment]
Thanks! The patch seems to have fix bbciplayer.py

**Comment by DaveyBoy1970** [comment]
My distro (UbuntuStusio 18.04 LTS) has Streamlink 1.1.1 which exhibits the same problem, starting last week. I tried the patch, but it doesn't seem to work for me.

streamlink www.bbc.co.uk/iplayer/live/bbcnews 540p --bbciplayer-username xxxxxxxx --bbciplayer-password xxxxxxxx

[cli][info] Found matching plugin bbciplayer for URL www.bbc.co.uk/iplayer/live/bbcnews
[plugin.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence
Traceback (most recent call last):
  File "/usr/bin/streamlink", line 11, in <module>
    load_entry_point('streamlink==1.1.1', 'console_scripts', 'streamlink')()
  File "/usr/share/streamlink/streamlink_cli/main.py", line 1033, in main
    handle_url()
  File "/usr/share/streamlink/streamlink_cli/main.py", line 577, in handle_url
    streams = fetch_streams(plugin)
  File "/usr/share/streamlink/streamlink_cli/main.py", line 457, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/usr/lib/python3/dist-packages/streamlink/plugin/plugin.py", line 323, in streams
    ostreams = list(ostreams)
  File "/usr/lib/python3/dist-packages/streamlink/plugins/bbciplayer.py", line 234, in _get_streams
    if not self.login(self.url):
  File "/usr/lib/python3/dist-packages/streamlink/plugins/bbciplayer.py", line 208, in login
    http_nonce = self._extract_nonce(session_res)
  File "/usr/lib/python3/dist-packages/streamlink/plugins/bbciplayer.py", line 116, in _extract_nonce
    final_url = urlparse(last_redirect_query['goto'])
KeyError: 'goto'

**Comment by tmatthews5511** [comment]
I would say uninstall your Streamlink 1.1.1, and then install the latest Streamlink 1.2.0, using git clone to get the 1.2.0 version, then using git pull to get the latest and greatest from time to time.

I hope the bbciplayer.py patch will be added a.s.a.p., since many could get dangerous withdrawal if they can't watch their BBC iPlayer. 

The patch worked for me, using Streamlink 1.2.0 (using git clone, then installing 'python setup.py install').

**Comment by busseyluke** [comment]
> The attached patch for bbciplayer.py seems to fix it. I'm not suggesting it's the ideal solution, but it does work for me.
> 
> [bbciplayer.py.patch.txt](https://github.com/streamlink/streamlink/files/3563371/bbciplayer.py.patch.txt)

Thanks for sharing!

Sorry if stupid question - how do I apply this patch in Windows?

**Comment by mkbloke** [comment]
> Sorry if stupid question - how do I apply this patch in Windows?

You could get a windows patch binary, from here for example:

http://gnuwin32.sourceforge.net/packages/patch.htm

It's probably just as quick to open bbciplayer.py in notepad and then manually change the _exrtract_nonce method to look like below:
```
    def _extract_nonce(cls, http_result):
        """
        Given an HTTP response from the sessino endpoint, extract the nonce, so we can "sign" requests with it.
        We don't really sign the requests in the traditional sense of a nonce, we just incude them in the auth requests.

        :param http_result: HTTP response from the bbc session endpoint.
        :type http_result: requests.Response
        :return: nonce to "sign" url requests with
        :rtype: string
        """

        # Extract the redirect URL from the last call
        last_redirect_url = http_result.history[-1].headers['Location']

        # Extract the nonce
        nonce = re.match(r'.*nonce=(.*?)&.*', last_redirect_url)

        # Return the nonce we can use for future queries
        return nonce.group(1)
```

**Comment by busseyluke** [comment]
Thanks for that! Unfortunately no dice so I think I will wait for next release to roll out.

`[cli][info] Found matching plugin bbciplayer for URL www.bbc.co.uk/iplayer/live/bbcnews
[plugin.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence
Traceback (most recent call last):
  File "runpy.py", line 193, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "C:\Program Files (x86)\Streamlink\bin\streamlink.exe\__main__.py", line 18, in <module>
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 1038, in main
    handle_url()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 578, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 458, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 323, in streams
    ostreams = list(ostreams)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\bbciplayer.py", line 248, in _get_streams
    tvip = self.find_tvip(self.url, master=True) + "_hd"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`
