### ISSUE TITLE
Can't authenticate Crunchyroll, CrunchyrollAPIError: Unauthenticated request

### ISSUE THREAD

**Issue by DanielJPiazza** [streamlink/streamlink#2785]
## Issue

- [ ] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

Version: Streamlink 1.3.1

Streamlink's Crunchyroll plugin is failing with a `CrunchyrollAPIError: Unauthenticated request` error.

### Expected / Actual behavior

The following command should authenticate with the valid Crunchyroll account, and then play the stream at the specified quality in the specified player.

```
streamlink --crunchyroll-username=<user> --crunchyroll-password=<pass> https://www.crunchyroll.com/somali-and-the-forest-spirit/episode-1-journeying-parent-and-child-792285 best --player "D:\Program Files\VideoLAN\VLC\vlc.exe"
```

What actually happens is the following error:

```
[cli][info] Found matching plugin crunchyroll for URL https://www.crunchyroll.com/somali-and-the-forest-spirit/episode-1-journeying-parent-and-child-792285
Traceback (most recent call last):
  File "runpy.py", line 193, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "D:\Program Files (x86)\Streamlink\bin\streamlink.exe\__main__.py", line 18, in <module>
  File "D:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 1038, in main
    handle_url()
  File "D:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 578, in handle_url
    streams = fetch_streams(plugin)
  File "D:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 458, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "D:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 317, in streams
    ostreams = self._get_streams()
  File "D:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 306, in _get_streams
    api = self._create_api()
  File "D:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 365, in _create_api
    api.start_session()
  File "D:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 197, in start_session
    self.session_id = self._api_call("start_session", params, schema=_session_schema)
  File "D:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 173, in _api_call
    raise CrunchyrollAPIError(err_msg, err_code)
streamlink.plugin.crunchyroll.CrunchyrollAPIError: Unauthenticated request
```

### Reproduction steps / Explicit stream URLs to test

Run the following command with a valid Crunchyroll account for user/pass:

```
streamlink --crunchyroll-username=<user> --crunchyroll-password=<pass> https://www.crunchyroll.com/somali-and-the-forest-spirit/episode-1-journeying-parent-and-child-792285 best --player "D:\Program Files\VideoLAN\VLC\vlc.exe"
```

### Logs

```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.3.1
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin crunchyroll for URL https://www.crunchyroll.com/somali-and-the-forest-spirit/episode-1-journeying-parent-and-child-792285
[cli][debug] Plugin specific arguments:
[cli][debug]  --crunchyroll-username=<user_removed> (username)
[cli][debug]  --crunchyroll-password=<pass_removed> (password)
[utils.l10n][debug] Language code: en_US
[plugin.crunchyroll][debug] Creating session with locale: en_US
Traceback (most recent call last):
  File "runpy.py", line 193, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "D:\Program Files (x86)\Streamlink\bin\streamlink.exe\__main__.py", line 18, in <module>
  File "D:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 1038, in main
    handle_url()
  File "D:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 578, in handle_url
    streams = fetch_streams(plugin)
  File "D:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 458, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "D:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 317, in streams
    ostreams = self._get_streams()
  File "D:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 306, in _get_streams
    api = self._create_api()
  File "D:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 365, in _create_api
    api.start_session()
  File "D:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 197, in start_session
    self.session_id = self._api_call("start_session", params, schema=_session_schema)
  File "D:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 173, in _api_call
    raise CrunchyrollAPIError(err_msg, err_code)
streamlink.plugin.crunchyroll.CrunchyrollAPIError: Unauthenticated request
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by mlindner** [comment]
I'm also getting the same error, in the same situation. Streamlink doesn't seem to be able to authenticate to Crunchyroll at the moment.

**Comment by asermax** [comment]
Having the same issue as well; it seems to work by using the `--crunchyroll-session-id` option with a session id generated on the website though.

**Comment by alzamer2** [comment]
it seem they changed access_token
try WveH9VkPLrXvuNm in place of Scwg9PRRZ19iVwD

**Comment by espilonnn** [comment]
Where can I replace "Scwg9PRRZ19iVwD" with"WveH9VkPLrXvuNm". I'm a noob at streamlink.

**Comment by alzamer2** [comment]
for those that was here to change
go to streamlink\plugins\crunchyroll.py
line 108
change 
`    _access_token = "Scwg9PRRZ19iVwD"`
with
`    _access_token = "WveH9VkPLrXvuNm"`

**Comment by locknet11** [comment]
@alzamer2 workaround works out of the box! Thanks :)

**Comment by DanielJPiazza** [comment]
Submitted pull request #2788 with updated Crunchyroll access token.

Thanks, @alzamer2 and @asermax!

**Comment by alzamer2** [comment]
You're welcome

**Comment by zekiz774** [comment]
How do I get the Crunchyroll access token?

**Comment by Tenpi** [comment]
@alzamer2 The access token "WveH9VkPLrXvuNm" is returning a 429. If you can tell me how you got this access token that would be great, preferably with a username + password so I can generate it uniquely for every user.
