### ISSUE TITLE
Stream crashing after a while

### ISSUE THREAD

**Issue by GilDev** [streamlink/streamlink#2848]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

After some time playing (sometimes a minute, sometimes 30), the remote stream is crashing, although it works fine on VLC desktop for example.

### Expected / Actual behavior

I would like for the stream to continue on, or even try to reconnect automatically if it crashes.
Right now it is crashing after some minutes, using VLC or OMXPlayer on Raspberry Pi 4.

### Reproduction steps / Explicit stream URLs to test

I’m using a Raspberry Pi (same behavior on a Raspberry Pi A (yes the first Raspberry Pi generation) and a Raspberry Pi 4). Tried over WiFi and Ethernet so the link doesn’t seem to be the problem.
1. Run `streamlink https://sarralbe.hdr-tv.com/live/sarralbe/sarralbe.stream/manifest_w1345660299.mpd best --player vlc --fifo` (`--fifo` doesn’t seem to change a thing)
2. Wait until it crashes.

### Log output

```
[cli][debug] OS:         Linux-4.19.97-v7l+-armv7l-with-debian-10.3
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 1.0.0
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.53.0)
[cli][info] Found matching plugin dash for URL https://sarralbe.hdr-tv.com/live/sarralbe/sarralbe.stream/manifest_w1345660299.mpd
[plugin.dash][debug] Parsing MPD URL: https://sarralbe.hdr-tv.com/live/sarralbe/sarralbe.stream/manifest_w1345660299.mpd
[utils.l10n][debug] Language code: en_GB
[stream.dash][debug] Available languages for DASH audio streams: NONE (using: n/a)
[cli][info] Available streams: 1600k (worst, best)
[cli][info] Opening stream: 1600k (dash)
[stream.dash][debug] Opening DASH reader for: p0va0br1585108 (video/mp4)
[cli][debug] Pre-buffering 8192 bytes
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=0))
[stream.dash][debug] Reloading manifest (p0va0br1585108:video/mp4)
[stream.dash][debug] Download of segment: https://sarralbe.hdr-tv.com/live/sarralbe/sarralbe.stream/chunk_ctvideo_cfm4s_ridp0va0br1585108_cinit_w1345660299_mpd.m4s complete
[cli][info] Creating pipe streamlinkpipe-1334
[cli][info] Starting player: vlc
[cli.output][debug] Opening subprocess: vlc --input-title-format https://sarralbe.hdr-tv.com/live/sarralbe/sarralbe.stream/manifest_w1345660299.mpd /tmp/streamlinkpipe-1334
[cli][debug] Writing stream to output
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=0))
[stream.dash][debug] Reloading manifest (p0va0br1585108:video/mp4)
[stream.dash][debug] Download of segment: https://sarralbe.hdr-tv.com/live/sarralbe/sarralbe.stream/chunk_ctvideo_cfm4s_ridp0va0br1585108_cs142671614574060_w1345660299_mpd.m4s complete
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=0))
[stream.dash][debug] Reloading manifest (p0va0br1585108:video/mp4)
[stream.dash][debug] Download of segment: https://sarralbe.hdr-tv.com/live/sarralbe/sarralbe.stream/chunk_ctvideo_cfm4s_ridp0va0br1585108_cs142671615473880_w1345660299_mpd.m4s complete
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=0))
[stream.dash][debug] Reloading manifest (p0va0br1585108:video/mp4)
[stream.dash][debug] Download of segment: https://sarralbe.hdr-tv.com/live/sarralbe/sarralbe.stream/chunk_ctvideo_cfm4s_ridp0va0br1585108_cs142671616373700_w1345660299_mpd.m4s complete
[stream.dash][debug] Download of segment: https://sarralbe.hdr-tv.com/live/sarralbe/sarralbe.stream/chunk_ctvideo_cfm4s_ridp0va0br1585108_cs142671617273520_w1345660299_mpd.m4s complete
[stream.dash][debug] Download of segment: https://sarralbe.hdr-tv.com/live/sarralbe/sarralbe.stream/chunk_ctvideo_cfm4s_ridp0va0br1585108_cs142671618173340_w1345660299_mpd.m4s complete
error: Error when reading from stream: Read timeout, exiting
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...
Exception in thread Thread-DASHStreamWorker:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/streamlink/plugin/api/http_session.py", line 164, in request
    *args, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/streamlink/stream/segmented.py", line 59, in run
    for segment in self.iter_segments():
  File "/usr/lib/python3/dist-packages/streamlink/stream/dash.py", line 97, in iter_segments
    if not self.reload():
  File "/usr/lib/python3/dist-packages/streamlink/stream/dash.py", line 111, in reload
    res = self.session.http.get(self.mpd.url, exception=StreamError)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/streamlink/plugin/api/http_session.py", line 175, in request
    raise err
streamlink.exceptions.StreamError: Unable to open URL: https://sarralbe.hdr-tv.com/live/sarralbe/sarralbe.stream/manifest_w1345660299.mpd (('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))
```

I get more log when not redirecting stdout to a file, here is the end:

```
streamlink.exceptions.StreamError: Unable to open URL: https://sarralbe.hdr-tv.com/live/sarralbe/sarralbe.stream/manifest_w1345660299.mpd (('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))

[stream.dash][debug] Download of segment: https://sarralbe.hdr-tv.com/live/sarralbe/sarralbe.stream/chunk_ctvideo_cfm4s_ridp0va0br1585108_cs142672281341130_w1345660299_mpd.m4s complete
[stream.dash][debug] Download of segment: https://sarralbe.hdr-tv.com/live/sarralbe/sarralbe.stream/chunk_ctvideo_cfm4s_ridp0va0br1585108_cs142672282240950_w1345660299_mpd.m4s complete
error: Error when reading from stream: Read timeout, exiting
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by back-to** [comment]
you can try this command

```
streamlink https://sarralbe.hdr-tv.com/live/sarralbe/sarralbe.stream/manifest.mpd --http-header "Host=sarralbe.hdr-tv.com" --http-header "Referer=https://sarralbe.hdr-tv.com/" --http-header "Origin=https://www.sarralbe.fr" --http-header "Connection=keep-alive"
```

but there are sometimes still some issues.

Not sure if there is much that Streamlink could do.

**Comment by GilDev** [comment]
Thanks, although that doesn’t seem to help…
Any idea on why this is not working? Do you know of another way I cloud try?

**Comment by back-to** [comment]
> Any idea on why this is not working?

`Remote end closed connection without response`
they are basically closing the connection,
_maybe the server wants some ping from Streamlink_ but I don't see it on there website
 
so not sure

> Do you know of another way I cloud try?

you could also try there HLS stream
`https://sarralbe.hdr-tv.com/live/sarralbe/sarralbe.stream/master.m3u8`

**Comment by GilDev** [comment]
I’m currently trying directly with VLC and it seems to be much more stable, despite a few `[afcb1a28] mp4 demux: Fragment sequence discontinuity detected 158534160 != 158534157` errors

**Comment by GilDev** [comment]
Well I’ve tried directly with VLC, using the CLI, and it seems to work quite nicely without any disconnection in 2-3 hours. Didn’t need Streamlink in the end apparently (fingers crossed it will continue like this though)…
Where did you find that HLS stream’s URL?

**Comment by back-to** [comment]
>  Where did you find that HLS stream’s URL?

compared URLs from the same streaming domain, tried to rewrite the dash URL and it worked.

https://github.com/search?q=hdr-tv.com&type=Code

> and it seems to work quite nicely without any disconnection in 2-3 hours. 

seems like the HLS stream works stable enough,
but there is not much we can do about the DASH stream right now.

closing

**Comment by GilDev** [comment]
Alright, thanks for you help!
I’m using the Dash stream with VLC though and like that it seems to work.

**Comment by bachoo786** [comment]
> Alright, thanks for you help!
> I’m using the Dash stream with VLC though and like that it seems to work.

Hey buddy do you mind sharing your working command line with vlc? I want to try it out please. Thanks

**Comment by GilDev** [comment]
I still had some trouble but maybe it was the link, I'm a bit tired about all this haha…
I just use `vlc "<stream URL>"`, or cvlc if I use it in a script (launched through a systemd service).

**Comment by bachoo786** [comment]
So `streamlink vlc "......" `

**Comment by GilDev** [comment]
No, no streamlink, that was the entire command in my previous comment.

**Comment by bachoo786** [comment]
Oh so are you not using streamlink?

**Comment by GilDev** [comment]
No that's what I wrote, streamlink command is on the first post but it works quite badly.

**Comment by johnthecracker** [comment]
<a href='https://postimg.cc/3khDkg07' target='_blank'><img src='https://i.postimg.cc/3khDkg07/Screen-Shot.jpg' border='0' alt='Screen-Shot'/></a>

**Comment by bachoo786** [comment]
???

**Comment by johnthecracker** [comment]
click on the picture to get it magnified and see what I did.

vlc https://sarralbe.hdr-tv.com/live/sarralbe/sarralbe.stream/manifest.mpd

a puzzling newbie with 100's of posts on github from 2013..

**Comment by bachoo786** [comment]
Puzzling newbie? Lol are we solving puzzles by clicking on the picture and finding answers. 

Thanks anyway fella

**Comment by GilDev** [comment]
@bachoo786 Have you managed to make it work?

**Comment by bachoo786** [comment]
nope didnt work

**Comment by johnthecracker** [comment]
I enjoy watching those birds in a nest.

About dash stream, url I posted earlier plays with vlc, mpv and ffplay. 

It doesn't play with streamlink without tweaking, as back-to had said.


ffplay https://sarralbe.hdr-tv.com/live/sarralbe/sarralbe.stream/manifest.mpd


```
Input #0, dash, from 'https://sarralbe.hdr-tv.com/live/sarralbe/sarralbe.stream/manifest.mpd':
  Metadata:
    Title           : sarralbe.stream
  Duration: N/A, start: -691346359.493078, bitrate: N/A
  Program 0
    Stream #0:0: Video: h264 (Main) (avc1 / 0x31637661), yuvj420p(pc, bt709), 1280x960 [SAR 1:1 DAR 4:3], 25 tbr, 90k tbn, 40 tbc
    Metadata:
      variant_bitrate : 1585108
      id              : p0va0br1585108
[swscaler @ 000001baef11a000] deprecated pixel format used, make sure you did set range correctly
-691346159.29 M-V: -0.021 fd=   4 aq=    0KB vq=   83KB sq=    0B f=0/0
```

**Comment by GilDev** [comment]
@bachoo786 What didn’t work? The command is pretty simple I thinks.

@johnthecracker Yeah I enjoy that too, that’s why I’m trying to do an always-on monitor with my good old HDMIPi. 😊 Problem is that it’s still not that stable (Raspberry Pi 1A, Ethernet over PLC with USB adapter on Pi), not sure if it’s my local link quality because of PLC or the stream… My WiFi dongles don’t reach that far even the one I have with an external antenna. Raspberry Pi 4’s WiFi seems to work though (but I’d like to use my Model A).

**Comment by johnthecracker** [comment]
URL has changed a bit:

https://www.sarralbe.fr/Webcam.html

https://sarralbe.live-kd.com/live/sarralbe/sarralbe.stream/manifest.mpd

Works with ffplay, mpv, vlc and latest streamlink:

```
[cli][info] Found matching plugin dash for URL https://sarralbe.live-kd.com/live/sarralbe/sarralbe.stream/manifest.mpd
[cli][info] Available streams: 1000k (worst, best)
[cli][info] Opening stream: 1000k (dash)
[cli][info] Starting player: mpv.exe
```

**Comment by GilDev** [comment]
Thanks for the update, I’m gonna play with that a bit, though with streamlink (freshed install through apt with fresh installed Raspberry Pi OS) it just closes without showing anything on screen:

```
pi@cigognes:~ $ streamlink https://sarralbe.live-kd.com/live/sarralbe/sarralbe.stream/manifest.mpd best --player vlc --fifo
[cli][info] Found matching plugin dash for URL https://sarralbe.live-kd.com/live/sarralbe/sarralbe.stream/manifest.mpd
[cli][info] Available streams: 1000k (worst, best)
[cli][info] Opening stream: 1000k (dash)
[cli][info] Creating pipe streamlinkpipe-1193
[cli][info] Starting player: vlc
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
Traceback (most recent call last):
  File "/usr/bin/streamlink", line 11, in <module>
    load_entry_point('streamlink==1.0.0', 'console_scripts', 'streamlink')()
  File "/usr/share/streamlink/streamlink_cli/main.py", line 1029, in main
    handle_url()
  File "/usr/share/streamlink/streamlink_cli/main.py", line 593, in handle_url
    handle_stream(plugin, streams, stream_name)
  File "/usr/share/streamlink/streamlink_cli/main.py", line 446, in handle_stream
    success = output_stream(plugin, stream)
  File "/usr/share/streamlink/streamlink_cli/main.py", line 330, in output_stream
    read_stream(stream_fd, output, prebuffer)
  File "/usr/lib/python3.7/contextlib.py", line 298, in __exit__
    self.thing.close()
  File "/usr/share/streamlink/streamlink_cli/output.py", line 29, in close
    self._close()
  File "/usr/share/streamlink/streamlink_cli/output.py", line 256, in _close
    self.namedpipe.close()
  File "/usr/lib/python3/dist-packages/streamlink/utils/named_pipe.py", line 72, in close
    self.fifo.close()
BrokenPipeError: [Errno 32] Broken pipe
pi@cigognes:~ $ streamlink https://sarralbe.live-kd.com/live/sarralbe/sarralbe.stream/manifest.mpd best --player vlc
[cli][info] Found matching plugin dash for URL https://sarralbe.live-kd.com/live/sarralbe/sarralbe.stream/manifest.mpd
[cli][info] Available streams: 1000k (worst, best)
[cli][info] Opening stream: 1000k (dash)
[cli][info] Starting player: vlc
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
pi@cigognes:~ 
```

**Comment by johnthecracker** [comment]
This is in ubuntu and windows now:

j@j:~$ streamlink -V
streamlink 1.4.1+32.gb4863da

```
j@j:~$ streamlink https://sarralbe.live-kd.com/live/sarralbe/sarralbe.stream/manifest.mpd best
[cli][info] Found matching plugin dash for URL https://sarralbe.live-kd.com/live/sarralbe/sarralbe.stream/manifest.mpd
[cli][info] Available streams: 1000k (worst, best)
[cli][info] Opening stream: 1000k (dash)
[cli][info] Starting player: /usr/bin/vlc
```

C:\>streamlink -V
streamlink 1.5.0+1.g2c1ac27

```
C:\>streamlink https://sarralbe.live-kd.com/live/sarralbe/sarralbe.stream/manifest.mpd best
[cli][info] Found matching plugin dash for URL https://sarralbe.live-kd.com/live/sarralbe/sarralbe.stream/manifest.mpd
[cli][info] Available streams: 1000k (worst, best)
[cli][info] Opening stream: 1000k (dash)
[cli][info] Starting player: C:\P\VLC\vlc.exe
```

**Comment by GilDev** [comment]
I’m using cvlc directly for the moment, it’s still not 100 % stable, here is what I get sometimes:
```
Jul 20 20:57:25 cigognes sh[19976]: [aeb80900] main tls client error: cannot resolve sarralbe.live-kd.com port 443: Temporary failure in name resolution
Jul 20 20:57:25 cigognes sh[19976]: [ae911a08] access stream error: HTTP connection failure
Jul 20 20:57:25 cigognes sh[19976]: [006848a8] main demux error: no suitable access module for `https://sarralbe.live-kd.com:443/live/sarralbe/sarralbe.stream/manifest.mpd'
```

Here’s my script, but even if it is in an infinite loop it sometimes hang up, the stream image stays static…

```bash
while true
do
        cvlc "https://sarralbe.live-kd.com/live/sarralbe/sarralbe.stream/manifest.mpd" --http-reconnect
        sleep 5
done
```

**Comment by johnthecracker** [comment]
I don't run streamlink here eather, although I could.
I tried your cvlc for the sake of test and it works, I just don't see
why would cvlc be my choice before anything else.
My script is below cvlc output and it works fine for now.
If you think birds do much between 5 and 60 sec. you can change my 60 to 5.

```
j@j:~$ cvlc "https://sarralbe.live-kd.com/live/sarralbe/sarralbe.stream/manifest.mpd" 
VLC media player 3.0.9.2 Vetinari (revision 3.0.9.2-0-gd4c1aefe4d)
[000055a2f9899820] dummy interface: using the dummy interface module...
[00007f31182fb6b0] mp4 demux: Fragment sequence discontinuity detected 159535160 != 0
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
[00007f31080033b0] glconv_vaapi_x11 gl error: vaDeriveImage: operation failed
[00007f3130077c60] main video output error: video output creation failed
[00007f312c317080] main decoder error: failed to create video output
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
[00007f312c317080] avcodec decoder: Using G3DVL VDPAU Driver Shared Library version 1.0 for hardware decoding
[00007f3138000c80] main input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 1000 ms)
```

```
#!/bin/bash
printf "\e]2;~sarralbe\a"
while :; do
	d=$(date +%Y-%m-%d_%H-%M-%S)
	file="SARRALBE_${d}.ts"	
	ffmpeg -loglevel error -stats -headers \
	"User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0" \
	-i "https://sarralbe.live-kd.com/live/sarralbe/sarralbe.stream/manifest.mpd" \
	-codec copy $file
	sleep 60
done
```

**Comment by GilDev** [comment]
Thanks, my script worked for 6 days straight and then started glitching, it may be because the WiFi link is a bit weak sometimes because of the WiFi USB dongle, but I would have guessed it would restart if it failed or crash…
Why wouldn't cvlc be your choice then? Streamlink is just a wrapper when used with cvlc, and it won't work for me…
Also yeah I want real-time video as birds are sometimes quite active and it's fun to see them eat for example.
