### ISSUE TITLE
error get recordings

### ISSUE THREAD

**Issue by matthiasschulenburg** [streamlink/streamlink#2885]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

since 2 days downloading zattoo recordings runs in an error. See logfile attached

### Reproduction steps / Explicit stream URLs to test
see logfile

1. download a recorded stream
2. watch cli output

### Log output

```
Streamlink.exe --output 20200406a_TuC.mp4 --zattoo-email xxx@gmx.net --zattoo-password xxx https://zattoo.com/recordings?recording=236063781 best
[cli][info] Found matching plugin zattoo for URL https://zattoo.com/recordings?recording=236063781
Traceback (most recent call last):
  File "runpy.py", line 193, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "C:\Users\msg\AppData\Local\Streamlink\bin\Streamlink.exe\__main__.py", line 18, in <module>
  File "C:\Users\msg\AppData\Local\Streamlink\pkgs\streamlink_cli\main.py", line 1038, in main
    handle_url()
  File "C:\Users\msg\AppData\Local\Streamlink\pkgs\streamlink_cli\main.py", line 578, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Users\msg\AppData\Local\Streamlink\pkgs\streamlink_cli\main.py", line 458, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "C:\Users\msg\AppData\Local\Streamlink\pkgs\streamlink\plugin\plugin.py", line 317, in streams
    ostreams = self._get_streams()
  File "C:\Users\msg\AppData\Local\Streamlink\pkgs\streamlink\plugins\zattoo.py", line 339, in _get_streams
    self._hello()
  File "C:\Users\msg\AppData\Local\Streamlink\pkgs\streamlink\plugins\zattoo.py", line 161, in _hello
    app_token = match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

c:\Daten\Streamlink>
```

### Additional comments, screenshots, etc.
can do a test on fix

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by matthiasschulenburg** [comment]
tested branch version, works fine
thanks a lot
Matthias
