### ISSUE TITLE
Film on fails channel id not found

### ISSUE THREAD

**Issue by jamiejacksoncumbria** [streamlink/streamlink#2948]
## Plugin Issue

- [ ] This is a plugin issue and I have read the contribution guidelines.

### Description

<Since version 1.4.1 filmon does not work. Found channel ID: None>

### Reproduction steps / Explicit stream URLs to test

```
/usr/local/bin/streamlink http://www.filmon.com/channel/cbs-action high --player-external-http --player-external-http-port 23530 --player-continuous-http -l debug
```

### Log output
```
/usr/local/lib/python2.7/dist-packages/streamlink_cli/main.py:760: PythonDeprecatedWarning: Python 2.7 has reached the end of its life.  A future version of streamlink will drop support for Python 2.7. Please upgrade your Python to at least 3.5.
  streamlink = Streamlink({"user-input-requester": ConsoleUserInputRequester(console)})
[cli][debug] OS:         Linux-4.15.0-99-generic-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     2.7.17
[cli][debug] Streamlink: 1.4.1
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin filmon for URL http://www.filmon.com/channel/cbs-action
[plugin.filmon][debug] Found channel ID: None
[plugin.filmon][debug] channel sleep 0
[plugin.filmon][debug] channel sleep 1
[plugin.filmon][debug] channel sleep 2
[plugin.filmon][debug] channel sleep 3
[plugin.filmon][debug] channel sleep 4
[plugin.filmon][debug] Reset cached channel: cbs-action
Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/streamlink_cli/main.py", line 1024, in main
    handle_url()
  File "/usr/local/lib/python2.7/dist-packages/streamlink_cli/main.py", line 585, in handle_url
    streams = fetch_streams(plugin)
  File "/usr/local/lib/python2.7/dist-packages/streamlink_cli/main.py", line 465, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/usr/local/lib/python2.7/dist-packages/streamlink/plugin/plugin.py", line 323, in streams
    ostreams = list(ostreams)
  File "/usr/local/lib/python2.7/dist-packages/streamlink/plugins/filmon.py", line 245, in _get_streams
    data = self.api.channel(_id)
  File "/usr/local/lib/python2.7/dist-packages/streamlink/plugins/filmon.py", line 161, in channel
    return self.session.http.json(res, schema=self.api_schema)
UnboundLocalError: local variable 'res' referenced before assignment
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
Looks like the filmon page has changed a bit, we'll need to update/rewrite the plugin.

**Comment by jamiejacksoncumbria** [comment]
Works on version 1.3.1 still

**Comment by mkbloke** [comment]
I tried the OP's URL and got the same error.  Substituted ```/channel/``` for ```/tv/``` in the OP's URL and it worked.  Went back to the OP's original URL and it is working consistently on repeated tests now.  Strange... perhaps it's a site update being rolled out that's still in progress.

**Comment by bastimeyer** [comment]
> perhaps it's a site update being rolled out that's still in progress.

Nope, it's just a bug in the implementation that added retries on 500 server responses:
061fb013acc232ab569d1f9d83e668882ee66b36 (#2796)
> UnboundLocalError: local variable 'res' referenced before assignment

**Comment by beardypig** [comment]
@bastimeyer that is a bug too. But, it still doesn't work for me :)

**Comment by jamiejacksoncumbria** [comment]
If you change /channel/channelname to /tv/channelname it works for me now.
