### ISSUE TITLE
Incompatibility with pycountry 20.7.3

### ISSUE THREAD

**Issue by farid-fari** [streamlink/streamlink#3058]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

If you upgrade `pycountry` to its latest version from yesterday (20.7.3), then you get the following behaviour when opening a stream:

    Traceback (most recent call last):
      File "/usr/bin/streamlink", line 11, in <module>
        load_entry_point('streamlink==1.4.1', 'console_scripts', 'streamlink')()
      File "/usr/lib/python3.8/site-packages/streamlink_cli/main.py", line 1024, in main
        handle_url()
      File "/usr/lib/python3.8/site-packages/streamlink_cli/main.py", line 585, in handle_url
        streams = fetch_streams(plugin)
      File "/usr/lib/python3.8/site-packages/streamlink_cli/main.py", line 464, in fetch_streams
        return plugin.streams(stream_types=args.stream_types,
      File "/usr/lib/python3.8/site-packages/streamlink/plugin/plugin.py", line 317, in streams
        ostreams = self._get_streams()
      File "/usr/lib/python3.8/site-packages/streamlink/plugins/twitch.py", line 794, in _get_streams
        return self._get_hls_streams("live")
      File "/usr/lib/python3.8/site-packages/streamlink/plugins/twitch.py", line 733, in _get_hls_streams
        streams = TwitchHLSStream.parse_variant_playlist(
      File "/usr/lib/python3.8/site-packages/streamlink/stream/hls.py", line 405, in parse_variant_playlist
        locale = session_.localization
      File "/usr/lib/python3.8/site-packages/streamlink/session.py", line 514, in localization
        return Localization(self.get_option("locale"))
      File "/usr/lib/python3.8/site-packages/streamlink/utils/l10n.py", line 122, in __init__
        self.language_code = language_code
      File "/usr/lib/python3.8/site-packages/streamlink/utils/l10n.py", line 147, in language_code
        self.language, self.country = self._parse_locale_code(language_code)
      File "/usr/lib/python3.8/site-packages/streamlink/utils/l10n.py", line 132, in _parse_locale_code
        return self.get_language(parts[0]), self.get_country(parts[1])
      File "/usr/lib/python3.8/site-packages/streamlink/utils/l10n.py", line 176, in get_language
        return Language.get(language)
      File "/usr/lib/python3.8/site-packages/streamlink/utils/l10n.py", line 76, in get
        return Language(lang.alpha_2, lang.alpha_3, lang.name, getattr(lang, "bibliographic", None))
      File "/usr/lib/python3.8/site-packages/pycountry/db.py", line 19, in __getattr__
        raise AttributeError
    AttributeError

This is probably due to a change in the API from `pycountry`.

### Expected / Actual behavior

No errors.

### Reproduction steps / Explicit stream URLs to test

1. Just run any stream with the latest version of everything.

### Log output

Before the error output from above:

```
[cli][debug] OS:         Linux-5.7.7-arch1-1-x86_64-with-glibc2.2.5
[cli][debug] Python:     3.8.3
[cli][debug] Streamlink: 1.4.1
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/lanf3ust
[plugin.twitch][debug] Getting live HLS streams for lanf3ust
```

**Comment by bastimeyer** [comment]
#3057
