### ISSUE TITLE
Nicolive plugin error

### ISSUE THREAD

**Issue by rckvnka** [streamlink/streamlink#3060]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description
The plugin failed to extract broadcast id. I tried with the livestreams and the timeshifts (VOD), both not work.

### Reproduction steps / Explicit stream URLs to test

1. I opened live.nicovideo.jp tried with any video live without login need
2. Copy paste the link to the command line (live2.nicovideo.jp/watch/lv326815335)
3. Failed to extract broadcast id

### Log output

```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.4.1
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin nicolive for URL live2.nicovideo.jp/watch/lv326815335
[plugin.nicolive][warning] Failed to extract broadcast id
Traceback (most recent call last):
  File "runpy.py", line 193, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "C:\Program Files (x86)\Streamlink\bin\streamlink.exe\__main__.py", line 18, in <module>
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 1024, in main
    handle_url()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 585, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 465, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 317, in streams
    ostreams = self._get_streams()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\nicolive.py", line 67, in _get_streams
    if not self.get_wss_api_url():
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\nicolive.py", line 124, in get_wss_api_url
    _log.debug("Got broadcast_id: {0}".format(self.broadcast_id))
AttributeError: 'NicoLive' object has no attribute 'broadcast_id'
```

### Additional comments, screenshots, etc.
I wanna say thank you in advance.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/pull/3039

**Comment by rckvnka** [comment]
I'm so sorry, I've tried many times but it still doesn't work for me. What did I do wrong?
*new to github and everything, sorry

[nicolive.zip](https://github.com/streamlink/streamlink/files/4874768/nicolive.zip)

**Comment by tnira** [comment]
https://github.com/streamlink/streamlink/issues/3028#issuecomment-650892270
