### ISSUE TITLE
'Read timed out' appears to not be handled properly as of 0.2.0

### ISSUE THREAD

**Issue by CyberBotX** [streamlink/streamlink#332]
I use streamlink under FreeBSD (I've made a port for it and submitted it, but I need to update it for the latest version) to watch streams on Twitch. With 0.1.0 and earlier, whenever a read timeout seemed to occur, I'd get a message such as this:

`[stream.hls][error] Failed to open segment 4370: Unable to open URL: https://video-edge-835ef0.ord02.hls.ttvnw.net/transcode-x2-835b70/sinister1_24051668848_571899805/chunked/index-0000004371-tN3E.ts (HTTPSConnectionPool(host='video-edge-835ef0.ord02.hls.ttvnw.net', port=443): Read timed out.)`

With 0.2.0, though, I instead see an exception occurring, like so:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 232, in _error_catcher
    yield
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 314, in read
    data = self._fp.read(amt)
  File "/usr/local/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/usr/local/lib/python3.5/http/client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/local/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 676, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 324, in read
    flush_decoder = True
  File "/usr/local/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 237, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='video-edge-835ef0.ord02.hls.ttvnw.net', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/site-packages/streamlink/stream/segmented.py", line 160, in run
    self.write(segment, result)
  File "/usr/local/lib/python3.5/site-packages/streamlink/stream/hls.py", line 111, in write
    for chunk in res.iter_content(chunk_size):
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 683, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='video-edge-835ef0.ord02.hls.ttvnw.net', port=443): Read timed out.
```

This was happening regardless of python 2.7 or python 3.5 being used.

The following is in my $HOME/.streamlinkrc file:

```
player-continuous-http
default-stream=best
hls-segment-threads=10
```

(Also my twitch-oauth-token that I am not going to include here.)

**Comment by zp** [comment]
Yea this happens to me as well under Windows (also tested on Alpine Linux, same thing), happens very frequently on HLS streams for me after beb3f08 (crappy ISP), the stream eventually dies and doesn't properly reconnect when the exception occurs.

HLS streams prior to beb3f08 will reconnect normally after internet hiccups.

Also happens on a "Connection Reset Error"

````
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\zp\Downloads\streamlink-test\latest\Streamlink\requests\packages\urllib3\response.py", line 232, in _error_catcher
    yield
  File "C:\Users\zp\Downloads\streamlink-test\latest\Streamlink\requests\packages\urllib3\response.py", line 314, in read
    data = self._fp.read(amt)
  File "http\client.py", line 448, in read
  File "http\client.py", line 488, in readinto
  File "socket.py", line 575, in readinto
  File "ssl.py", line 929, in recv_into
  File "ssl.py", line 791, in read
  File "ssl.py", line 575, in read
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zp\Downloads\streamlink-test\latest\Streamlink\requests\models.py", line 676, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\zp\Downloads\streamlink-test\latest\Streamlink\requests\packages\urllib3\response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\zp\Downloads\streamlink-test\latest\Streamlink\requests\packages\urllib3\response.py", line 324, in read
    flush_decoder = True
  File "contextlib.py", line 77, in __exit__
  File "C:\Users\zp\Downloads\streamlink-test\latest\Streamlink\requests\packages\urllib3\response.py", line 250, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connec
tion was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection w
as forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "C:\Users\zp\Downloads\streamlink-test\latest\Streamlink\streamlink\stream\segmented.py", line 160, in run
    self.write(segment, result)
  File "C:\Users\zp\Downloads\streamlink-test\latest\Streamlink\streamlink\stream\hls.py", line 111, in write
    for chunk in res.iter_content(chunk_size):
  File "C:\Users\zp\Downloads\streamlink-test\latest\Streamlink\requests\models.py", line 679, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was f
orcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibl
y closed by the remote host', None, 10054, None))
````

**Comment by beardypig** [comment]
Good points. That's an oversight on my part, I'll get a patch together for proper retry and resume support in the next week or so. It's relatively straightforward to do :-)

**Comment by gravyboat** [comment]
@beardypig Once we get a few things fixed I think we should do a new `0.2.1` (or 0.3.0) release. There are some things that have been fixed and the upgrade issue for users who already had `0.2.0` installed seems to be causing some one off issues.

**Comment by beardypig** [comment]
Sounds good to me. I've been working on this issue, I just need to work out a good way to test it. Hopefully I'll submit a PR tomorrow :-)

**Comment by gravyboat** [comment]
No worries, this was a relevant issue that wasn't going to be closed for a bit so I wanted to make the note here.

**Comment by gravyboat** [comment]
Closing since the fix is merged.

**Comment by CyberBotX** [comment]
It appears that this has regressed in 0.3.1, I get the exceptions again instead of the simple error.
