### ISSUE TITLE
StreamLink in CentOS 7 with pip Error

### ISSUE THREAD

**Issue by h-o-sein** [streamlink/streamlink#3453]
CentOS 7
Python 2.7.5
`
[root@server ~]# streamlink
Traceback (most recent call last):
  File "/usr/bin/streamlink", line 9, in <module>
    load_entry_point('streamlink==2.0.0', 'console_scripts', 'streamlink')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/streamlink_cli/main.py", line 222
    log.error(f"Unable to fetch new streams: {err}")
                                                  ^
SyntaxError: invalid syntax
`

**Comment by bastimeyer** [comment]
> Python 2.7.5
> streamlink==2.0.0

https://streamlink.github.io/changelog.html#streamlink-2-0-0-2020-12-22

> BREAKING: dropped support for Python 2 and Python 3.5 (#3232, #3269)

**Comment by h-o-sein** [comment]
> > Python 2.7.5
> > streamlink==2.0.0
> 
> https://streamlink.github.io/changelog.html#streamlink-2-0-0-2020-12-22
> 
> > BREAKING: dropped support for Python 2 and Python 3.5 (#3232, #3269)

```
[root@server ~]# pip -V
pip 20.3.3 from /usr/lib/python2.7/site-packages/pip (python 2.7)
```

```
[root@server ~]# python 
Python 2.7.5 (default, Nov 16 2020, 22:23:17) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```


```
[root@server ~]# streamlink
Traceback (most recent call last):
  File "/usr/bin/streamlink", line 9, in <module>
    load_entry_point('streamlink==2.0.0', 'console_scripts', 'streamlink')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/streamlink_cli/main.py", line 222
    log.error(f"Unable to fetch new streams: {err}")
                                                  ^
SyntaxError: invalid syntax
```

**Comment by bastimeyer** [comment]
You are using Python 2.7. As I've already shown you, **Python 2 support has been dropped in the Streamlink 2.0.0 release.** The new min Python version requirement is Python 3.6.

**Comment by h-o-sein** [comment]
oh ok ty

> You are using Python 2.7. As I've already shown you, **Python 2 support has been dropped in the Streamlink 2.0.0 release.** The new min Python version requirement is Python 3.6.
