### ISSUE TITLE
Help fixing 3rd party plugin

### ISSUE THREAD

**Issue by MannixMD** [streamlink/streamlink#3460]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Since the last update (2.0.0) the [plugin](https://github.com/oggy1989/streamlink-plugins/blob/master/tvnplayer.py) I was using to watch videos from player.pl stopped working. Now when i try to watch anything I'm getting this error
```
[session][error] Failed to load plugin tvnplayer from C:\Users\Mats\AppData\Loca
l\Streamlink\pkgs\streamlink\plugins
Traceback (most recent call last):
  File "C:\Users\Mats\AppData\Local\Streamlink\pkgs\streamlink\session.py", line
 423, in load_plugins
    mod = load_module(module_name, path)
  File "C:\Users\Mats\AppData\Local\Streamlink\pkgs\streamlink\utils\__init__.py
", line 25, in load_module
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Mats\AppData\Local\Streamlink\pkgs\streamlink\plugins\tvnplayer
.py", line 12, in <module>
    from streamlink.plugin.api import http, validate
ImportError: cannot import name 'http' from 'streamlink.plugin.api' (C:\Users\Ma
ts\AppData\Local\Streamlink\pkgs\streamlink\plugin\api\__init__.py)
error: No plugin can handle URL: https://player.pl/programy-online/gogglebox-prz
ed-telewizorem-odcinki,2777/odcinek-22,S13E22,192014
```
### Reproduction steps / Explicit stream URLs to test
In cmd run streamlink.exe https://player.pl/programy-online/gogglebox-przed-telewizorem-odcinki,2777/odcinek-22,S13E22,192014 best

### Log output

```
C:\Users\Mats>streamlink.exe --loglevel debug https://player.pl/programy-online/
gogglebox-przed-telewizorem-odcinki,2777/odcinek-22,S13E22,192014 best
[session][error] Failed to load plugin tvnplayer from C:\Users\Mats\AppData\Loca
l\Streamlink\pkgs\streamlink\plugins
Traceback (most recent call last):
  File "C:\Users\Mats\AppData\Local\Streamlink\pkgs\streamlink\session.py", line
 423, in load_plugins
    mod = load_module(module_name, path)
  File "C:\Users\Mats\AppData\Local\Streamlink\pkgs\streamlink\utils\__init__.py
", line 25, in load_module
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Mats\AppData\Local\Streamlink\pkgs\streamlink\plugins\tvnplayer
.py", line 12, in <module>
    from streamlink.plugin.api import http, validate
ImportError: cannot import name 'http' from 'streamlink.plugin.api' (C:\Users\Ma
ts\AppData\Local\Streamlink\pkgs\streamlink\plugin\api\__init__.py)
[cli][debug] OS:         Windows 7
[cli][debug] Python:     3.8.6
[cli][debug] Streamlink: 2.0.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
error: No plugin can handle URL: https://player.pl/programy-online/gogglebox-prz
ed-telewizorem-odcinki,2777/odcinek-22,S13E22,192014
```

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
Ask the person who wrote the plugin. This is external code which is unrelated to Streamlink.
https://github.com/oggy1989/streamlink-plugins/issues

Streamlink 2.0.0 has dropped support for python2 and has thus cleaned up its compatibility imports and methods. If you're trying to run a plugin which still relies on this old code, then you obviously can't use Streamlink 2.0.0.
