### ISSUE TITLE
Twitch.tv stream crash on Streamlink 2.0.0 / Streamlink Twitch GUI 1.11

### ISSUE THREAD

**Issue by haebawari** [streamlink/streamlink#3490]
## Issue

- [ ] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

Unexpected twitch stream crash. This is the first occurrence of the kind. Updated both Streamlink (2.0.0) and Streamlink Twitch GUI (1.11) yesterday. Happened after ~4 hours of playback time. 

### Expected / Actual behavior

Expected: Twitch stream playback going uninterrupted until stream ends.
Actual: Interrupted playback hours in.

### Reproduction steps / Explicit stream URLs to test

1. Have stream open

### Logs

Log from pop-up error message in Streamlink Twitch GUI
```
Found matching plugin twitch for URL twitch.tv/forsen
Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
Starting player: D:\mpv\mpv4\mpv.exe
Got HTTP request from libmpv
Opening stream: 1080p60 (hls)
Low latency streaming (HLS live edge: 1)
Exception in thread Thread-TwitchHLSStreamWriter:
Traceback (most recent call last):
File "D:\Streamlink 2.0.0\pkgs\urllib3\response.py", line 438, in _error_catcher
yield
File "D:\Streamlink 2.0.0\pkgs\urllib3\response.py", line 767, in read_chunked
chunk = self._handle_chunk(amt)
File "D:\Streamlink 2.0.0\pkgs\urllib3\response.py", line 711, in _handle_chunk
value = self._fp._safe_read(amt)
File "http\client.py", line 612, in _safe_read
File "socket.py", line 669, in readinto
File "ssl.py", line 1241, in recv_into
File "ssl.py", line 1099, in read
socket.timeout: The read operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "D:\Streamlink 2.0.0\pkgs\requests\models.py", line 753, in generate
for chunk in self.raw.stream(chunk_size, decode_content=True):
File "D:\Streamlink 2.0.0\pkgs\urllib3\response.py", line 572, in stream
for line in self.read_chunked(amt, decode_content=decode_content):
File "D:\Streamlink 2.0.0\pkgs\urllib3\response.py", line 793, in read_chunked
self._original_response.close()
File "contextlib.py", line 131, in __exit__
File "D:\Streamlink 2.0.0\pkgs\urllib3\response.py", line 443, in _error_catcher
raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='video-edge-1ff1b4.fra05.abs.hls.ttvnw.net', port=443): Read timed out.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "threading.py", line 932, in _bootstrap_inner
File "D:\Streamlink 2.0.0\pkgs\streamlink\stream\segmented.py", line 189, in run
self.write(segment, result)
File "D:\Streamlink 2.0.0\pkgs\streamlink\stream\hls.py", line 135, in write
return self._write(sequence, *args, **kwargs)
File "D:\Streamlink 2.0.0\pkgs\streamlink\stream\hls.py", line 169, in _write
for chunk in res.iter_content(chunk_size):
File "D:\Streamlink 2.0.0\pkgs\requests\models.py", line 760, in generate
raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='video-edge-1ff1b4.fra05.abs.hls.ttvnw.net', port=443): Read timed out.
```

### Additional comments, etc.

stream: twitch.tv/forsen

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
`urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='video-edge-1ff1b4.fra05.abs.hls.ttvnw.net', port=443): Read timed out.`

This error is the expected behavior. We're trying to get data from Twitch. The server doesn't respond quickly enough so we bomb out. There's nothing broken with Streamlink, That Twitch server must have been having a problem.

**Comment by Trung0246** [comment]
Just a question: is there's a way to configure streamlink such it will attempt to restart the stream instead bomb out? Or do I have to manually run the command again everytime it bomb out?
