### ISSUE TITLE
i can't uninstall pynput as gui-scrcpy needs it

### ISSUE THREAD

**Issue by esotericDisciple** [streamlink/streamlink#3560]
``` 
$ streamlink
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/streamlink/utils/l10n.py", line 8, in <module>
    from iso3166 import countries
ModuleNotFoundError: No module named 'iso3166'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/streamlink", line 33, in <module>
    sys.exit(load_entry_point('streamlink==2.0.0', 'console_scripts', 'streamlink')())
  File "/usr/bin/streamlink", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/streamlink_cli/main.py", line 20, in <module>
    import streamlink.logger as logger
  File "/usr/lib/python3.9/site-packages/streamlink/__init__.py", line 21, in <module>
    from streamlink.api import streams
  File "/usr/lib/python3.9/site-packages/streamlink/api.py", line 1, in <module>
    from streamlink.session import Streamlink
  File "/usr/lib/python3.9/site-packages/streamlink/session.py", line 14, in <module>
    from streamlink.utils.l10n import Localization
  File "/usr/lib/python3.9/site-packages/streamlink/utils/l10n.py", line 12, in <module>
    from pycountry import languages, countries
  File "/usr/lib/python3.9/site-packages/pycountry/__init__.py", line 10, in <module>
    import pkg_resources
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 559, in _build_master
    ws = cls()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 552, in __init__
    self.add_entry(entry)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 608, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2063, in find_on_path
    for dist in factory(fullpath):
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2128, in distributions_from_metadata
    yield Distribution.from_location(
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2588, in from_location
    return cls(
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2989, in _reload_version
    md_version = self._get_version()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2770, in _get_version
    version = _version_from_file(lines)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2554, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2765, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1417, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1407, in get_metadata
    value = self._get(path)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1611, in _get
    with open(path, 'rb') as stream:
```
**PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.9/site-packages/pynput-1.7.3-py3.9.egg-info/PKG-INFO'**
```

**Comment by bastimeyer** [comment]
> `pynput`

This is none of Streamlink's dependencies. Whatever you're trying to do here is unrelated to Streamlink.

> ModuleNotFoundError: No module named 'iso3166'

You've uninstalled `iso3166` and thus broken one of Streamlink's dependencies.

**Comment by esotericDisciple** [comment]
I didn't even know iso3166 was installed

**Comment by esotericDisciple** [comment]
I think Manjaro just forced out Python 3.9, that's just a hunch and all I have to go with right now...But the pynput error happened when typing streamlink in Konsole so it's related somehow

**Comment by esotericDisciple** [comment]
```
streamlink
usage: streamlink [OPTIONS] <URL> [STREAM]

Use -h/--help to see the available options or read the manual at https://streamlink.github.io
```
Were the archlinux wiki not a directly adjacent tab I probably wouldn't have found `pacman -Rdd` to use  to uninstall and reinstall pynput, which seems to have fixed the issue...

**Comment by esotericDisciple** [comment]
But it hasn't fixed the unexpected version check output error that's resurfaced with the twitch gui _and no, none of the older solutions are working or meaningful_
