### ISSUE TITLE
plugins.youtube: video_id not found by regexp

### ISSUE THREAD

**Issue by etam** [streamlink/streamlink#3668]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch: current master is c7bd7ec6099192d2b3c7bed1bbcd472cb8949f95

### Description

Streamlink fails to get stream url of a live stream. It used to do it fine few days ago.

### Reproduction steps / Explicit stream URLs to test

1. Try to play `https://www.youtube.com/c/Urz%C4%85dTransportuKolejowego/live`

### Log output

```
> ./bin/streamlink --loglevel debug "https://www.youtube.com/c/Urz%C4%85dTransportuKolejowego/live" 720p --stream-url
Traceback (most recent call last):
  File "./bin/streamlink", line 33, in <module>
    sys.exit(load_entry_point('streamlink==2.1.1+1.gc7bd7ec', 'console_scripts', 'streamlink')())
  File "/home/etam/tmp/streamlink_master/lib64/python3.8/site-packages/streamlink_cli/main.py", line 1075, in main
    handle_url()
  File "/home/etam/tmp/streamlink_master/lib64/python3.8/site-packages/streamlink_cli/main.py", line 566, in handle_url
    streams = fetch_streams(plugin)
  File "/home/etam/tmp/streamlink_master/lib64/python3.8/site-packages/streamlink_cli/main.py", line 459, in fetch_streams
    return plugin.streams(stream_types=args.stream_types,
  File "/home/etam/tmp/streamlink_master/lib64/python3.8/site-packages/streamlink/plugin/plugin.py", line 317, in streams
    ostreams = self._get_streams()
  File "/home/etam/tmp/streamlink_master/lib64/python3.8/site-packages/streamlink/plugins/youtube.py", line 301, in _get_streams
    self.video_id = self._find_video_id(self.url)
  File "/home/etam/tmp/streamlink_master/lib64/python3.8/site-packages/streamlink/plugins/youtube.py", line 262, in _find_video_id
    return self._find_video_id(canon_link)
  File "/home/etam/tmp/streamlink_master/lib64/python3.8/site-packages/streamlink/plugins/youtube.py", line 227, in _find_video_id
    if m.group("video_id"):
AttributeError: 'NoneType' object has no attribute 'group'
```

### Additional comments, etc.
If in 
https://github.com/streamlink/streamlink/blob/c7bd7ec6099192d2b3c7bed1bbcd472cb8949f95/src/streamlink/plugins/youtube.py#L227
I change it to
```python
if m and m.group("video_id"):
```
I get
```
error: Unable to open URL: https://consent.youtube.com/m (400 Client Error: Bad Request for url: https://consent.youtube.com/m)
```

**Comment by etam** [comment]
If I open in my browser a new private window and go to `youtube.com` I get redirected to `https://consent.youtube.com/m?continue=https%3A%2F%2Fwww.youtube.com%2F&gl=PL&m=0&pc=yt&uxe=23983172&hl=pl&src=1`

**Comment by dailywebtech** [comment]
the same output with streamlink over windows

` streamlink -l debug youtube.com/channel/UCFJBVnqU3i74W3HeIcGFmYQ/live
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.6
[cli][debug] Streamlink: 2.0.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin youtube for URL youtube.com/channel/UCFJBVnqU3i74W3HeIcGFmYQ/live
[plugins.youtube][debug] Re-directing to canonical URL: https://consent.youtube.com/m
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files (x86)\Streamlink\bin\streamlink.exe\__main__.py", line 18, in <module>
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 1052, in main
    handle_url()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 580, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 459, in fetch_streams
    return plugin.streams(stream_types=args.stream_types,
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 317, in streams
    ostreams = self._get_streams()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\youtube.py", line 301, in _get_streams
    self.video_id = self._find_video_id(self.url)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\youtube.py", line 262, in _find_video_id
    return self._find_video_id(canon_link)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\youtube.py", line 227, in _find_video_id
    if m.group("video_id"):
AttributeError: 'NoneType' object has no attribute 'group'`

**Comment by bastimeyer** [comment]
```
$ streamlink -l debug 'https://www.youtube.com/c/Urz%C4%85dTransportuKolejowego/live'
[cli][debug] OS:         Linux-5.11.10-arch1-1-x86_64-with-glibc2.33
[cli][debug] Python:     3.9.2
[cli][debug] Streamlink: 2.1.1+0.g6a30ed7
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=https://www.youtube.com/c/Urz%C4%85dTransportuKolejowego/live
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/c/Urz%C4%85dTransportuKolejowego/live
[plugins.youtube][debug] Re-directing to canonical URL: https://consent.youtube.com/m
Traceback (most recent call last):
  File "/home/basti/.local/bin/streamlink", line 33, in <module>
    sys.exit(load_entry_point('streamlink', 'console_scripts', 'streamlink')())
  File "/home/basti/repos/streamlink/src/streamlink_cli/main.py", line 1073, in main
    handle_url()
  File "/home/basti/repos/streamlink/src/streamlink_cli/main.py", line 564, in handle_url
    streams = fetch_streams(plugin)
  File "/home/basti/repos/streamlink/src/streamlink_cli/main.py", line 457, in fetch_streams
    return plugin.streams(stream_types=args.stream_types,
  File "/home/basti/repos/streamlink/src/streamlink/plugin/plugin.py", line 317, in streams
    ostreams = self._get_streams()
  File "/home/basti/repos/streamlink/src/streamlink/plugins/youtube.py", line 301, in _get_streams
    self.video_id = self._find_video_id(self.url)
  File "/home/basti/repos/streamlink/src/streamlink/plugins/youtube.py", line 262, in _find_video_id
    return self._find_video_id(canon_link)
  File "/home/basti/repos/streamlink/src/streamlink/plugins/youtube.py", line 227, in _find_video_id
    if m.group("video_id"):
AttributeError: 'NoneType' object has no attribute 'group'
```

> [plugins.youtube][debug] Re-directing to canonical URL: https://consent.youtube.com/m

This is new on YT and the plugin doesn't support handling the consent dialog/page yet.

**Comment by etam** [comment]
I confirm that the merged code fixes this issue.
