### ISSUE TITLE
plugins.FunimationNow: no subtitles by default, --mux-subtitles leads to error

### ISSUE THREAD

**Issue by FaceHiddenInsideTheDark** [streamlink/streamlink#3751]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Description

Funimation has no issue streaming from URL in English, but has issues with streaming with subtitles when I set --funimation-language="japanese" No subtitles are present, but the stream works perfectly otherwise. When I pass --mux-subtitles ffmpegmux.py throws an exception.

### Reproduction steps / Explicit stream URLs to test

1. execute `streamlink --funimation-email="xxx" --funimation-password="xxx" --http-cookie "incap_ses_xxx=xxx" "https://www.funimation.com/en/shows/my-hero-academia/early-bird/" best --funimation-language="japanese" --mux-subtitles`
2. view error log output instead of stream with subs

### Log output

```
[cli][info] Found matching plugin funimationnow for URL https://www.funimation.com/en/shows/my-hero-academia/early-bird/
[plugins.funimationnow][info] Logged in to Funimation as xxx
[cli][info] Available streams: 234p (worst), 360p, 432p_alt, 432p, 480p, 540p, 720p_alt, 720p, 1080p_alt, 1080p (best)
[cli][info] Opening stream: 1080p (muxed-stream)
[utils.named_pipe][info] Creating pipe streamlinkpipe-18212-1-9266
[utils.named_pipe][info] Creating pipe streamlinkpipe-18212-2-5174
[utils.named_pipe][info] Creating pipe streamlinkpipe-18212-3-4767
[utils.named_pipe][info] Creating pipe streamlinkpipe-18212-4-5528
[cli][info] Starting player: "D:\Programs\MPV\mpv.exe"
Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\ffmpegmux.py", line 66, in copy_to_pipe
    data = stream.read(8192)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\ffmpegmux.py", line 156, in read
    data = self.process.stdout.read(size)
ValueError: read of closed file
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

### Additional comments, etc.
I wish I could just use a --funimation-subtitles="english" instead of having to mux them with ffmpeg. Funimation's default settings are for language to be in Japanese and English for subtitles, with the option to switch over to dub if need be, this should also be default for the funimationnow plugin.

**Comment by FaceHiddenInsideTheDark** [comment]
Found a workaround:
The error was with had to do with parsing AAC extradata. Attaching --ffmpeg-audio-transcode aac at the end of my command fixed the issue.
