### ISSUE TITLE
youtube.py: Live-Channels don't work - AttributeError

### ISSUE THREAD

**Issue by malvinas2** [streamlink/streamlink#3826]
### Description
Stream doesn't start ;-)

Ubuntu 20.04.1 LTS (GNU/Linux 3.16.85-62 aarch64)
Streamlink 2.2.0

### Reproduction steps / Explicit stream URLs to test
America TV
`streamlink http://www.youtube.com/channel/UC6NVDkuzY2exMOVFw4i9oHw/live 720p`
C5N
`streamlink http://www.youtube.com/channel/UCFgk2Q2mVO1BklRQhSv6p0w/live 720p`

### Log output

```
2021-06-24 22:06:40.254 spawn: [cli][info] Found matching plugin youtube for URL http://www.youtube.com/channel/UC6NVDkuzY2exMOVFw4i9oHw/live
2021-06-24 22:06:50.896 spawn: Traceback (most recent call last):
2021-06-24 22:06:50.896 spawn:   File "/usr/local/bin/streamlink", line 8, in 
2021-06-24 22:06:50.896 spawn:     sys.exit(main())
2021-06-24 22:06:50.896 spawn:   File "/usr/local/lib/python3.8/dist-packages/streamlink_cli/main.py", line 1029, in main
2021-06-24 22:06:50.896 spawn:     handle_url()
2021-06-24 22:06:50.896 spawn:   File "/usr/local/lib/python3.8/dist-packages/streamlink_cli/main.py", line 585, in handle_url
2021-06-24 22:06:50.896 spawn:     streams = fetch_streams(plugin)
2021-06-24 22:06:50.896 spawn:   File "/usr/local/lib/python3.8/dist-packages/streamlink_cli/main.py", line 464, in fetch_streams
2021-06-24 22:06:50.896 spawn:     return plugin.streams(stream_types=args.stream_types,
2021-06-24 22:06:50.896 spawn:   File "/usr/local/lib/python3.8/dist-packages/streamlink/plugin/plugin.py", line 317, in streams
2021-06-24 22:06:50.896 spawn:     ostreams = self._get_streams()
2021-06-24 22:06:50.896 spawn:   File "/usr/local/lib/python3.8/dist-packages/streamlink/plugins/youtube.py", line 286, in _get_streams
2021-06-24 22:06:50.896 spawn:     if not self._data_status(data):
2021-06-24 22:06:50.896 spawn:   File "/usr/local/lib/python3.8/dist-packages/streamlink/plugins/youtube.py", line 277, in _data_status
2021-06-24 22:06:50.896 spawn:     status, reason = self._schema_playabilitystatus(data)
2021-06-24 22:06:50.896 spawn:   File "/usr/local/lib/python3.8/dist-packages/streamlink/plugins/youtube.py", line 126, in _schema_playabilitystatus
2021-06-24 22:06:50.896 spawn:     validate.union_get("status", "reason")
2021-06-24 22:06:50.896 spawn: AttributeError: module 'streamlink.plugin.api.validate' has no attribute 'union_get'
```

**Comment by bastimeyer** [comment]
> Streamlink 2.2.0
> AttributeError: module 'streamlink.plugin.api.validate' has no attribute 'union_get'

You are **not using the right Streamlink `2.2.0` version**.
Streamlink `2.2.0` includes new validation methods, one of them being `union_get`.

You must have copied the new plugin into an old Streamlink version. This is explicitly not supported. Closing...

```
$ streamlink -l debug youtube.com/channel/UC6NVDkuzY2exMOVFw4i9oHw/live 720p
[cli][debug] OS:         Linux-5.12.13-1-git-x86_64-with-glibc2.33
[cli][debug] Python:     3.9.5
[cli][debug] Streamlink: 2.2.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=youtube.com/channel/UC6NVDkuzY2exMOVFw4i9oHw/live
[cli][debug]  stream=['720p']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][info] Found matching plugin youtube for URL youtube.com/channel/UC6NVDkuzY2exMOVFw4i9oHw/live
[plugins.youtube][debug] c_data_keys: gl, m, pc, continue, ca, x, v, t, hl, src, uxe
[plugins.youtube][debug] Using video ID: 2Vyx4ee2Tss
[plugins.youtube][debug] This video is live.
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 720p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 5347459; Last Sequence: 5347464
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 5347462; End Sequence: None
[stream.hls][debug] Adding segment 5347462 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 5347463 to queue
[stream.hls][debug] Adding segment 5347464 to queue
[stream.hls][debug] Download of segment 5347462 complete
[cli][info] Starting player: mpv
[cli.output][debug] Opening subprocess: mpv --force-media-title=youtube.com/channel/UC6NVDkuzY2exMOVFw4i9oHw/live -
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 5347463 complete
[stream.hls][debug] Download of segment 5347464 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 5347465 to queue
[stream.hls][debug] Download of segment 5347465 complete
[cli][info] Player closed
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by malvinas2** [comment]
> You must have copied the new plugin into an old Streamlink version. 

That's indeed what I did first, but before posting the issue I upgraded to 2.2.0 as shown in the screenshot. 

streamlink -V outputs 2.2.0

![sl](https://user-images.githubusercontent.com/25912063/123328620-190d7b00-d53c-11eb-93c3-23e82b0aa4f9.png)

**Comment by bastimeyer** [comment]
You are not using a clean `2.2.0` install, otherwise you wouldn't be seeing the error message. Simple as that. There is no support for any custom/hacked solutions here.

Use `--loglevel debug` to check that you are indeed using the right version, incase you have accidentally installed multiple versions.

**Comment by malvinas2** [comment]
I get the same output like you using the shell, everything seems to be fine. 
But from within _TVHeadend_ I still get the error messages shown in the first post; apart from **youtube.py** other plugins like _rtve.py_ work without problems. 

Maybe there are other TVHeadend users out there, who can help?

**Comment by bastimeyer** [comment]
Issues of downstream projects which have streamlink as a dependency are out of scope. You'll have to ask on the respective project's issue tracker, support channel, etc.

As said, manually copying plugins from newer Streamlink versions into older ones is not supported, regardless whether you're using Streamlink directly or via a third party project. If this third party project is based on an older Streamlink version and you want the latest upgrades, then this project will have to upgrade to the latest Streamlink version.

**Comment by back-to** [comment]
@malvinas2 

> But from within TVHeadend I still get the error messages shown in the first post; apart from youtube.py other plugins like rtve.py work without problems.

you installed multiple `Streamlink` on your system
one was installed with _sudo_ the other just as _--user_

remove both and reinstall, might be the easiest way.

> /usr/local/lib/python3.8/dist-packages/streamlink
> /home/arg/.local/lib/python3.8/site-packages/streamlink

https://streamlink.github.io/latest/install.html#pypi-package-and-source-code
