### ISSUE TITLE
python problem PLAYER_VERSION is not defined

### ISSUE THREAD

**Issue by c769214** [streamlink/streamlink#388]
user@user-Sys:~$ streamlink  http://vaughnlive.tv/sherming9 best
[cli][info] Found matching plugin xxx_vaughnlive for URL http://vaughnlive.tv/sherming9
Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 9, in <module>
    load_entry_point('streamlink==0.0.2', 'console_scripts', 'streamlink')()
  File "/usr/local/lib/python2.7/dist-packages/streamlink_cli/main.py", line 902, in main
    handle_url()
  File "/usr/local/lib/python2.7/dist-packages/streamlink_cli/main.py", line 479, in handle_url
    streams = fetch_streams(plugin)
  File "/usr/local/lib/python2.7/dist-packages/streamlink_cli/main.py", line 392, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/usr/local/lib/python2.7/dist-packages/streamlink/plugin/plugin.py", line 316, in get_streams
    return self.streams(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/streamlink/plugin/plugin.py", line 230, in streams
    ostreams = self._get_streams()
  File "/usr/local/lib/python2.7/dist-packages/streamlink/plugins/vaughnlive.py", line 62, in _get_streams
    params["domain"] = DOMAIN_MAP.get(match.group("domain"), match.group("domain"))
NameError: global name 'PLAYER_VERSION' is not defined

Did anyone have the same problem like that? 
Thanks in advance.

**Comment by gravyboat** [comment]
This was fixed here: https://github.com/streamlink/streamlink/pull/383 which was merged earlier today, give the nightly a shot: https://streamlink-builds.s3.amazonaws.com/nightly/windows/streamlink-latest.exe
