### ISSUE TITLE
plugins.raiplay: StreamError: Unable to open URL

### ISSUE THREAD

**Issue by tommyv** [streamlink/streamlink#3895]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Some Raiplay channels don't work correctly anymore: RAI1 has intermittent errors, RAI YoYo all the time.

Posting debug log for RAI YoYo

### Debug log

```text
root@compiler:~# /usr/bin/myenv/bin/streamlink https://www.raiplay.it/dirette/raiyoyo best --loglevel debug
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-5.4.128-1-pve-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     3.6.9
[cli][debug] Streamlink: 2.3.0
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.1.0)
[cli][debug] Arguments:
[cli][debug]  url=https://www.raiplay.it/dirette/raiyoyo
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin raiplay for URL https://www.raiplay.it/dirette/raiyoyo
[plugins.raiplay][debug] Found JSON URL: https://www.raiplay.it/dirette/raiyoyo.json
[plugins.raiplay][debug] Found stream URL: https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=746899
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 396p (worst), 504p, 576p (best)
[cli][info] Opening stream: 576p (hls)
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
Exception in thread Thread-HLSStreamWorker:
Traceback (most recent call last):
  File "/usr/bin/myenv/lib/python3.6/site-packages/streamlink/plugin/api/http_session.py", line 160, in request
    res.raise_for_status()
  File "/usr/bin/myenv/lib/python3.6/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://raiyoyo1-live.akamaized.net/hls/live/598330/raiyoyo1/raiyoyo1/raiyoyo_2400/exp=1627978393%E2%80%BEacl=%2Fhls%2Flive%2F598330%2Fraiyoyo1%2F*!%2Fhls%2Flive%2F598330-b%2Fraiyoyo1%2F*!%2F*.key%E2%80%BEdata=hdntl%E2%80%BEhmac=9eeac7cf3dcdd5bf8689690362dd426110851e1d5702a8ac9d3747add830ea74/chunklist.m3u8?aka_me_session_id=AAAAAAAAAACZ+ghhAAAAAN5phokQGkTQdf2RLap3zbDCUeLSU3mMfyfC2IVCGxEadJlEwos5X%2FCxWQPX3y4Ls6SsHPWHNqFs&aka_media_format_type=hls

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/bin/myenv/lib/python3.6/site-packages/streamlink/stream/segmented.py", line 84, in run
    for segment in self.iter_segments():
  File "/usr/bin/myenv/lib/python3.6/site-packages/streamlink/stream/hls.py", line 325, in iter_segments
    self.reload_playlist()
  File "/usr/bin/myenv/lib/python3.6/site-packages/streamlink/stream/hls.py", line 246, in reload_playlist
    **self.reader.request_params)
  File "/usr/bin/myenv/lib/python3.6/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/bin/myenv/lib/python3.6/site-packages/streamlink/plugin/api/http_session.py", line 168, in request
    raise err
streamlink.exceptions.StreamError: Unable to open URL: https://raiyoyo1-live.akamaized.net/hls/live/598330/raiyoyo1/raiyoyo1/raiyoyo_2400/exp=1627978393%E2%80%BEacl=%2Fhls%2Flive%2F598330%2Fraiyoyo1%2F*!%2Fhls%2Flive%2F598330-b%2Fraiyoyo1%2F*!%2F*.key%E2%80%BEdata=hdntl%E2%80%BEhmac=9eeac7cf3dcdd5bf8689690362dd426110851e1d5702a8ac9d3747add830ea74/chunklist.m3u8?aka_me_session_id=AAAAAAAAAACZ+ghhAAAAAN5phokQGkTQdf2RLap3zbDCUeLSU3mMfyfC2IVCGxEadJlEwos5X%2FCxWQPX3y4Ls6SsHPWHNqFs&aka_media_format_type=hls (403 Client Error: Forbidden for url: https://raiyoyo1-live.akamaized.net/hls/live/598330/raiyoyo1/raiyoyo1/raiyoyo_2400/exp=1627978393%E2%80%BEacl=%2Fhls%2Flive%2F598330%2Fraiyoyo1%2F*!%2Fhls%2Flive%2F598330-b%2Fraiyoyo1%2F*!%2F*.key%E2%80%BEdata=hdntl%E2%80%BEhmac=9eeac7cf3dcdd5bf8689690362dd426110851e1d5702a8ac9d3747add830ea74/chunklist.m3u8?aka_me_session_id=AAAAAAAAAACZ+ghhAAAAAN5phokQGkTQdf2RLap3zbDCUeLSU3mMfyfC2IVCGxEadJlEwos5X%2FCxWQPX3y4Ls6SsHPWHNqFs&aka_media_format_type=hls)

[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][error] Try 1/1: Could not open stream <HLSStream('https://raiyoyo1-live.akamaized.net/hls/live/598330/raiyoyo1/raiyoyo1/raiyoyo_2400/exp=1627978393%E2%80%BEacl=%2Fhls%2Flive%2F598330%2Fraiyoyo1%2F*!%2Fhls%2Flive%2F598330-b%2Fraiyoyo1%2F*!%2F*.key%E2%80%BEdata=hdntl%E2%80%BEhmac=9eeac7cf3dcdd5bf8689690362dd426110851e1d5702a8ac9d3747add830ea74/chunklist.m3u8?aka_me_session_id=AAAAAAAAAACZ+ghhAAAAAN5phokQGkTQdf2RLap3zbDCUeLSU3mMfyfC2IVCGxEadJlEwos5X%2FCxWQPX3y4Ls6SsHPWHNqFs&aka_media_format_type=hls', 'https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=746899')> (Failed to read data from stream: Read timeout)
error: Could not open stream <HLSStream('https://raiyoyo1-live.akamaized.net/hls/live/598330/raiyoyo1/raiyoyo1/raiyoyo_2400/exp=1627978393%E2%80%BEacl=%2Fhls%2Flive%2F598330%2Fraiyoyo1%2F*!%2Fhls%2Flive%2F598330-b%2Fraiyoyo1%2F*!%2F*.key%E2%80%BEdata=hdntl%E2%80%BEhmac=9eeac7cf3dcdd5bf8689690362dd426110851e1d5702a8ac9d3747add830ea74/chunklist.m3u8?aka_me_session_id=AAAAAAAAAACZ+ghhAAAAAN5phokQGkTQdf2RLap3zbDCUeLSU3mMfyfC2IVCGxEadJlEwos5X%2FCxWQPX3y4Ls6SsHPWHNqFs&aka_media_format_type=hls', 'https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=746899')>, tried 1 times, exiting
[cli][info] Closing currently open stream...
```

**Comment by back-to** [comment]
there are two issues

---

1. Streamlink shouldn't crash with `streamlink.exceptions.StreamError:`

---

2. `Requests(2.26.0)` and `charset_normalizer` doesn't work correctly

install `chardet` and it should work again

Example:

```
$ pip uninstall chardet
Found existing installation: chardet 4.0.0
Uninstalling chardet-4.0.0:
  Would remove:
    /venv/bin/chardetect
    /venv/lib/python3.9/site-packages/chardet-4.0.0.dist-info/*
    /venv/lib/python3.9/site-packages/chardet/*
Proceed (y/n)? y
  Successfully uninstalled chardet-4.0.0
```

```
$ streamlink https://www.raiplay.it/dirette/raiyoyo
[cli][debug] OS:         Linux-5.11.0-25-generic-x86_64-with-glibc2.33
[cli][debug] Python:     3.9.5
[cli][debug] Streamlink: 2.3.0+2.gccdd84b
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(0.58.0)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://raiyove/598330/raiyoyo1/raiyoyo1/raiyoyo_2400/exp=1628017135%E2%80
streamlink.exceptions.StreamError: Unable to open URL: https://raiyoyo1-live.akamaized.net/hls/live/598330/raiyoyo1/raiyoyo1/raiyoyo_2400/exp=1628017135%E2%80%BEacl=
```

```
$ pip install chardet
Collecting chardet
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Installing collected packages: chardet
Successfully installed chardet-4.0.0
```

```
$ streamlink https://www.raiplay.it/dirette/raiyoyo
[cli][debug] OS:         Linux-5.11.0-25-generic-x86_64-with-glibc2.33
[cli][debug] Python:     3.9.5
[cli][debug] Streamlink: 2.3.0+2.gccdd84b
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(0.58.0)
[cli][info] Found matching plugin raiplay for URL https://www.raiplay.it/dirette/raiyoyo
[plugins.raiplay][debug] Found JSON URL: https://www.raiplay.it/dirette/raiyoyo.json
[plugins.raiplay][debug] Found stream URL: https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=746899
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 396p (worst), 504p, 576p (best)
[cli][info] Opening stream: 576p (hls)
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] First Sequence: 104345; Last Sequence: 105784
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 105782; End Sequence: None
[stream.hls][debug] Adding segment 105782 to queue
[stream.hls][debug] Adding segment 105783 to queue
[stream.hls][debug] Adding segment 105784 to queue
[stream.hls][debug] Segment 105782 complete
[cli][info] Starting player: /usr/bin/mpv
[cli.output][debug] Opening subprocess: /usr/bin/mpv "--force-media-title=Unknown Title" -
[stream.hls][debug] Segment 105783 complete
[cli][debug] Writing stream to output
```

**Comment by tommyv** [comment]
Thanks, tried as suggested:

```
root@compiler:~# pip3 install chardet
Collecting chardet
  Using cached https://files.pythonhosted.org/packages/19/c7/fa589626997dd07bd87d9269342ccb74b1720384a4d739a1872bd84fbe68/chardet-4.0.0-py2.py3-none-any.whl
Installing collected packages: chardet
Successfully installed chardet-4.0.0
```
and then

```
root@compiler:~# /usr/bin/myenv/bin/streamlink https://www.raiplay.it/dirette/raiyoyo best --loglevel debug
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-5.4.128-1-pve-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     3.6.9
[cli][debug] Streamlink: 2.3.0
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.1.0)
[cli][debug] Arguments:
[cli][debug]  url=https://www.raiplay.it/dirette/raiyoyo
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin raiplay for URL https://www.raiplay.it/dirette/raiyoyo
[plugins.raiplay][debug] Found JSON URL: https://www.raiplay.it/dirette/raiyoyo.json
[plugins.raiplay][debug] Found stream URL: https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=746899
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 396p (worst), 504p, 576p (best)
[cli][info] Opening stream: 576p (hls)
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
Exception in thread Thread-HLSStreamWorker:
Traceback (most recent call last):
  File "/usr/bin/myenv/lib/python3.6/site-packages/streamlink/plugin/api/http_session.py", line 160, in request
    res.raise_for_status()
  File "/usr/bin/myenv/lib/python3.6/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://raiyoyo1-live.akamaized.net/hls/live/598330/raiyoyo1/raiyoyo1/raiyoyo_2400/exp=1628019329%E2%80%BEacl=%2Fhls%2Flive%2F598330%2Fraiyoyo1%2F*!%2Fhls%2Flive%2F598330-b%2Fraiyoyo1%2F*!%2F*.key%E2%80%BEdata=hdntl%E2%80%BEhmac=bc5698c88f1fb7cf2c01dd6cc9e19f7cb08247019d021e760e924f15dfdb920a/chunklist.m3u8?aka_me_session_id=AAAAAAAAAACBmglhAAAAAG23IK5Ct6xYFeS4pZ6Jg8jc05cveN4myZqsFwilclJqrjLq2O9EQ%2FEQ01Enl6QhSAChCwpyR4NH&aka_media_format_type=hls

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/bin/myenv/lib/python3.6/site-packages/streamlink/stream/segmented.py", line 84, in run
    for segment in self.iter_segments():
  File "/usr/bin/myenv/lib/python3.6/site-packages/streamlink/stream/hls.py", line 325, in iter_segments
    self.reload_playlist()
  File "/usr/bin/myenv/lib/python3.6/site-packages/streamlink/stream/hls.py", line 246, in reload_playlist
    **self.reader.request_params)
  File "/usr/bin/myenv/lib/python3.6/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/bin/myenv/lib/python3.6/site-packages/streamlink/plugin/api/http_session.py", line 168, in request
    raise err
streamlink.exceptions.StreamError: Unable to open URL: https://raiyoyo1-live.akamaized.net/hls/live/598330/raiyoyo1/raiyoyo1/raiyoyo_2400/exp=1628019329%E2%80%BEacl=%2Fhls%2Flive%2F598330%2Fraiyoyo1%2F*!%2Fhls%2Flive%2F598330-b%2Fraiyoyo1%2F*!%2F*.key%E2%80%BEdata=hdntl%E2%80%BEhmac=bc5698c88f1fb7cf2c01dd6cc9e19f7cb08247019d021e760e924f15dfdb920a/chunklist.m3u8?aka_me_session_id=AAAAAAAAAACBmglhAAAAAG23IK5Ct6xYFeS4pZ6Jg8jc05cveN4myZqsFwilclJqrjLq2O9EQ%2FEQ01Enl6QhSAChCwpyR4NH&aka_media_format_type=hls (403 Client Error: Forbidden for url: https://raiyoyo1-live.akamaized.net/hls/live/598330/raiyoyo1/raiyoyo1/raiyoyo_2400/exp=1628019329%E2%80%BEacl=%2Fhls%2Flive%2F598330%2Fraiyoyo1%2F*!%2Fhls%2Flive%2F598330-b%2Fraiyoyo1%2F*!%2F*.key%E2%80%BEdata=hdntl%E2%80%BEhmac=bc5698c88f1fb7cf2c01dd6cc9e19f7cb08247019d021e760e924f15dfdb920a/chunklist.m3u8?aka_me_session_id=AAAAAAAAAACBmglhAAAAAG23IK5Ct6xYFeS4pZ6Jg8jc05cveN4myZqsFwilclJqrjLq2O9EQ%2FEQ01Enl6QhSAChCwpyR4NH&aka_media_format_type=hls)

[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][error] Try 1/1: Could not open stream <HLSStream('https://raiyoyo1-live.akamaized.net/hls/live/598330/raiyoyo1/raiyoyo1/raiyoyo_2400/exp=1628019329%E2%80%BEacl=%2Fhls%2Flive%2F598330%2Fraiyoyo1%2F*!%2Fhls%2Flive%2F598330-b%2Fraiyoyo1%2F*!%2F*.key%E2%80%BEdata=hdntl%E2%80%BEhmac=bc5698c88f1fb7cf2c01dd6cc9e19f7cb08247019d021e760e924f15dfdb920a/chunklist.m3u8?aka_me_session_id=AAAAAAAAAACBmglhAAAAAG23IK5Ct6xYFeS4pZ6Jg8jc05cveN4myZqsFwilclJqrjLq2O9EQ%2FEQ01Enl6QhSAChCwpyR4NH&aka_media_format_type=hls', 'https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=746899')> (Failed to read data from stream: Read timeout)
error: Could not open stream <HLSStream('https://raiyoyo1-live.akamaized.net/hls/live/598330/raiyoyo1/raiyoyo1/raiyoyo_2400/exp=1628019329%E2%80%BEacl=%2Fhls%2Flive%2F598330%2Fraiyoyo1%2F*!%2Fhls%2Flive%2F598330-b%2Fraiyoyo1%2F*!%2F*.key%E2%80%BEdata=hdntl%E2%80%BEhmac=bc5698c88f1fb7cf2c01dd6cc9e19f7cb08247019d021e760e924f15dfdb920a/chunklist.m3u8?aka_me_session_id=AAAAAAAAAACBmglhAAAAAG23IK5Ct6xYFeS4pZ6Jg8jc05cveN4myZqsFwilclJqrjLq2O9EQ%2FEQ01Enl6QhSAChCwpyR4NH&aka_media_format_type=hls', 'https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=746899')>, tried 1 times, exiting
[cli][info] Closing currently open stream...
```

While RAI3 for example produces this:

```
root@compiler:~# /usr/bin/myenv/bin/streamlink https://www.raiplay.it/dirette/rai3 best -l debug
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-5.4.128-1-pve-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     3.6.9
[cli][debug] Streamlink: 2.3.0
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.1.0)
[cli][debug] Arguments:
[cli][debug]  url=https://www.raiplay.it/dirette/rai3
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin raiplay for URL https://www.raiplay.it/dirette/rai3
[plugins.raiplay][debug] Found JSON URL: https://www.raiplay.it/dirette/rai3.json
[plugins.raiplay][debug] Found stream URL: https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=308709
[utils.l10n][debug] Language code: en_US
[stream.hls][debug] Using external audio tracks for stream 576p (language=ita, name=Italiano)
[stream.hls][debug] Using external audio tracks for stream 522p (language=ita, name=Italiano)
[stream.hls][debug] Using external audio tracks for stream 396p (language=ita, name=Italiano)
[cli][info] Available streams: 396p (worst), 522p, 576p (best)
[cli][info] Opening stream: 576p (hls-multi)
[stream.ffmpegmux][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[stream.ffmpegmux][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[utils.named_pipe][info] Creating pipe streamlinkpipe-723-1-5023
[utils.named_pipe][info] Creating pipe streamlinkpipe-723-2-1634
[stream.ffmpegmux][debug] ffmpeg command: ffmpeg -nostats -y -i /tmp/streamlinkpipe-723-1-5023 -i /tmp/streamlinkpipe-723-2-1634 -c:v copy -c:a copy -map 0:v? -map 0:a? -map 1:a -f mpegts pipe:1
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/streamlinkpipe-723-1-5023
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/streamlinkpipe-723-2-1634
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] First Sequence: 173401; Last Sequence: 174840
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 174838; End Sequence: None
[stream.hls][debug] Adding segment 174838 to queue
[stream.hls][debug] Adding segment 174839 to queue
[stream.hls][debug] Adding segment 174840 to queue
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] First Sequence: 173401; Last Sequence: 174840
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 174838; End Sequence: None
[stream.hls][debug] Adding segment 174838 to queue
[stream.hls][debug] Adding segment 174839 to queue
[stream.hls][debug] Adding segment 174840 to queue
[stream.hls][debug] Segment 174838 complete
[stream.hls][debug] Segment 174839 complete
[stream.hls][debug] Segment 174840 complete
[stream.hls][debug] Segment 174838 complete
[cli][info] Starting player: /usr/bin/vlc
[cli.output][debug] Opening subprocess: /usr/bin/vlc --input-title-format https://www.raiplay.it/dirette/rai3 -
error: Failed to start player: /usr/bin/vlc (Process exited prematurely)
[cli][info] Closing currently open stream...
[stream.ffmpegmux][debug] Closing ffmpeg thread
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[stream.ffmpegmux][error] Pipe copy aborted: /tmp/streamlinkpipe-723-2-1634
[stream.ffmpegmux][error] Pipe copy aborted: /tmp/streamlinkpipe-723-1-5023
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[stream.ffmpegmux][debug] Closed all the substreams
```

**Comment by bastimeyer** [comment]
@back-to We can force the old `chardet` dependency of `requests>=2.26.0` instead of `charset_normalizer` [via `requests[use_chardet_on_py3]>=2.26.0`](https://github.com/psf/requests/blob/v2.26.0/setup.py#L107), but if it's indeed an upstream issue, then it should be reported there.

**Comment by tommyv** [comment]
Forgot to install `chardet` under virtual environment. No error now, only takes up to 60 seconds to start playing, wonder why ?
