### ISSUE TITLE
plugins.Zbiornik: Not working

### ISSUE THREAD

**Issue by michalMonster** [streamlink/streamlink#3934]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

After entering the streamlink command https://zbiornik.tv/live/mc_mc best -o mc_mc.mp4 an error pops up.

```
[session][error] Failed to load plugin cam4 from C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\session.py", line 472, in load_plugins
    mod = load_module(module_name, path)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\__init__.py", line 26, in load_module
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\cam4.py", line 4, in <module>
    from streamlink.plugin.api import http, useragents, validate
ImportError: cannot import name 'http' from 'streamlink.plugin.api' (C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\api\__init__.py)
[session][error] Failed to load plugin camsoda from C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\session.py", line 472, in load_plugins
    mod = load_module(module_name, path)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\__init__.py", line 26, in load_module
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\camsoda.py", line 6, in <module>
    from streamlink.plugin.api import http
ImportError: cannot import name 'http' from 'streamlink.plugin.api' (C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\api\__init__.py)
[session][error] Failed to load plugin myfreecams from C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\session.py", line 472, in load_plugins
    mod = load_module(module_name, path)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\__init__.py", line 26, in load_module
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\myfreecams.py", line 6, in <module>
    from streamlink.compat import unquote
ImportError: cannot import name 'unquote' from 'streamlink.compat' (C:\Program Files (x86)\Streamlink\pkgs\streamlink\compat.py)
[session][info] Resolved plugin zbiornik with deprecated can_handle_url API
[cli][info] Found matching plugin zbiornik for URL https://zbiornik.tv/mc_mc
[plugins.zbiornik][info] This is a custom plugin.
[plugins.zbiornik][info] Channel: mc_mc
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (rtmp)
[cli][error] Try 1/1: Could not open stream <RTMPStream({'rtmp': 'rtmp://c6.zbiornik.com/videochat/', 'pageUrl': 'https://zbiornik.tv/mc_mc', 'app': 'videochat/?57f4ac9f66b7d9296573c79d56dedf67', 'playpath': '3946429-public', 'swfVfy': 'https://zbiornik.tv/wowza.swf', 'live': True, 'flv': '-'}, redirect=False> (Could not open stream: rtmpdump.exe is not installed or not supported on your system)
error: Could not open stream <RTMPStream({'rtmp': 'rtmp://c6.zbiornik.com/videochat/', 'pageUrl': 'https://zbiornik.tv/mc_mc', 'app': 'videochat/?57f4ac9f66b7d9296573c79d56dedf67', 'playpath': '3946429-public', 'swfVfy': 'https://zbiornik.tv/wowza.swf', 'live': True, 'flv': '-'}, redirect=False>, tried 1 times, exiting
```

### Debug log

```text
[session][error] Failed to load plugin cam4 from C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\session.py", line 472, in load_plugins
    mod = load_module(module_name, path)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\__init__.py", line 26, in load_module
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\cam4.py", line 4, in <module>
    from streamlink.plugin.api import http, useragents, validate
ImportError: cannot import name 'http' from 'streamlink.plugin.api' (C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\api\__init__.py)
[session][error] Failed to load plugin camsoda from C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\session.py", line 472, in load_plugins
    mod = load_module(module_name, path)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\__init__.py", line 26, in load_module
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\camsoda.py", line 6, in <module>
    from streamlink.plugin.api import http
ImportError: cannot import name 'http' from 'streamlink.plugin.api' (C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\api\__init__.py)
[session][error] Failed to load plugin myfreecams from C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\session.py", line 472, in load_plugins
    mod = load_module(module_name, path)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\__init__.py", line 26, in load_module
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\myfreecams.py", line 6, in <module>
    from streamlink.compat import unquote
ImportError: cannot import name 'unquote' from 'streamlink.compat' (C:\Program Files (x86)\Streamlink\pkgs\streamlink\compat.py)
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.7
[cli][debug] Streamlink: 2.3.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(1.1.0)
[cli][debug] Arguments:
[cli][debug]  --loglevel=debug
[cli][debug]  --rtmp-rtmpdump=rtmpdump.exe
[cli][debug]  --rtmpdump=C:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
usage: streamlink [OPTIONS] <URL> [STREAM]

Use -h/--help to see the available options or read the manual at https://streamlink.github.io
```

**Comment by bastimeyer** [comment]
> [session][error] Failed to load plugin cam4
> [session][error] Failed to load plugin camsoda
> [session][error] Failed to load plugin myfreecams
> [plugins.zbiornik][info] This is a custom plugin.
> [plugins.zbiornik][info] Channel: mc_mc

unsupported
