### ISSUE TITLE
ERROR: test_open_windows (tests.test_output.TestFileOutput) ... AttributeError: <module 'streamlink_cli.output' does not have the attribute 'msvcrt'

### ISSUE THREAD

**Issue by mjevans** [streamlink/streamlink#4102]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

I use the archlinux package (streamlink-git) which pulls from the master / main branch on github.  By default the build script runs the unit tests too.

It looks like test_open_windows() is generating an AttributeError because of msvcrt, which only exists for Micorosft Windows platforms.

Example of working
https://github.com/streamlink/streamlink/blob/24c59a23103922977991acc28741a323d8efa7a1/tests/utils/test_named_pipe.py#L119

BUG
https://github.com/streamlink/streamlink/blob/e152c539ebcd64605cab01fe1bc18db86d98b269/tests/test_output.py#L77

Though it would be more future proof if is_Nix or similar existed rather than just is_win32 vs not is_win32.

### Debug log

```text
test_close_before_open (tests.utils.test_named_pipe.TestNamedPipeWindows) ... skipped 'test only applicable on Windows'
test_create (tests.utils.test_named_pipe.TestNamedPipeWindows) ... skipped 'test only applicable on Windows'
test_export (tests.utils.test_named_pipe.TestNamedPipeWindows) ... skipped 'test only applicable on Windows'
test_named_pipe (tests.utils.test_named_pipe.TestNamedPipeWindows) ... skipped 'test only applicable on Windows'
test_parse_json (tests.utils.test_parse.TestUtilsParse) ... ok
test_parse_qsd (tests.utils.test_parse.TestUtilsParse) ... ok
test_parse_xml (tests.utils.test_parse.TestUtilsParse) ... ok
test_parse_xml_entities (tests.utils.test_parse.TestUtilsParse) ... ok
test_parse_xml_entities_fail (tests.utils.test_parse.TestUtilsParse) ... ok
test_parse_xml_fail (tests.utils.test_parse.TestUtilsParse) ... ok
test_parse_xml_ns (tests.utils.test_parse.TestUtilsParse) ... ok
test_parse_xml_ns_ignore (tests.utils.test_parse.TestUtilsParse) ... ok
test_parse_xml_validate (tests.utils.test_parse.TestUtilsParse) ... ok
test_swf_decompress (tests.utils.test_swf.TestUtilsSWF) ... ok
test_hours_minutes_seconds (tests.utils.test_times.TestUtilsTimes) ... ok
test_seconds_to_hhmmss (tests.utils.test_times.TestUtilsTimes) ... ok

======================================================================
ERROR: test_open_windows (tests.test_output.TestFileOutput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/mock.py", line 1334, in patched
    with self.decoration_helper(patched,
  File "/usr/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.9/unittest/mock.py", line 1316, in decoration_helper
    arg = exit_stack.enter_context(patching)
  File "/usr/lib/python3.9/contextlib.py", line 448, in enter_context
    result = _cm_type.__enter__(cm)
  File "/usr/lib/python3.9/unittest/mock.py", line 1405, in __enter__
    original, local = self.get_original()
  File "/usr/lib/python3.9/unittest/mock.py", line 1378, in get_original
    raise AttributeError(
AttributeError: <module 'streamlink_cli.output' from '~/.cache/yay/streamlink-git/src/streamlink/src/streamlink_cli/output.py'> does not have the attribute 'msvcrt'

----------------------------------------------------------------------
Ran 640 tests in 11.437s

FAILED (errors=1, skipped=23)

cd ; git log -n 1  
commit 765f969dfd6348a5d07c442c8980ea674bf6035f (HEAD -> master, origin/master, origin/HEAD)
Author: bastimeyer <mail@bastimeyer.de>
Date:   Thu Oct 14 00:03:01 2021 +0200

    ci.github: switch to codecov-action@v2
```

**Comment by mjevans** [comment]
Is it possible to abort the tests if run with a known unsupported test environment so that it's more obviously a bug there rather than after numerous successful tests?

**Comment by mjevans** [comment]
The archlinux AUR package is fixed, and they also knew how to get around a pytest bug #4108

PYTHONPATH="/absolute/path/of/build/area/" pytest
OR
PYTHONPATH="/absolute/path/of/build/area/" python -m pytest

E.G  PYTHONPATH="$PWD/tmp_install/usr/lib/python$pyver/site-packages" pytest
