### ISSUE TITLE
3.0.0 - The 'pycountry' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by DmitriyFrogo** [streamlink/streamlink#4179]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Streamlink 3.0.0 always starts with an "The 'pycountry' distribution was not found and is required by the application" error.
There's no issues with 2.4.0

### Debug log

```text
COMMAND: streamlink --twitch-disable-ads --twitch-low-latency --retry-streams=3 --retry-max=100 --loglevel debug https://twitch.tv/unclebjorn best

Traceback (most recent call last):
  File "runpy.py", line 197, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files (x86)\Streamlink\bin\streamlink.exe\__main__.py", line 17, in <module>
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 22, in <module>
    import streamlink.logger as logger
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\__init__.py", line 21, in <module>
    from streamlink.api import streams
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\api.py", line 1, in <module>
    from streamlink.session import Streamlink
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\session.py", line 18, in <module>
    from streamlink.utils.l10n import Localization
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\l10n.py", line 4, in <module>
    from pycountry import countries, languages
  File "C:\Program Files (x86)\Streamlink\pkgs\pycountry\__init__.py", line 12, in <module>
    __version__ = pkg_resources.get_distribution("pycountry").version
  File "C:\Program Files (x86)\Streamlink\pkgs\pkg_resources\__init__.py", line 471, in get_distribution
    dist = get_provider(dist)
  File "C:\Program Files (x86)\Streamlink\pkgs\pkg_resources\__init__.py", line 347, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "C:\Program Files (x86)\Streamlink\pkgs\pkg_resources\__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Program Files (x86)\Streamlink\pkgs\pkg_resources\__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycountry' distribution was not found and is required by the application
PROCESS ENDED.
```

**Comment by bastimeyer** [comment]
For some reason, the `pycountry` package does not get picked up in the python environment of the Windows installer, even though the package is installed.
@beardypig Do you have any idea why this could happen?

**Comment by bastimeyer** [comment]
`pycountry` doesn't have wheels published on pypi
https://pypi.org/project/pycountry/20.7.3/#files

which is the reason why it has been added to `pynsist`'s `packages` list instead of `pypi_wheels` in #4175.

The same was already done for the old default dependency `iso639` which `pycountry` replaced, as can be seen in the diff:
https://github.com/streamlink/streamlink/commit/aabd6af71854da81b85f005fadafd3ae11d204b0#diff-24a9b73e1130bf3bed74fa811baeb53c70bf59bc7be512c434d71e93c6c7f808R92

A workaround for this could be building a `pycountry` wheel ourselves and adding it to the Windows installer's wheels list:
https://pynsist.readthedocs.io/en/latest/faq.html#bundling-packages-which-don-t-have-wheels-on-pypi
https://pynsist.readthedocs.io/en/latest/cfgfile.html#cfg-include

**Comment by bastimeyer** [comment]
Reopening for awareness until 3.0.1 has been published (working on it right now)

**Comment by bastimeyer** [comment]
3.0.1 has just been published and should fix the issue.

https://github.com/streamlink/streamlink/releases/tag/3.0.1
https://github.com/streamlink/streamlink/actions/runs/1472192749

I'm closing this thread later today.
