### ISSUE TITLE
streamlink -h is raising TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by mtakeshi1** [streamlink/streamlink#4212]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Hi everyone. 
Just as the title says, the latest version from pip is raising the above error due to non-escaped % in the argparser.py. 

Specifically, in the three lines on the file argparser.py that contains:

`{time:%Y%m%d%H%M%S}`

replacing with

`{time:%%Y%%m%%d%%H%%M%%S}`

should fix the issue.

Thanks for the great work anyway,
takeshi

### Debug log

```text
Traceback (most recent call last):
  File "/home/user/.local/bin/streamlink", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/streamlink_cli/main.py", line 1069, in main
    parser.print_help()
  File "/usr/lib/python3.8/argparse.py", line 2509, in print_help
    self._print_message(self.format_help(), file)
  File "/home/user/.local/lib/python3.8/site-packages/streamlink_cli/argparser.py", line 105, in format_help
    return formatter.format_help()
  File "/usr/lib/python3.8/argparse.py", line 294, in format_help
    help = self._root_section.format_help()
  File "/usr/lib/python3.8/argparse.py", line 225, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.8/argparse.py", line 225, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.8/argparse.py", line 225, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.8/argparse.py", line 225, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.8/argparse.py", line 541, in _format_action
    help_text = self._expand_help(action)
  File "/usr/lib/python3.8/argparse.py", line 636, in _expand_help
    return self._get_help_string(action) % params
TypeError: not enough arguments for format string
```

**Comment by mtakeshi1** [comment]
Thanks!

**Comment by bastimeyer** [comment]
Thanks for reporting. There will be another patch release soon because of that unfortunate mistake.
