### ISSUE TITLE
plugins.twitcasting: Support streams requiring being logged in

### ISSUE THREAD

**Issue by nurupo** [streamlink/streamlink#4281]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Looks like some streams may not provide `fmp4` json key:

```
$ streamlink -o test.ts https://twitcasting.tv/054109 best
[cli][info] Found matching plugin twitcasting for URL https://twitcasting.tv/054109
error: Unable to validate JSON: Key 'fmp4' not found in {'movie': {'id': 716069636, 'live': True}, 'hls': {'host': 'twitcasting.tv', 'proto': 'https', 'source': True}}
```

I have tested 10 other streamers and they all had `fmp4` and `llfmp4` keys, so this issue might be a bit hard to reproduce. It seems like this streamer was streaming from PC instead of a mobile device, if that is of any help.

Here is a stacktrace of `--json`:

```
$ streamlink --json https://twitcasting.tv/054109 best         
Traceback (most recent call last):
  File ".pyenv/lib/python3.9/site-packages/streamlink/plugin/api/validate.py", line 537, in validate
    return validate(self.schema, value)
  File "/usr/lib/python3.9/functools.py", line 877, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File ".pyenv/lib/python3.9/site-packages/streamlink/plugin/api/validate.py", line 380, in validate_all
    value = validate(schema, value)
  File "/usr/lib/python3.9/functools.py", line 877, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File ".pyenv/lib/python3.9/site-packages/streamlink/plugin/api/validate.py", line 417, in validate_dict
    raise ValueError("Key '{0}' not found in {1!r}".format(key, value))
ValueError: Key 'fmp4' not found in {'movie': {'id': 716069636, 'live': True}, 'hls': {'host': 'twitcasting.tv', 'proto': 'https', 'source': True}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".pyenv/lib/python3.9/site-packages/streamlink_cli/main.py", line 565, in handle_url
    streams = fetch_streams(plugin)
  File ".pyenv/lib/python3.9/site-packages/streamlink_cli/main.py", line 459, in fetch_streams
    return plugin.streams(stream_types=args.stream_types,
  File ".pyenv/lib/python3.9/site-packages/streamlink/plugin/plugin.py", line 336, in streams
    ostreams = self._get_streams()
  File ".pyenv/lib/python3.9/site-packages/streamlink/plugins/twitcasting.py", line 51, in _get_streams
    stream_info = self._get_stream_info()
  File ".pyenv/lib/python3.9/site-packages/streamlink/plugins/twitcasting.py", line 86, in _get_stream_info
    return self.session.http.json(res, schema=self._STREAM_INFO_SCHEMA)
  File ".pyenv/lib/python3.9/site-packages/streamlink/plugin/api/http_session.py", line 135, in json
    return parse_json(res.text, *args, **kwargs)
  File ".pyenv/lib/python3.9/site-packages/streamlink/utils/parse.py", line 38, in parse_json
    return _parse(json.loads, data, name, exception, schema, *args, **kwargs)
  File ".pyenv/lib/python3.9/site-packages/streamlink/utils/parse.py", line 21, in _parse
    parsed = schema.validate(parsed, name=name, exception=exception)
  File ".pyenv/lib/python3.9/site-packages/streamlink/plugin/api/validate.py", line 539, in validate
    raise exception("Unable to validate {0}: {1}".format(name, err))
streamlink.exceptions.PluginError: Unable to validate JSON: Key 'fmp4' not found in {'movie': {'id': 716069636, 'live': True}, 'hls': {'host': 'twitcasting.tv', 'proto': 'https', 'source': True}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "streamlink", line 8, in <module>
    sys.exit(main())
  File ".pyenv/lib/python3.9/site-packages/streamlink_cli/main.py", line 1056, in main
    handle_url()
  File ".pyenv/lib/python3.9/site-packages/streamlink_cli/main.py", line 569, in handle_url
    console.exit(err)
  File ".pyenv/lib/python3.9/site-packages/streamlink_cli/console.py", line 87, in exit
    self.msg_json(error=msg)
  File ".pyenv/lib/python3.9/site-packages/streamlink_cli/console.py", line 79, in msg_json
    msg = dumps(out, cls=JSONEncoder, indent=2)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.9/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.9/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File ".pyenv/lib/python3.9/site-packages/streamlink_cli/utils/__init__.py", line 25, in default
    return json.JSONEncoder.default(self, obj)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PluginError is not JSON serializable
```

### Debug log

```text
$ streamlink --loglevel debug -o test.ts https://twitcasting.tv/054109 best
[cli][debug] OS:         Linux-5.10.0-8-amd64-x86_64-with-glibc2.31
[cli][debug] Python:     3.9.2
[cli][debug] Streamlink: 3.0.3
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.3)
[cli][debug] Arguments:
[cli][debug]  url=https://twitcasting.tv/054109
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --output=test.ts
[cli][info] Found matching plugin twitcasting for URL https://twitcasting.tv/054109
error: Unable to validate JSON: Key 'fmp4' not found in {'movie': {'id': 716069636, 'live': True}, 'hls': {'host': 'twitcasting.tv', 'proto': 'https', 'source': True}}
```
```

**Comment by nurupo** [comment]
>I have tested 10 other streamers and they all had fmp4 and llfmp4 keys, so this issue might be a bit hard to reproduce.

In the last 3 days this has been happening all the time with the steamer from my debug log, so at least that is a consistent way to reproduce the failure.

**Comment by nurupo** [comment]
Looks like this stream requires you to be logged in.

I didn't occur to me to check in Incognito before.

https://twitcasting.tv/streamserver.php?target=054109&mode=client contains `llfmp4` when I'm logged in

```
{
  "movie": {
    "id": 716611113,
    "live": true
  },
  "hls": {
    "host": "twitcasting.tv",
    "proto": "https",
    "source": true
  },
  "fmp4": {
    "host": "202-218-143-75.twitcasting.tv",
    "proto": "wss",
    "source": true,
    "mobilesource": false
  },
  "llfmp4": {
    "streams": {
      "main": "wss://202-218-143-75.twitcasting.tv/tc.edge/v1/streams/716611113.336.96/fmp4",
      "base": "wss://202-218-143-75.twitcasting.tv/tc.edge/v1/streams/716611113.240.64/fmp4"
    }
  }
}
```

but doesn't when I'm not:

```
{
  "movie": {
    "id": 716611113,
    "live": true
  },
  "hls": {
    "host": "twitcasting.tv",
    "proto": "https",
    "source": true
  }
}
```

and there is this obvious message in Incognito:

![must-be-logged-in](https://user-images.githubusercontent.com/1855294/148772681-a0c6f3e6-c826-4cea-92ec-9b87cd4bafe8.png)

**Comment by nurupo** [comment]
Changed the issue title to better reflect what is happening.

**Comment by nurupo** [comment]
For anyone stumbling across this, I have worked around this by dumping the website cookies into a config file with a bunch of:

```
http-cookie=key=value
http-cookie=key=value
http-cookie=key=value
```

and then passing that to streamlink with `--config /path/config`.
