### ISSUE TITLE
PreBuilt Binaries not working on Windows

### ISSUE THREAD

**Issue by ryankashi** [streamlink/streamlink#4402]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

The prebiult binaries are not running correctly on windows 10. This was tested using Python versions 3.7 and 3.9 using the prebuilt amd64 architecture.

Prebuilt binaries are working properly with streamlink version 2.1.2. Other versions in between 3.2.0 and 2.1.2 are untested.

### Debug log

```text
PS C:\Users\kashi\Desktop\tenami\streamlink-portable-3.2.0-py3.7.9-amd64\streamlink> .\streamlink https://www.crunchyroll.com/attack-on-titan/episode-84-night-of-the-end-823862 --stream-url --loglevel debug
Traceback (most recent call last):
  File "C:\Users\kashi\Desktop\tenami\streamlink-portable-3.2.0-py3.7.9-amd64\streamlink\\streamlink-script.py", line 11, in <module>
    from streamlink_cli.main import main
  File "C:\Users\kashi\Desktop\tenami\streamlink-portable-3.2.0-py3.7.9-amd64\streamlink\packages\streamlink_cli\main.py", line 27, in <module>
    from streamlink.stream.stream import Stream, StreamIO
  File "C:\Users\kashi\Desktop\tenami\streamlink-portable-3.2.0-py3.7.9-amd64\streamlink\packages\streamlink\stream\__init__.py", line 2, in <module>
    from streamlink.stream.hls import HLSStream
  File "C:\Users\kashi\Desktop\tenami\streamlink-portable-3.2.0-py3.7.9-amd64\streamlink\packages\streamlink\stream\hls.py", line 11, in <module>
    from Crypto.Cipher import AES
  File "C:\Users\kashi\Desktop\tenami\streamlink-portable-3.2.0-py3.7.9-amd64\streamlink\packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Users\kashi\Desktop\tenami\streamlink-portable-3.2.0-py3.7.9-amd64\streamlink\packages\Crypto\Cipher\_mode_ecb.py", line 47, in <module>
    """
  File "C:\Users\kashi\Desktop\tenami\streamlink-portable-3.2.0-py3.7.9-amd64\streamlink\packages\Crypto\Util\_raw_api.py", line 309, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Not found '_raw_ecb.cp37-win_amd64.pyd', Cannot load '_raw_ecb.pyd': [WinError 193] %1 is not a valid Win32 application
PS C:\Users\kashi\Desktop\tenami\streamlink-portable-3.2.0-py3.7.9-amd64\streamlink>
```

**Comment by gravyboat** [comment]
I can't duplicate this on a Windows 10 machine running the latest version:
```
streamlink https://www.crunchyroll.com/attack-on-titan/episode-84-night-of-the-end-823862 --stream-url --loglevel debug
https://pl.crunchyroll.com/evs2/8b68679ae75e13a73d72360e610ab0a1/assets/3ba57449677384ec7ae7ee61b8988a7f_4389829.mp4/index-v1-a1.m3u8?Expires=1647826999&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMi84YjY4Njc5YWU3NWUxM2E3M2Q3MjM2MGU2MTBhYjBhMS9hc3NldHMvM2JhNTc0NDk2NzczODRlYzdhZTdlZTYxYjg5ODhhN2ZfKi5tM3U4PyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NDc4MjY5OTl9fX1dfQ__&Signature=ASSq0dGhXG3gG9In3aDeOfYqFu6R6tivp8RWIDDIbwbg2PdzNOhA5VXshnV5I6W3mtHm652v~bcpXLmGTZgw54iDsS5CJEilJbQWxBNKGazq0~UQuSoCENAXSq0RSPtvR3Sz3HqAUhnerZrQ1X0mO8A5A0i0wo7WAR5kpHrejC-FYQeZu0FLe860DaNjeFG4pQUscXR01H273Vcz~LWkgWi4JSq0vXTYlOI9p7KSOCNNj5gA8fHcKc78Kl68a3Z1i14jOqGynvq46pXAFWAyZprv59KK8Vd0MLz2qs8OXgFHnuZYZiyiaUJ-yHzVSbPXSV-tNZ3OSCD7u1wPE4tlBw__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=ll-prod
```
and
```
streamlink https://www.crunchyroll.com/attack-on-titan/episode-84-night-of-the-end-823862 --loglevel debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.9.10
[cli][debug] Streamlink: 3.2.0
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.2.3)
[cli][debug] Arguments:
[cli][debug]  url=https://www.crunchyroll.com/attack-on-titan/episode-84-night-of-the-end-823862
[cli][debug]  --loglevel=debug
```

If you're upgrading make sure you fully uninstall the old version before install the new version, you may need to manually remove the directory after uninstalling.

**Comment by bastimeyer** [comment]
> streamlink-portable

https://github.com/beardypig/streamlink-portable
