### ISSUE TITLE
Read timeout on all attempts when downloading from Twitch

### ISSUE THREAD

**Issue by Razunter** [streamlink/streamlink#446]
Trying to download stream from Twitch, getting "read timeout" every time at about 5-50mb.
Can watch on Twitch without issues.

Stream url: https://www.twitch.tv/ognglobal/v/115348644
Quality: best

```
d:\Soft\Streamlink\bin>streamlink -f -o "H:\temp\[ENG] OVERWACH APEX S2 ENERGIZED BY HOT6.mp4" https://www.twitch.tv/ognglobal/v/115348644 best --hls-segment-threads 3
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/ognglobal/v/115348644
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Opening stream: source (hls)
[download][..2 ENERGIZED BY HOT6.mp4] Written 7.5 MB (6s @ 1.1 MB/s)                                                   Exception in thread Thread-1:
Traceback (most recent call last):
  File "d:\Soft\Streamlink\pkgs\requests\packages\urllib3\response.py", line 298, in _error_catcher
    yield
  File "d:\Soft\Streamlink\pkgs\requests\packages\urllib3\response.py", line 380, in read
    data = self._fp.read(amt)
  File "http\client.py", line 448, in read
  File "http\client.py", line 488, in readinto
  File "socket.py", line 575, in readinto
  File "ssl.py", line 929, in recv_into
  File "ssl.py", line 791, in read
  File "ssl.py", line 575, in read
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Soft\Streamlink\pkgs\requests\models.py", line 703, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "d:\Soft\Streamlink\pkgs\requests\packages\urllib3\response.py", line 432, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "d:\Soft\Streamlink\pkgs\requests\packages\urllib3\response.py", line 397, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "contextlib.py", line 77, in __exit__
  File "d:\Soft\Streamlink\pkgs\requests\packages\urllib3\response.py", line 303, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='vod040-ttvnw.akamaized.net', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "d:\Soft\Streamlink\pkgs\streamlink\stream\segmented.py", line 160, in run
    self.write(segment, result)
  File "d:\Soft\Streamlink\pkgs\streamlink\stream\hls.py", line 116, in write
    for chunk in res.iter_content(chunk_size):
  File "d:\Soft\Streamlink\pkgs\requests\models.py", line 710, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='vod040-ttvnw.akamaized.net', port=443): Read timed out.

[cli][error] Error when reading from stream: Read timeout
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by beardypig** [comment]
Working on this right now ...

**Comment by gravyboat** [comment]
Closing since #522 is merged, can you please give the nightly a shot?

**Comment by Razunter** [comment]
Tried, but getting unrelated error:
> File "d:\Soft\Streamlink\pkgs\streamlink\utils\l10n.py", line 2, in <module>
>     from iso639 import languages
> ImportError: No module named 'iso639'
