### ISSUE TITLE
Crunchyroll authentication broken

### ISSUE THREAD

**Issue by Aspenpaw** [streamlink/streamlink#4549]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

I notice this is a fairly common issue with streamlink. Yet again, a crunchyroll stream is failing to open on my system due to an "Unauthenticated Request" error. I assume Crunchyroll has changed their security settings. 

### Debug log

```text
Microsoft Windows [Version 10.0.22000.675]
(c) Microsoft Corporation. All rights reserved.

C:\Users\alexa>streamlink https://www.crunchyroll.com/en-gb/rezero-starting-life-in-another-world-/rezero-starting-life-in-another-world-the-end-of-the-beginning-and-the-beginning-of-the-end-part-1-702401
[cli][info] Found matching plugin crunchyroll for URL https://www.crunchyroll.com/en-gb/rezero-starting-life-in-another-world-/rezero-starting-life-in-another-world-the-end-of-the-beginning-and-the-beginning-of-the-end-part-1-702401
Traceback (most recent call last):
  File "C:\Users\alexa\AppData\Local\Streamlink\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\alexa\AppData\Local\Streamlink\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\alexa\AppData\Local\Streamlink\bin\streamlink.exe\__main__.py", line 18, in <module>
  File "C:\Users\alexa\AppData\Local\Streamlink\pkgs\streamlink_cli\main.py", line 1064, in main
    handle_url()
  File "C:\Users\alexa\AppData\Local\Streamlink\pkgs\streamlink_cli\main.py", line 573, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Users\alexa\AppData\Local\Streamlink\pkgs\streamlink_cli\main.py", line 467, in fetch_streams
    return plugin.streams(stream_types=args.stream_types,
  File "C:\Users\alexa\AppData\Local\Streamlink\pkgs\streamlink\plugin\plugin.py", line 351, in streams
    ostreams = self._get_streams()
  File "C:\Users\alexa\AppData\Local\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 308, in _get_streams
    api = self._create_api()
  File "C:\Users\alexa\AppData\Local\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 373, in _create_api
    api.start_session()
  File "C:\Users\alexa\AppData\Local\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 191, in start_session
    self.session_id = self._api_call("start_session", params, schema=_session_schema)
  File "C:\Users\alexa\AppData\Local\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 167, in _api_call
    raise CrunchyrollAPIError(err_msg, err_code)
streamlink.plugins.crunchyroll.CrunchyrollAPIError: Unauthenticated request

C:\Users\alexa>
```

**Comment by Aspenpaw** [comment]
https://github.com/streamlink/streamlink/issues/4453#issuecomment-1114520315
This comment fixed it for me. (I discovered this after posting the issue). Perhaps these changes should be deployed in crunchyroll.py in the main software package?

**Comment by mkbloke** [comment]
As specified in the plugin issue template, please provide full debug log output by using `-l debug` when submitting future plugin issues.

The crunchyroll plugin was updated in #4510, so Streamlink 4.0.1 does not contain the updated plugin code.

If you read more of #4453 you'll discover the pull request was mentioned there.
