### ISSUE TITLE
ValueError: Incorrect AES key length (17 bytes)

### ISSUE THREAD

**Issue by Inferi0r** [streamlink/streamlink#4554]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Trying to extract the public live stream from https://www.tutele.nl/online.php?a=3102 and using http headers from both the **.m3u8** as the .**videokey.php** which results in using:

`streamlink --http-no-ssl-verify --http-header "Origin=" --http-header "cookie=" --http-header "referer=" --http-header "user-agent=" --http-header "xauth="  https://ed7.zorrohd.nl/live/ST859f6f0c73b02aa.m3u8 best`

I also tried with --hls-segment-key-uri and leaving --http-no-ssl-verify out, but did not make a difference.

However I am receiving a 'ValueError: Incorrect AES key length (17 bytes)' error.
Please refer to the debug log for the command I used, I have replaced my IP in the referer with XX.XXX.XX.XXX.

### Debug log

```text
[cli][debug] OS:         macOS 12.4
[cli][debug] Python:     3.10.4
[cli][debug] Streamlink: 4.0.1
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.3.2)
[cli][debug] Arguments:
[cli][debug]  url=https://ed7.zorrohd.nl/live/ST859f6f0c73b02aa.m3u8
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --http-header=[('Origin', 'https://www.tutele.nl'), ('cookie', 'HstCfa4340070=1653849799706; HstCmu4340070=1653849799706; HstCnv4340070=1; PHPSESSID=447qktvo1rkfkd9lk37hba70q6; xauth_token=5jnX9%2BoBu6TjHHZNOB5FK4yfN0o1zNR%2BcvP4YNmItKGvvJJAFxpaBsDaO0z51F3Uqc7iOKwuwobmfNe3epleNGhBuJuC1r9x5znS4YOaxpaqq7Yd33lBWZ547EnpcLv3JkyHZLviCQmzj1tlm4bT7wzDQeJ2%2BvmOD19i4UFAK4rcdSyP1GWf%2B14i0qeMjW7VNKjBA9LlU6wLX%2B1FtePwLVEygY7sbIYREFmwsqxUCCsdprad9kfq2m4xKmksggccCp9FyBgXSUXgEj1xUPaHGZPH9VGc5%2B7qnGdmZJx6rpxWZb3IzSNv25SrzUt2LShxB%2FxLEJPxWEKvuxRnlzRyhIhN40PhCbgkjGYxKs9fzEiF0bDrvUwX1BtbmUsVbK0O; HstCla4340070=1653854608144; HstPn4340070=10; HstPt4340070=10; HstCns4340070=5'), ('referer', 'https://www.tutele.nl/embed.php?&a=3102&s=447qktvo1rkfkd9lk37hba70q6&ip=XX.XXX.XX.XXX&useragent=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_15_7%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F101.0.4951.64+Safari%2F537.36&referer='), ('user-agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36'), ('xauth', '5jnX9+oBu6TjHHZNOB5FK4yfN0o1zNR+cvP4YNmItKGvvJJAFxpaBsDaO0z51F3Uqc7iOKwuwobmfNe3epleNGhBuJuC1r9x5znS4YOaxpaqq7Yd33lBWZ547EnpcLv3JkyHZLviCQmzj1tlm4bT7wzDQeJ2+vmOD19i4UFAK4rcdSyP1GWf+14i0qeMjW7VNKjBA9LlU6wLX+1FtePwLVEygY7sbIYREFmwsqxUCCsdprad9kfq2m4xKmksggccCp9FyBgXSUXgEj1xUPaHGZPH9VGc5+7qnGdmZJx6rpxWZb3IzSNv25SrzUt2LShxB/xLEJPxWEKvuxRnlzRyhIhN40PhCbgkjGYxKs9fzEj9Ecge7v5OU824OfI5v+4I')]
[cli][debug]  --http-no-ssl-verify=True
[cli][info] Found matching plugin hls for URL https://ed7.zorrohd.nl/live/ST859f6f0c73b02aa.m3u8
[plugins.hls][debug] URL=https://ed7.zorrohd.nl/live/ST859f6f0c73b02aa.m3u8; params={}
[utils.l10n][debug] Language code: nl_NL
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[cli][info] Starting player: /Applications/VLC.app/Contents/MacOS/VLC
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] First Sequence: 66; Last Sequence: 80
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 78; End Sequence: None
[stream.hls][debug] Adding segment 78 to queue
[stream.hls][debug] Adding segment 79 to queue
[stream.hls][debug] Adding segment 80 to queue
Exception in thread Thread-HLSStreamWriter:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/streamlink/4.0.1/libexec/lib/python3.10/site-packages/streamlink/stream/segmented.py", line 200, in run
    self.write(segment, result, *data)
  File "/opt/homebrew/Cellar/streamlink/4.0.1/libexec/lib/python3.10/site-packages/streamlink/stream/hls.py", line 196, in write
    return self._write(sequence, *args, **kwargs)
  File "/opt/homebrew/Cellar/streamlink/4.0.1/libexec/lib/python3.10/site-packages/streamlink/stream/hls.py", line 221, in _write
    decryptor = self.create_decryptor(sequence.segment.key, sequence.num)
  File "/opt/homebrew/Cellar/streamlink/4.0.1/libexec/lib/python3.10/site-packages/streamlink/stream/hls.py", line 120, in create_decryptor
    return AES.new(self.key_data, AES.MODE_CBC, iv)
  File "/opt/homebrew/Cellar/streamlink/4.0.1/libexec/lib/python3.10/site-packages/Crypto/Cipher/AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/opt/homebrew/Cellar/streamlink/4.0.1/libexec/lib/python3.10/site-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/opt/homebrew/Cellar/streamlink/4.0.1/libexec/lib/python3.10/site-packages/Crypto/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/opt/homebrew/Cellar/streamlink/4.0.1/libexec/lib/python3.10/site-packages/Crypto/Cipher/AES.py", line 93, in _create_base_cipher
    raise ValueError("Incorrect AES key length (%d bytes)" % len(key))
ValueError: Incorrect AES key length (17 bytes)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 81 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 82 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 83 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 84 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 85 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 86 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 87 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 88 to queue
[stream.hls][debug] Adding segment 89 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 90 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 91 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 92 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 93 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 94 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 95 to queue
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][error] Try 1/1: Could not open stream <HLSStream('https://ed7.zorrohd.nl/live/ST859f6f0c73b02aa.m3u8', None)> (Failed to read data from stream: Read timeout)
error: Could not open stream <HLSStream('https://ed7.zorrohd.nl/live/ST859f6f0c73b02aa.m3u8', None)>, tried 1 times, exiting
[cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment]
Not a bug. The server is returning an invalid decryption key response. You can check it yourself and see that it always returns 17 bytes instead of 16.

It looks like the decryption key response includes a new line character `0x0a` at the end. Example with curl, copied from my web browser's dev tools (and adding `--insecure` due to TLS issues):
```
$ curl ... | xxd
00000000: a12f 1ec7 bb9a 441f fd9a 9289 0e94 e7b4  ./....D.........
00000010: 0a
```

The player on their site is using a custom HLS implementation that deviates from the HLS specification. Key files of AES-128 encrypted segments must be 16 bytes:
https://datatracker.ietf.org/doc/html/rfc8216#section-5.1

Streamlink allows you to override the key URI via [`--hls-segment-key-uri`](https://streamlink.github.io/cli.html#cmdoption-hls-segment-key-uri), which supports the usual protocols, like `file://`, so you can download the key, modify and correct it. Since the server is returning dynamic keys which seem to expire fast, you'll probably have to write a custom plugin for this.
