### ISSUE TITLE
Every attempted url produces the same generic error

### ISSUE THREAD

**Issue by dsteplight** [streamlink/streamlink#458]
streamlink twitch.tv/lirik best                                                                                                                       [17:01:50]
[cli][info] Found matching plugin twitch for URL twitch.tv/lirik
Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 11, in <module>
    load_entry_point('streamlink==0.2.0', 'console_scripts', 'streamlink')()
  File "/Library/Python/2.7/site-packages/streamlink_cli/main.py", line 899, in main
    handle_url()
  File "/Library/Python/2.7/site-packages/streamlink_cli/main.py", line 479, in handle_url
    streams = fetch_streams(plugin)
  File "/Library/Python/2.7/site-packages/streamlink_cli/main.py", line 392, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/Library/Python/2.7/site-packages/streamlink/plugin/plugin.py", line 316, in get_streams
    return self.streams(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/streamlink/plugin/plugin.py", line 230, in streams
    ostreams = self._get_streams()
  File "/Library/Python/2.7/site-packages/streamlink/plugins/twitch.py", line 532, in _get_streams
    return self._get_hls_streams("live")
  File "/Library/Python/2.7/site-packages/streamlink/plugins/twitch.py", line 496, in _get_hls_streams
    streams = HLSStream.parse_variant_playlist(self.session, url)
  File "/Library/Python/2.7/site-packages/streamlink/stream/hls.py", line 282, in parse_variant_playlist
    res = session_.http.get(url, exception=IOError, **request_params)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/streamlink/plugin/api/http_session.py", line 156, in request
    *args, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
    conn.connect()
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connection.py", line 330, in connect
    cert = self.sock.getpeercert()
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
    'subjectAltName': get_subj_alt_name(x509)
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 166, in get_subj_alt_name
    cert = _Certificate(openssl_backend, peer_cert._x509)
AttributeError: 'X509' object has no attribute '_x509'

**Comment by stevek123** [comment]
I think this will help: https://github.com/kennethreitz/requests/issues/3701 

It's probably using an old version

**Comment by dsteplight** [comment]
@stevek123  Thank you. That solved to problem.

The steps required on the link provided where to do the following. Now I see my stream in VLC.
sudo pip uninstall pyopenssl cryptography requests
sudo pip install requests
