### ISSUE TITLE
I can't open a video on youtube!!!

### ISSUE THREAD

**Issue by ringtvt** [streamlink/streamlink#4896]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

I can't open a video on youtube
I used: 
C:\Program Files (x86)\Streamlink\bin>Streamlink  "https://www.youtube.com/watch?v=SWwXFcsgrp4"
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files (x86)\Streamlink\bin\streamlink.exe\__main__.py", line 17, in <module>
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 17, in <module>
    import streamlink.logger as logger
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\__init__.py", line 19, in <module>
    from streamlink.api import streams
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\api.py", line 1, in <module>
    from streamlink.session import Streamlink
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\session.py", line 16, in <module>
    from streamlink.plugin.api.http_session import HTTPSession
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\api\__init__.py", line 1, in <module>
    from streamlink.plugin.api.http_session import HTTPSession
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\api\http_session.py", line 13, in <module>
    from streamlink.utils.parse import parse_json, parse_xml
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\__init__.py", line 5, in <module>
    from streamlink.utils.parse import parse_html, parse_json, parse_qsd, parse_xml
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\parse.py", line 5, in <module>
    from lxml.etree import HTML, XML
ModuleNotFoundError: No module named 'lxml.etree'

C:\Program Files (x86)\Streamlink\bin>pause
Press any key to continue . . .

### Debug log

```text
C:\Program Files (x86)\Streamlink\bin>Streamlink  "https://www.youtube.com/watch?v=SWwXFcsgrp4"
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files (x86)\Streamlink\bin\streamlink.exe\__main__.py", line 17, in <module>
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 17, in <module>
    import streamlink.logger as logger
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\__init__.py", line 19, in <module>
    from streamlink.api import streams
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\api.py", line 1, in <module>
    from streamlink.session import Streamlink
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\session.py", line 16, in <module>
    from streamlink.plugin.api.http_session import HTTPSession
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\api\__init__.py", line 1, in <module>
    from streamlink.plugin.api.http_session import HTTPSession
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\api\http_session.py", line 13, in <module>
    from streamlink.utils.parse import parse_json, parse_xml
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\__init__.py", line 5, in <module>
    from streamlink.utils.parse import parse_html, parse_json, parse_qsd, parse_xml
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\parse.py", line 5, in <module>
    from lxml.etree import HTML, XML
ModuleNotFoundError: No module named 'lxml.etree'

C:\Program Files (x86)\Streamlink\bin>pause
Press any key to continue . . .
```

**Comment by bastimeyer** [comment]
> ModuleNotFoundError: No module named 'lxml.etree'

Not a plugin issue. Fix your broken Streamlink install.
https://streamlink.github.io/install.html

----

Btw, this video is also not supported by the YouTube plugin

```
$ streamlink https://www.youtube.com/watch?v=SWwXFcsgrp4
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=SWwXFcsgrp4
error: This plugin does not support protected videos, try youtube-dl instead
```
