### ISSUE TITLE
When I try to launch a twitch stream using the latest Nightly i get a error

### ISSUE THREAD

**Issue by thinkpad4** [streamlink/streamlink#490]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first!*

*Feel free to use the following template. Be as detailed as possible.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description
When I try to launch a twitch stream using the latest Nightly I get this
Traceback (most recent call last):
  File "d:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 12, in
 <module>
    main()
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 935
, in main
    handle_url()
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 480
, in handle_url
    streams = fetch_streams(plugin)
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 392
, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", lin
e 321, in get_streams
    return self.streams(*args, **kwargs)
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", lin
e 230, in streams
    ostreams = self._get_streams()
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\twitch.py", li
ne 554, in _get_streams
    return self._get_hls_streams("live")
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\twitch.py", li
ne 518, in _get_hls_streams
    streams = HLSStream.parse_variant_playlist(self.session, url)
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 3
06, in parse_variant_playlist
    locale = session_.localization
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink\session.py", line 473,
 in localization
    return Localization(self.get_option("locale"))
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\l10n.py", line 1
8, in __init__
    self.language_code = language_code
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\l10n.py", line 3
8, in language_code
    self.language = self.get_language(parts[0])
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\l10n.py", line 6
1, in get_language
    return languages.get(alpha2=_language)
  File "d:\Program Files (x86)\Streamlink\pkgs\iso639\iso639.py", line 265, in g
et
    return getattr(self, key)[value]
  File "d:\Program Files (x86)\Streamlink\pkgs\iso639\iso639.py", line 132, in _
_getattr__
    'alpha2': self.part1,
  File "d:\Program Files (x86)\Streamlink\pkgs\iso639\iso639.py", line 105, in _
_get__
    val = self.f(instance)
  File "d:\Program Files (x86)\Streamlink\pkgs\iso639\iso639.py", line 198, in p
art1
    return dict((x.part1, x) for x in self.languages if x.part1)
  File "d:\Program Files (x86)\Streamlink\pkgs\iso639\iso639.py", line 105, in _
_get__
    val = self.f(instance)
  File "d:\Program Files (x86)\Streamlink\pkgs\iso639\iso639.py", line 174, in l
anguages
    l, i, m, p5, p2, p1 = _fabtabular()
  File "d:\Program Files (x86)\Streamlink\pkgs\iso639\iso639.py", line 20, in _f
abtabular
    from pkg_resources import resource_filename
ImportError: No module named 'pkg_resources'

### Expected / Actual behavior

...

### Reproduction steps / Stream URLs to test
streamlink twitch.tv/crream best

even offline it should show: error: No streams found on this URL: twitch.tv/crream

### Environment details (operating system, python version, etc.)
Windows 7 64bit, latest nightly
...

### Comments, logs, screenshots, etc.

...

**Comment by agentqwe** [comment]
win10x64 err too

**Comment by gravyboat** [comment]
I'm going to close this since #493 is merged, can you give the nightly a shot?
