### ISSUE TITLE
Can't stream from IBM video with a RaspberryPi (Raspbian)

### ISSUE THREAD

**Issue by DarrCoh** [streamlink/streamlink#4926]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Hi

First time reporting a bug on GitHub, sorry if I'm not doing things correctly this time.

Trying to stream from a RaspberryPi-3B with VLC from IBM live video.

I put the log in the appropriate text-box.

Thanks !

### Debug log

```text
dacohen@raspberrypi:~/ISS-Viewer $ streamlink https://video.ibm.com/channel/live-iss-stream best
[cli][info] Found matching plugin ustreamtv for URL https://video.ibm.com/channel/live-iss-stream
Exception in thread Thread-UStreamTVWsClient-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/streamlink/plugin/api/websocket.py", line 107, in run
    self.ws.run_forever(**self._ws_rundata)
TypeError: run_forever() got an unexpected keyword argument 'ping_payload'
[plugins.ustreamtv][error] Waiting for stream data timed out.
error: No playable streams found on this URL: https://video.ibm.com/channel/live-iss-stream
```

**Comment by bastimeyer** [comment]
This is not a debug log. **Post the full debug log**, as requested by the template.
https://streamlink.github.io/cli.html#cmdoption-loglevel

> TypeError: run_forever() got an unexpected keyword argument 'ping_payload'

**How did you install Streamlink?** This looks like you're using an old/incorrect `websocket-client` python dendency which is not supported by Streamlink.

----

Streamlink, websocket-client as well as Streamlink's ustreamtv plugin are working fine:
```
$ streamlink 'https://video.ibm.com/channel/live-iss-stream' -l debug
[cli][debug] OS:         Linux-6.0.7-1-git-x86_64-with-glibc2.36
[cli][debug] Python:     3.11.0
[cli][debug] Streamlink: 5.0.1+27.gf969d518
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.4.2
[cli][debug] Arguments:
[cli][debug]  url=https://video.ibm.com/channel/live-iss-stream
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][info] Found matching plugin ustreamtv for URL https://video.ibm.com/channel/live-iss-stream
[stream.ffmpegmux][debug] ffmpeg version n5.1.2 Copyright (c) 2000-2022 the FFmpeg developers
[stream.ffmpegmux][debug]  built with gcc 12.2.0 (GCC)
[stream.ffmpegmux][debug]  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-version3 --enable-vulkan
[stream.ffmpegmux][debug]  libavutil      57. 28.100 / 57. 28.100
[stream.ffmpegmux][debug]  libavcodec     59. 37.100 / 59. 37.100
[stream.ffmpegmux][debug]  libavformat    59. 27.100 / 59. 27.100
[stream.ffmpegmux][debug]  libavdevice    59.  7.100 / 59.  7.100
[stream.ffmpegmux][debug]  libavfilter     8. 44.100 /  8. 44.100
[stream.ffmpegmux][debug]  libswscale      6.  7.100 /  6.  7.100
[stream.ffmpegmux][debug]  libswresample   4.  7.100 /  4.  7.100
[stream.ffmpegmux][debug]  libpostproc    56.  6.100 / 56.  6.100
[plugins.ustreamtv][debug] Connecting to UStream API: media_id=9408562, application=channel, referrer=https://video.ibm.com/channel/live-iss-stream, cluster=live
[plugin.api.websocket][debug] Connecting to: wss://r15985161-1-9408562-channel-ws-live.ums.services.video.ibm.com/1/ustream
[plugins.ustreamtv][debug] Waiting for stream data (for at most 15 seconds)...
[plugins.ustreamtv][debug] Processing 'moduleInfo' - 'cdnConfig'
[plugins.ustreamtv][debug] Processing 'moduleInfo' - 'stream'
Available streams: 252p+a126k (worst), 252p+a177k, 360p+a126k, 360p+a177k, 486p+a126k, 486p+a177k, 720p+a126k, 720p+a177k (best)
```

**Comment by bastimeyer** [comment]
The `ping_payload` keyword was added to `websocket-client`'s `WebSocketApp.run_forever()` method in version `0.59.0`, the last version before its `1.0.0` bump:
https://github.com/websocket-client/websocket-client/commit/cefb07e88302970b134f85142aeec485451ff8e7

Streamlink requires `websocket-client >=1.2.1,<2.0`:
https://github.com/streamlink/streamlink/blob/5.0.1/setup.cfg#L49
