### ISSUE TITLE
ImportError: cannot import name 'StreamProcess' from 'streamlink.stream'

### ISSUE THREAD

**Issue by teskaro** [streamlink/streamlink#4968]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [x] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

After updating from version 2 to the 5.0.1 i got this error when opening trough a cronjob on a raspberry pi. opening with ./script.sh works fine

### Debug log

```text
Traceback (most recent call last):
  File "/usr/bin/streamlink", line 33, in <module>
    sys.exit(load_entry_point('streamlink==2.0.0', 'console_scripts', 'streamlink')())
  File "/usr/bin/streamlink", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/share/streamlink/streamlink_cli/main.py", line 25, in <module>
    from streamlink.stream import StreamProcess
ImportError: cannot import name 'StreamProcess' from 'streamlink.stream' (/home/piche/.local/lib/python3.9/site-packages/streamlink/stream/__init__.py)
```

**Comment by teskaro** [comment]
.sh file:

`streamlink "--twitch-api-header=Authorization=OAuth MYID" --output "/media/piche/Daten/Streams/STREAMER/$(date -d "today" +"%Y-%m-%d-%H-%M").ts" twitch.tv/STREAMER best`

**Comment by bastimeyer** [comment]
> After updating from version 2 to the 5.0.1

> File "/usr/bin/streamlink", line 33, in <module>
>     sys.exit(load_entry_point('streamlink==2.0.0', 'console_scripts', 'streamlink')())

You are not executing 5.0.1, you are executing 2.0.0 from your python system library. You either have two separate installs while mixing up `PYTHONPATH`, or you have a Frankenstein install. Whatever you've done while trying to upgrade, you did a mistake. Completely uninstall all versions of Streamlink you have installed and install it again. Preferrable in a clean virtual environment, as explained in the docs. Otherwise, use the available AppImages.

https://streamlink.github.io/install.html

I will be releasing 5.1.0 in a couple of minutes though, and new AppImages will be available shortly after.
