### ISSUE TITLE
Cannot run recent Streamlink in Python 3.11

### ISSUE THREAD

**Issue by pboettcher** [streamlink/streamlink#5032]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Unfortunately I cannot start streamlink after updating it with pip3.
PIP reported that all the dependencies are met, but when I am trying to launch streamlink I get an error.

```
[root@localhost bin]# ./streamlink
Traceback (most recent call last):
  File "/usr/local/bin/./streamlink", line 5, in <module>
    from streamlink_cli.main import main
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlink_cli/main.py", line 17, in <module>
    import streamlink.logger as logger
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlink/__init__.py", line 19, in <module>
    from streamlink.api import streams
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlink/api.py", line 1, in <module>
    from streamlink.session import Streamlink
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlink/session.py", line 16, in <module>
    from streamlink.plugin.api.http_session import HTTPSession
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlink/plugin/api/__init__.py", line 1, in <module>
    from streamlink.plugin.api.http_session import HTTPSession
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlink/plugin/api/http_session.py", line 13, in <module>
    from streamlink.utils.parse import parse_json, parse_xml
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlink/utils/__init__.py", line 5, in <module>
    from streamlink.utils.parse import parse_html, parse_json, parse_qsd, parse_xml
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlink/utils/parse.py", line 5, in <module>
    from lxml.etree import HTML, XML
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/lxml/etree.pyx", line 1, in init lxml.etree
ValueError: builtins.type size changed, may indicate binary incompatibility. Expected 904 from C header, got 896 from PyObject
```

Trying to investigate this issue I forcedly launched Python 3.11, executed lines from the startup script line-by-line, and got the same error:

```
[root@localhost ~]# python3.11
Python 3.11.0a4 (main, Aug 19 2022, 10:37:08) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> import sys
>>> from streamlink_cli.main import main
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/streamlink_cli/main.py", line 17, in <module>
    import streamlink.logger as logger
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlink/__init__.py", line 19, in <module>
    from streamlink.api import streams
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlink/api.py", line 1, in <module>
    from streamlink.session import Streamlink
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlink/session.py", line 16, in <module>
    from streamlink.plugin.api.http_session import HTTPSession
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlink/plugin/api/__init__.py", line 1, in <module>
    from streamlink.plugin.api.http_session import HTTPSession
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlink/plugin/api/http_session.py", line 13, in <module>
    from streamlink.utils.parse import parse_json, parse_xml
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlink/utils/__init__.py", line 5, in <module>
    from streamlink.utils.parse import parse_html, parse_json, parse_qsd, parse_xml
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlink/utils/parse.py", line 5, in <module>
    from lxml.etree import HTML, XML
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/lxml/etree.pyx", line 1, in init lxml.etree
ValueError: builtins.type size changed, may indicate binary incompatibility. Expected 904 from C header, got 896 from PyObject
```

### Debug log

```text
[root@localhost bin]# ./streamlink
Traceback (most recent call last):
  File "/usr/local/bin/./streamlink", line 5, in <module>
    from streamlink_cli.main import main
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlink_cli/main.py", line 17, in <module>
    import streamlink.logger as logger
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlink/__init__.py", line 19, in <module>
    from streamlink.api import streams
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlink/api.py", line 1, in <module>
    from streamlink.session import Streamlink
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlink/session.py", line 16, in <module>
    from streamlink.plugin.api.http_session import HTTPSession
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlink/plugin/api/__init__.py", line 1, in <module>
    from streamlink.plugin.api.http_session import HTTPSession
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlink/plugin/api/http_session.py", line 13, in <module>
    from streamlink.utils.parse import parse_json, parse_xml
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlink/utils/__init__.py", line 5, in <module>
    from streamlink.utils.parse import parse_html, parse_json, parse_qsd, parse_xml
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlink/utils/parse.py", line 5, in <module>
    from lxml.etree import HTML, XML
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/lxml/etree.pyx", line 1, in init lxml.etree
ValueError: builtins.type size changed, may indicate binary incompatibility. Expected 904 from C header, got 896 from PyObject
```

**Comment by bastimeyer** [comment]
Not a Streamlink bug. You have a broken `lxml` install, which you'll need to fix.

> ValueError: builtins.type size changed, may indicate binary incompatibility.

How did you upgrade with pip? The error message suggests that you are trying to run lxml whose Python C extensions were built for a different Python version, which are of course incompatible.

Did you install the pre-built lxml wheels, or did you build lxml yourself? Which OS are you using and which versions of `libxml2` and `libxslt` are installed? These libs are required if you're building lxml from source.

I can't see anything related to your issue on the lxml issue tracker, so you must've done something wrong with your upgrade via pip.
https://bugs.launchpad.net/lxml/+bugs?orderby=-datecreated&start=0

**Comment by bastimeyer** [comment]
No response. Closing...
Also, as said, not a Streamlink issue. Fix your lxml install.

**Comment by pboettcher** [comment]
Sorry for re-opening. libxml2 and libxslt are installed. When I tried to install lxml using pip3,it told me that the package is already up to date.
I installed python 3.11 in CentOS 7 by building it from source: https://stackoverflow.com/questions/73407527/installing-ssl-package-with-pip-requires-ssl-package-to-be-already-installed/73415654#73415654
I "solve" the issue temporarily by specifying python 3.9 in the streamlink script.

**Comment by bastimeyer** [comment]
> it told me

If you're expecting any kind of help (on any issue tracker, online forum, etc.), then post explicit log outputs. This is not useful.

Also, you don't need libxml2 and libxslt when installing the lxml wheel from PyPI via pip, because that wheel does have those dependencies statically linked, assuming there is a wheel available for your platform. If you're building lxml from source, then you'll need those libs so it can build the wheel locally. Since you're on CentOS 7, there definitely are wheels available for "cp311" "manylinux" on all major CPU architectures. Whatever your issue is, it's unrelated to Streamlink, so you'll have to figure this out on your own. We can't help you with your messed up python environment.

As a hint, don't install any python packages via pip as root. This is a good way of breaking your system's global Python environment. Use a virtualenv instead.

If you're having issues installing Streamlink and its Python dependencies on your system, then use the available appimages.
https://streamlink.github.io/install.html#linux-appimages

Otherwise, take a look at the other install docs and how to install packages via pip. Good luck.
