### ISSUE TITLE
Unable to build on python 3.11 docker image

### ISSUE THREAD

**Issue by michaelarnauts** [streamlink/streamlink#5841]
### Checklist

- [X] This is a bug report and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

6.6.1

### Description

Since the recent change of https://github.com/streamlink/streamlink/commit/115c2ed4863f092042da0bee2a444cd84a1dd0a3, it seems I can't build the plugin anymore in Python 3.11.

It is complaining that logging.INFO (=20) is an invalid log level.
```python
self.announce("building plugins JSON data", logging.INFO)
```

You can reproduce it by trying to build this Dockerfile:

```Dockerfile
FROM python:3.11

RUN cd /tmp && \
    wget https://github.com/streamlink/streamlink/releases/download/6.6.1/streamlink-6.6.1.tar.gz && \
    tar -xzvf streamlink-*.tar.gz && \
    cd streamlink-* && \
    python setup.py bdist_wheel
```

### Debug log

```text
...
1.628 adding license file 'LICENSE'
1.632 writing manifest file 'src/streamlink.egg-info/SOURCES.txt'
1.634 copying src/streamlink_cli/py.typed -> build/lib/streamlink_cli
1.634 copying src/streamlink/py.typed -> build/lib/streamlink
1.635 copying src/streamlink/session/http.pyi -> build/lib/streamlink/session
1.635 Traceback (most recent call last):
1.635   File "/tmp/streamlink-6.6.1/setup.py", line 89, in <module>
1.635     setup(
1.635   File "/usr/local/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
1.635     return distutils.core.setup(**attrs)
1.635            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1.635   File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
1.635     return run_commands(dist)
1.635            ^^^^^^^^^^^^^^^^^^
1.635   File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
1.635     dist.run_commands()
1.635   File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
1.635     self.run_command(cmd)
1.635   File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
1.635     super().run_command(command)
1.635   File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
1.636     cmd_obj.run()
1.636   File "/usr/local/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 368, in run
1.636     self.run_command("build")
1.636   File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
1.636     self.distribution.run_command(command)
1.636   File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
1.636     super().run_command(command)
1.636   File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
1.636     cmd_obj.run()
1.636   File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 132, in run
1.636     self.run_command(cmd_name)
1.636   File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
1.636     self.distribution.run_command(command)
1.636   File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
1.636     super().run_command(command)
1.636   File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
1.637     cmd_obj.run()
1.637   File "/usr/local/lib/python3.11/site-packages/setuptools/command/build_py.py", line 63, in run
1.637     self.build_package_data()
1.637   File "/tmp/streamlink-6.6.1/build_backend/commands.py", line 29, in build_package_data
1.637     self._build_plugins_json()
1.637   File "/tmp/streamlink-6.6.1/build_backend/commands.py", line 19, in _build_plugins_json
1.637     self.announce("building plugins JSON data", logging.INFO)
1.637   File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 186, in announce
1.637     log.log(level, msg)
1.637   File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/log.py", line 40, in log
1.637     self._log(level, msg, args)
1.637   File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/log.py", line 21, in _log
1.637     raise ValueError('%s wrong log level' % str(level))
1.637 ValueError: 20 wrong log level
------
Dockerfile:3
--------------------
   2 |
   3 | >>> RUN cd /tmp && \
   4 | >>>     wget https://github.com/streamlink/streamlink/releases/download/6.6.1/streamlink-6.6.1.tar.gz && \
   5 | >>>     tar -xzvf streamlink-*.tar.gz && \
   6 | >>>     cd streamlink-* && \
   7 | >>>     python setup.py bdist_wheel
   8 |
--------------------
ERROR: failed to solve: process "/bin/sh -c cd /tmp &&     wget https://github.com/streamlink/streamlink/releases/download/6.6.1/streamlink-6.6.1.tar.gz &&     tar -xzvf streamlink-*.tar.gz &&     cd streamlink-* &&     python setup.py bdist_wheel" did not complete successfully: exit code: 1
```

**Comment by skulblakka** [comment]
Support for loglevels of the standard library have been added in [setuptools 65.6](https://setuptools.pypa.io/en/latest/history.html#id165) while the python 3.11 docker container comes with setuptools 65.5.1.

Updating setuptools to 65.6+ should resolve the issue.

**Comment by bastimeyer** [comment]
> ```
> python setup.py bdist_wheel
> ```

Invoking setuptools directly has been deprecated a long time ago.

Since PEP 517/518, you need a **build frontend**, e.g. [`build`](https://pypi.org/project/build/) or `pip`.
https://streamlink.github.io/install.html#source-distribution

Unless disabled, build-frontends build the package in an isolated environment with all build-backend dependencies installed which are defined in the project's `pyproject.toml`.

```sh
docker run --rm -i python:3.11 bash <<"EOF"
cd "$(mktemp -d)"
curl -SLO https://github.com/streamlink/streamlink/releases/download/6.6.1/streamlink-6.6.1.tar.gz
tar -xzf streamlink-6.6.1.tar.gz --strip-components=1
python -m pip install build
python -m build --wheel
python -m pip install ./dist/streamlink-6.6.1-py3-none-any.whl
python -m streamlink -l debug
EOF
```

> loglevels of the standard library has been added in [setuptools 65.6](https://setuptools.pypa.io/en/latest/history.html#id165)

Thanks for the hint, @skulblakka.

Streamlink's [`pyproject.toml` currently requires `setuptools >=64`](https://github.com/streamlink/streamlink/blob/6.6.1/pyproject.toml#L3), so this needs to get bumped.
