### ISSUE TITLE
plugins.afreeca: plug-in is not working.

### ISSUE THREAD

**Issue by Dev-Pixel-www** [streamlink/streamlink#5984]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Streamlink version (6.7.3)

### Description

Only Afreeca TV plugins don't work. It's the same if I install a new Python and Streamlink.

### Debug log

```text
streamlink https://play.afreecatv.com/khm11903 best --loglevel=all --ffmpeg-copyts
[02:05:23.579316][session][debug] Loading plugin: afreeca
[02:05:23.611324][cli][debug] OS:         Windows 10
[02:05:23.612324][cli][debug] Python:     3.12.3
[02:05:23.612324][cli][debug] OpenSSL:    OpenSSL 3.0.13 30 Jan 2024
[02:05:23.613323][cli][debug] Streamlink: 6.7.3
[02:05:23.614325][cli][debug] Dependencies:
[02:05:23.615325][cli][debug]  certifi: 2024.2.2
[02:05:23.615325][cli][debug]  exceptiongroup: 1.2.0
[02:05:23.616325][cli][debug]  isodate: 0.6.1
[02:05:23.617326][cli][debug]  lxml: 5.2.1
[02:05:23.617326][cli][debug]  pycountry: 23.12.11
[02:05:23.618326][cli][debug]  pycryptodome: 3.20.0
[02:05:23.618326][cli][debug]  PySocks: 1.7.1
[02:05:23.619326][cli][debug]  requests: 2.31.0
[02:05:23.619326][cli][debug]  trio: 0.25.0
[02:05:23.620326][cli][debug]  trio-websocket: 0.11.1
[02:05:23.620326][cli][debug]  typing-extensions: 4.11.0
[02:05:23.621326][cli][debug]  urllib3: 2.2.1
[02:05:23.621326][cli][debug]  websocket-client: 1.7.0
[02:05:23.621326][cli][debug] Arguments:
[02:05:23.621326][cli][debug]  url=https://play.afreecatv.com/khm11903
[02:05:23.622326][cli][debug]  stream=['best']
[02:05:23.622326][cli][debug]  --loglevel=all
[02:05:23.622326][cli][debug]  --ffmpeg-ffmpeg=C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe
[02:05:23.623327][cli][debug]  --ffmpeg-copyts=True
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Streamlink\bin\streamlink.exe\__main__.py", line 18, in <module>
  File "C:\Program Files\Streamlink\pkgs\streamlink_cli\main.py", line 963, in main
    error_code = run(parser)
                 ^^^^^^^^^^^
  File "C:\Program Files\Streamlink\pkgs\streamlink_cli\main.py", line 936, in run
    handle_url()
  File "C:\Program Files\Streamlink\pkgs\streamlink_cli\main.py", line 544, in handle_url
    plugin = pluginclass(streamlink, resolved_url, options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Streamlink\pkgs\streamlink\plugins\afreeca.py", line 92, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Program Files\Streamlink\pkgs\streamlink\plugin\plugin.py", line 307, in __init__
    self.load_cookies()
  File "C:\Program Files\Streamlink\pkgs\streamlink\plugin\plugin.py", line 563, in load_cookies
    for key, value in self.cache.get_all().items():
                      ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Streamlink\pkgs\streamlink\cache.py", line 171, in get_all
    ret[okey] = value["value"]
                ~~~~~^^^^^^^^^
KeyError: 'value'
```

**Comment by Dev-Pixel-www** [comment]
Thank you. I solved it by deleting plugin-cache.json.

**Comment by bastimeyer** [comment]
Would've been nice to know if you indeed modified the file, because as said, a missing `value` attribute for any stored cookies doesn't make any sense to me.
