### ISSUE TITLE
When I close VLC I get this error

### ISSUE THREAD

**Issue by thinkpad4** [streamlink/streamlink#604]
### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description
```
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
Traceback (most recent call last):
  File "d:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 12, in
 <module>
    main()
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 952
, in main
    handle_url()
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 499
, in handle_url
    handle_stream(plugin, streams, stream_name)
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 381
, in handle_stream
    success = output_stream(stream)
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 270
, in output_stream
    read_stream(stream_fd, output, prebuffer)
  File "contextlib.py", line 159, in __exit__
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\output.py", line 2
8, in close
    self._close()
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\output.py", line 1
58, in _close
    self.http.close()
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\utils\http_server.
py", line 115, in close
    self.socket.shutdown(2)
OSError: [WinError 10057] A request to send or receive data was disallowed becau
se the socket is not connected and (when sending on a datagram socket using a se
ndto call) no address was supplied
```

### Expected / Actual behavior

Not to happen

### Reproduction steps / Stream URLs to test

just close vlc when watching a twitch stream

### Environment details (operating system, python version, etc.)

Win7 64bit latest nightly

### Comments, logs, screenshots, etc.
@gravyboat @beardypig do you get this error too?

**Comment by beardypig** [comment]
I assume you have the `http-player` option enabled? 

I have recreated the issue, should be simple to fix. I will submit a PR later to fix it.

**Comment by thinkpad4** [comment]
@beardypig Yes I do, sorry for not adding that, it's been set that way for so long that I didn't even think about it
