### ISSUE TITLE
It's not possible to add arguments in the custom plugin: AttributeError: 'Namespace' object has no attribute 'youtube_playlist_max'

### ISSUE THREAD

**Issue by JunioCalu** [streamlink/streamlink#6186]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Collaboration

- [X] [I will provide feedback should a pull request be opened with a fix for the plugin](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Streamlink version

streamlink 6.10.0

### Description

I'm customizing the generic plugin attached below, but I'm not able to add argument parameters to it:

[generic.py.txt](https://github.com/user-attachments/files/16994673/generic.py.txt)

### Debug log

```text
streamlink --loglevel=debug --hls-live-edge 6 --ringbuffer-size 64M -4 --default-stream best --url "https://www.youtube.com/watch?v=xwq5HDrO-iw"
[session][debug] Loading plugin: youtube
[cli][debug] OS:         Linux-6.6.47-1-MANJARO-x86_64-with-glibc2.40
[cli][debug] Python:     3.12.5
[cli][debug] OpenSSL:    OpenSSL 3.3.1 4 Jun 2024
[cli][debug] Streamlink: 6.10.0
[cli][debug] Dependencies:
[cli][debug]  certifi: 2024.8.30
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 5.3.0
[cli][debug]  pycountry: 24.6.1
[cli][debug]  pycryptodome: 3.20.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.32.3
[cli][debug]  trio: 0.26.2
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.12.2
[cli][debug]  urllib3: 2.2.3
[cli][debug]  websocket-client: 1.8.0
[cli][debug] Arguments:
[cli][debug]  url=https://www.youtube.com/watch?v=xwq5HDrO-iw
[cli][debug]  --loglevel=debug
[cli][debug]  --ipv4=True
[cli][debug]  --url=https://www.youtube.com/watch?v=xwq5HDrO-iw
[cli][debug]  --default-stream=['best']
[cli][debug]  --ringbuffer-size=67108864
[cli][debug]  --hls-live-edge=6
[cli][debug]  --ffmpeg-verbose=True
Traceback (most recent call last):
  File "/home/junio/livebot/venv/bin/streamlink", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/junio/livebot/venv/lib/python3.12/site-packages/streamlink_cli/main.py", line 990, in main
    exit_code = run(parser)
                ^^^^^^^^^^^
  File "/home/junio/livebot/venv/lib/python3.12/site-packages/streamlink_cli/main.py", line 957, in run
    handle_url()
  File "/home/junio/livebot/venv/lib/python3.12/site-packages/streamlink_cli/main.py", line 534, in handle_url
    options = setup_plugin_options(pluginname, pluginclass)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junio/livebot/venv/lib/python3.12/site-packages/streamlink_cli/main.py", line 740, in setup_plugin_options
    value = getattr(args, parg.namespace_dest(pluginname))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'youtube_playlist_max'
```

**Comment by bastimeyer** [comment]
This is not what the issue tracker and plugin issues are for. You are looking for support for third party code. This is not supported here.
