### ISSUE TITLE
plugins.abematv: URL matching broken

### ISSUE THREAD

**Issue by Hakkin** [streamlink/streamlink#6366]
### Checklist

- [x] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [x] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [x] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [x] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Collaboration

- [x] [I will provide feedback should a pull request be opened with a fix for the plugin](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Streamlink version

streamlink 7.1.1

### Description

The plugin raises an exception when trying to match `/video/episode/` and `/channels/.../slots/` links for Abema.tv. `/now-on-air/` URLs still work correctly.
Example URL: https://abema.tv/channels/anime-live/slots/E1MrshEdMczcP1

### Debug log

```text
[12:25:03.588818][session][debug] Loading plugin: abematv
[12:25:03.602688][cli][debug] OS:         Linux-6.6.68-1-lts-x86_64-with-glibc2.40
[12:25:03.602847][cli][debug] Python:     3.13.1
[12:25:03.602934][cli][debug] OpenSSL:    OpenSSL 3.4.0 22 Oct 2024
[12:25:03.603008][cli][debug] Streamlink: 7.1.1
[12:25:03.603572][cli][debug] Dependencies:
[12:25:03.609891][cli][debug]  certifi: 2024.12.14
[12:25:03.613221][cli][debug]  isodate: 0.7.2
[12:25:03.615045][cli][debug]  lxml: 5.3.0
[12:25:03.617867][cli][debug]  pycountry: 24.6.1
[12:25:03.619685][cli][debug]  pycryptodome: 3.21.0
[12:25:03.622057][cli][debug]  PySocks: 1.7.1
[12:25:03.623912][cli][debug]  requests: 2.32.3
[12:25:03.625738][cli][debug]  trio: 0.28.0
[12:25:03.626997][cli][debug]  trio-websocket: 0.11.1
[12:25:03.628696][cli][debug]  urllib3: 2.3.0
[12:25:03.631254][cli][debug]  websocket-client: 1.8.0
[12:25:03.632364][cli][debug] Arguments:
[12:25:03.632648][cli][debug]  url=https://abema.tv/channels/anime-live/slots/E1MrshEdMczcP1
[12:25:03.632832][cli][debug]  stream=['best']
[12:25:03.633017][cli][debug]  --loglevel=all
[12:25:03.634056][cli][info] Found matching plugin abematv for URL https://abema.tv/channels/anime-live/slots/E1MrshEdMczcP1
Traceback (most recent call last):
  File "/home/hakkin/.local/bin/streamlink", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/hakkin/.local/pipx/venvs/streamlink/lib/python3.13/site-packages/streamlink_cli/main.py", line 976, in main
    exit_code = run(parser)
  File "/home/hakkin/.local/pipx/venvs/streamlink/lib/python3.13/site-packages/streamlink_cli/main.py", line 959, in run
    exit_code = handle_url_wrapper()
  File "/home/hakkin/.local/pipx/venvs/streamlink/lib/python3.13/site-packages/streamlink_cli/main.py", line 552, in handle_url_wrapper
    handle_url()
    ~~~~~~~~~~^^
  File "/home/hakkin/.local/pipx/venvs/streamlink/lib/python3.13/site-packages/streamlink_cli/main.py", line 599, in handle_url
    streams = fetch_streams(plugin)
  File "/home/hakkin/.local/pipx/venvs/streamlink/lib/python3.13/site-packages/streamlink_cli/main.py", line 472, in fetch_streams
    return plugin.streams(
           ~~~~~~~~~~~~~~^
        stream_types=args.stream_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        sorting_excludes=args.stream_sorting_excludes,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/hakkin/.local/pipx/venvs/streamlink/lib/python3.13/site-packages/streamlink/plugin/plugin.py", line 399, in streams
    ostreams = self._get_streams()
  File "/home/hakkin/.local/pipx/venvs/streamlink/lib/python3.13/site-packages/streamlink/plugins/abematv.py", line 226, in _get_streams
    if matchresult.group("onair"):
       ~~~~~~~~~~~~~~~~~^^^^^^^^^
IndexError: no such group
```

**Comment by bastimeyer** [comment]
Caused by 742988f2d57f1807bea2210a1d721c632c1d7b75

The capture group checks were not updated in some plugins after splitting verbose regexes into multiple simple ones, causing an `IndexError` to be raised by calling `Match.group()` or `Match.__getitem__()`. Same issue as #6363 

I'll fix this and the remaining plugins later.
