### ISSUE TITLE
pycountry does not handle some locales

### ISSUE THREAD

**Issue by beardypig** [streamlink/streamlink#649]
Originally reported here: https://github.com/streamlink/streamlink-portable/issues/12 by @sysilion

### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description
 
Using some locales with `pycountry` will produce an `AttributeError` from `pycountry`. 

### Reproduction steps / Stream URLs to test

`streamlink --locale ko_KR twitch.tv/twitch`

### Environment details (operating system, python version, etc.)

When using the `pycountry` module instead of `iso3116/iso-639` modules.

### Comments, logs, screenshots, etc.

```shell
$ streamlink --locale ko_KR -ldebug "twitch.tv/twitch"
[cli][info] Found matching plugin twitch for URL twitch.tv/twitch
[plugin.twitch][debug] Getting live HLS streams for twitch
[plugin.twitch][info] Attempting to authenticate using OAuth token
[plugin.twitch][info] Successfully logged in as beardypig
Traceback (most recent call last):
  File "/home/beardypig/.virtualenvs/streamlink-python3.6/bin/streamlink", line 11, in <module>
    load_entry_point('streamlink', 'console_scripts', 'streamlink')()
  File "/home/beardypig/projects/streamlink/src/streamlink_cli/main.py", line 978, in main
    handle_url()
  File "/home/beardypig/projects/streamlink/src/streamlink_cli/main.py", line 479, in handle_url
    streams = fetch_streams(plugin)
  File "/home/beardypig/projects/streamlink/src/streamlink_cli/main.py", line 391, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/home/beardypig/projects/streamlink/src/streamlink/plugin/plugin.py", line 321, in get_streams
    return self.streams(*args, **kwargs)
  File "/home/beardypig/projects/streamlink/src/streamlink/plugin/plugin.py", line 230, in streams
    ostreams = self._get_streams()
  File "/home/beardypig/projects/streamlink/src/streamlink/plugins/twitch.py", line 600, in _get_streams
    return self._get_hls_streams("live")
  File "/home/beardypig/projects/streamlink/src/streamlink/plugins/twitch.py", line 564, in _get_hls_streams
    force_restart=not stream_type == "live")
  File "/home/beardypig/projects/streamlink/src/streamlink/stream/hls.py", line 286, in parse_variant_playlist
    locale = session_.localization
  File "/home/beardypig/projects/streamlink/src/streamlink/session.py", line 474, in localization
    return Localization(self.get_option("locale"))
  File "/home/beardypig/projects/streamlink/src/streamlink/utils/l10n.py", line 113, in __init__
    self.language_code = language_code
  File "/home/beardypig/projects/streamlink/src/streamlink/utils/l10n.py", line 137, in language_code
    self.country = self.get_country(parts[1])
  File "/home/beardypig/projects/streamlink/src/streamlink/utils/l10n.py", line 152, in get_country
    return Country.get(country)
  File "/home/beardypig/projects/streamlink/src/streamlink/utils/l10n.py", line 31, in get
    return Country(c.alpha_2, c.alpha_3, c.numeric, c.name, c.official_name)
  File "/home/beardypig/.virtualenvs/streamlink-python3.6/lib/python3.6/site-packages/pycountry/db.py", line 22, in __getattr__
    raise AttributeError
AttributeError
```

**Comment by gravyboat** [comment]
Closing since #650 is merged.
