### ISSUE TITLE
streamlink doesn't run under PyPy

### ISSUE THREAD

**Issue by tycho** [streamlink/streamlink#876]
If I try to run streamlink under PyPy, I get this:

```
Traceback (most recent call last):
  File "/opt/pypy/bin/streamlink", line 11, in <module>
    load_entry_point('streamlink==0.5.0', 'console_scripts', 'streamlink')()
  File "/opt/pypy/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/pypy/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/opt/pypy/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/opt/pypy/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/pypy/site-packages/streamlink_cli/main.py", line 17, in <module>
    from streamlink.stream import StreamProcess
  File "/opt/pypy/site-packages/streamlink/stream/__init__.py", line 4, in <module>
    from streamlink.stream.akamaihd import AkamaiHDStream
  File "/opt/pypy/site-packages/streamlink/stream/akamaihd.py", line 15, in <module>
    from ..packages.flashmedia import FLV, FLVError
  File "/opt/pypy/site-packages/streamlink/packages/flashmedia/__init__.py", line 4, in <module>
    from .amf import *
  File "/opt/pypy/site-packages/streamlink/packages/flashmedia/amf.py", line 3, in <module>
    from .types import AMF0String, AMF0Value, U8, U16BE, U32BE
  File "/opt/pypy/site-packages/streamlink/packages/flashmedia/types.py", line 298, in <module>
    U24BE = HighLowCombo(">HB", 8, True)
TypeError: __new__() takes exactly 2 arguments (4 given)
```

The cause of this is that the `Struct` base class for `PrimitiveType` has a `__new__()` function with different arguments:
```
$ pypy -c "import struct; help(struct.Struct.__new__)"
Help on function __new__:

__new__(subtype, format)

$ python2 -c "import struct; help(struct.Struct.__new__)"
Help on built-in function __new__:

__new__(...)
    T.__new__(S, ...) -> a new object with type S, a subtype of T
```

This smells like it could be a PyPy bug, so I've raised this as an issue in the PyPy project to see what they have to say about it:

https://bitbucket.org/pypy/pypy/issues/2551/structstruct-has-weird-__new__-arguments

But in the meantime... perhaps the better approach is to simply not inherit from Struct to begin with:
```diff
diff --git a/src/streamlink/packages/flashmedia/types.py b/src/streamlink/packages/flashmedia/types.py
index cc4fcca..ee5f3d2 100644
--- a/src/streamlink/packages/flashmedia/types.py
+++ b/src/streamlink/packages/flashmedia/types.py
@@ -29,10 +29,17 @@ AMF3_MIN_INTEGER = -268435456
 AMF3_MAX_INTEGER = 268435455
 
 
-class PrimitiveType(Struct):
+class PrimitiveType(object):
     def __call__(self, *args):
         return self.pack(*args)
 
+    def __init__(self, strformat):
+        self.struct = Struct(strformat)
+
+    @property
+    def size(self):
+        return self.struct.size
+
     def read(self, fd):
         data = fd.read(self.size)
 
@@ -41,6 +48,18 @@ class PrimitiveType(Struct):
 
         return self.unpack(data)[0]
 
+    def pack(self, *args):
+        return self.struct.pack(*args)
+
+    def pack_into(self, *args):
+        return self.struct.pack_into(*args)
+
+    def unpack(self, *args):
+        return self.struct.unpack(*args)
+
+    def unpack_from(self, *args):
+        return self.struct.unpack_from(*args)
+
 
 class PrimitiveClassType(PrimitiveType):
     def __init__(self, format, cls):
```

This should work for both CPython and PyPy, and is probably the cleaner fix. I don't know what (if any) other `Struct` member functions need to be wrapped if this code path actually gets hit though. I don't think I'm hitting it with my test case of streaming from Twitch.tv.

Thoughts?

**Comment by beardypig** [comment]
Seems like it was an issue with PyPy?

**Comment by tycho** [comment]
Yep. Thanks for the fast reply! 😆
