### ISSUE TITLE
TypeError: request() got an unexpected keyword argument 'retries'

### ISSUE THREAD

**Issue by SanyaIV** [streamlink/streamlink#932]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Just updated from Streamlink... uhm.. some version.. Iunno 0.2.0? to 0.6.0 and now I can't launch streams anymore.

### Expected / Actual behavior

Stream to launch.

### Reproduction steps / Explicit stream URLs to test

1. ... iunno, launch any stream.
2. ...
3. ...

### Environment details

Operating system and version: ... Windows 10 64bit version 1703 build 15063.296
Streamlink and Python version: ... Streamlink 0.6.0 Python... Not sure, I have 2.7 and 3.5 installed.

### Comments, logs, screenshots, etc.
```
C:\Users\sanya>streamlink twitch.tv/sacriel best
[cli][info] Found matching plugin twitch for URL twitch.tv/sacriel
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 15, in <module>
    main()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 1027, in main
    handle_url()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 502, in handle_url
    handle_stream(plugin, streams, stream_name)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 384, in handle_stream
    success = output_stream(stream)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 250, in output_stream
    stream_fd, prebuffer = open_stream(stream)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 225, in open_stream
    stream_fd = stream.open()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 267, in open
    reader.open()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\segmented.py", line 185, in open
    self.worker = self.__worker__(self)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 126, in __init__
    self.reload_playlist()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 137, in reload_playlist
    **self.reader.request_params)
  File "C:\Program Files (x86)\Streamlink\pkgs\requests\sessions.py", line 531, in get
    return self.request('GET', url, **kwargs)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\api\http_session.py", line 156, in request
    *args, **kwargs)
TypeError: request() got an unexpected keyword argument 'retries'
```

**Comment by beardypig** [comment]
@SanyaIV did you uninstall streamlink before installing the new version? If you didn't it might be worth trying that.

**Comment by SanyaIV** [comment]
I didn't, but I'll try that.

**Comment by gravyboat** [comment]
Good stuff! I'm going to close this since it's resolved.
