### ISSUE TITLE
can't play any twtich stream

### ISSUE THREAD

**Issue by craftwar** [streamlink/streamlink#934]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
Try to watch any twitch stream on my win7 64bit. No one works.
...

### Expected / Actual behavior
Error as below, streamlink stops. 

### Reproduction steps / Explicit stream URLs to test

1. use pip install streamlink in python35-32
2. D:\Python\Python35-32\Scripts\streamlink.exe -p "C:\Program Files\VideoLAN\VLC\vlc.exe" -player-continuous-http http://twitch.tv/divinity_123 best
3. other streams tested
    http://twitch.tv/voyboy, http://twitch.tv/froggen

### Environment details

Operating system and version: win7 64 bit ultimate
Streamlink and Python version: python3.5.2, Streamlink 0.6.0(install from pip)

### Comments, logs, screenshots, etc.
```
D:\Python\Python35-32\Scripts\streamlink.exe -p "C:\Program Files\VideoLAN\VLC\vlc.exe" -player-continuous-http http://twitch.tv/divinity_123 best
[cli][info] Found matching plugin twitch for URL twitch.tv/divinity_123
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p (best)

[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: layer-continuous-http
[cli][info] Closing currently open stream...
Traceback (most recent call last):
  File "d:\programs\python\python35-32\lib\site-packages\streamlink_cli\main.py", line 262, in output_stream
    output.open()
  File "d:\programs\python\python35-32\lib\site-packages\streamlink_cli\output.py", line 23, in open
    self._open()
  File "d:\programs\python\python35-32\lib\site-packages\streamlink_cli\output.py", line 124, in _open
    self._open_subprocess()
  File "d:\programs\python\python35-32\lib\site-packages\streamlink_cli\output.py", line 142, in _open_subprocess
    stderr=self.stderr)
  File "d:\programs\python\python35-32\lib\subprocess.py", line 947, in __init__

    restore_signals, start_new_session)
  File "d:\programs\python\python35-32\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系統找不到指定的\u6a94案。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Programs\Python\Python35-32\Scripts\streamlink-script.py", line 9, in
 <module>
    load_entry_point('streamlink==0.6.0', 'console_scripts', 'streamlink')()
  File "d:\programs\python\python35-32\lib\site-packages\streamlink_cli\main.py", line 1027, in main
    handle_url()
  File "d:\programs\python\python35-32\lib\site-packages\streamlink_cli\main.py", line 502, in handle_url
    handle_stream(plugin, streams, stream_name)
  File "d:\programs\python\python35-32\lib\site-packages\streamlink_cli\main.py", line 384, in handle_stream
    success = output_stream(stream)
  File "d:\programs\python\python35-32\lib\site-packages\streamlink_cli\main.py", line 266, in output_stream
    args.player, err)
  File "d:\programs\python\python35-32\lib\site-packages\streamlink_cli\console.py", line 69, in exit
    self.msg(u"{0}", msg)
  File "d:\programs\python\python35-32\lib\site-packages\streamlink_cli\console.py", line 45, in msg
    self.output.write(formatted)
	UnicodeEncodeError: 'cp932' codec can't encode character '\u6a94' in position 75
: illegal multibyte sequence
```

**Comment by craftwar** [comment]
I find out what's wrong.
[cli][info] Starting player: layer-continuous-http
Streamlink try to start player: "layer-continuous-http"
I need use --player-continuous-http as agrument to work properly.

doc or code need to be fixed.

**Comment by gravyboat** [comment]
The first dash missing is an issue with the docs we have yet to fix unfortunately: https://github.com/streamlink/streamlink.github.io/issues/1

**Comment by bastimeyer** [comment]
> doc or code need to be fixed.

https://streamlink.github.io/cli.html#cmdoption-player-continuous-http
The documentation itself is fine and the parameter you're talking about is a multi-character parameter, which requires a double hyphen if we want to keep all parameters in [Unix style](https://serverfault.com/questions/387935/whats-the-difference-betwen-the-single-dash-and-double-dash-flags-on-shell-comm).

It is just the anchor that doesn't include the whole parameter name.
The anchor format that's being used here is
`"cmdoption" + "-" + parameterWithoutAnyLeadingDashes`
and not
`"cmdoption" + parameter`.

**Comment by beardypig** [comment]
They "fixed" the URLs in Sphinx (https://github.com/streamlink/streamlink.github.io/issues/1#issuecomment-287378698) because it's not a valid URL if there are two dashes in a row. 

However, there is an actual issue with the docs... there is only one dash.

**Comment by bastimeyer** [comment]
> there is only one dash

You are right.. It's a single [`U+2013` (en-dash)](http://www.fileformat.info/info/unicode/char/2013/index.htm) character instead of two `U+002D`. This looks weird on my system.

The `smart_quotes` option needs to be turned off (on by default):
http://www.sphinx-doc.org/en/stable/config.html#confval-html_use_smartypants
http://docutils.sourceforge.net/docs/user/config.html#smart-quotes

**Comment by beardypig** [comment]
Yeah, I'm updating it now... :)

**Comment by gravyboat** [comment]
Closing since #940 is merged.
