### ISSUE TITLE
Error on nightly when using twitch

### ISSUE THREAD

**Issue by thinkpad4** [streamlink/streamlink#945]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Getting a error when trying to connect to a twitch stream with the latest nightly

### Expected / Actual behavior

```
[cli][info] Found matching plugin twitch for URL twitch.tv/crream
[plugin.twitch][info] Attempting to authenticate using OAuth token
[plugin.twitch][info] Successfully logged in as Thinkpad4
error: No playable streams found on this URL: twitch.tv/crream
```

That is what it should return ^

### Reproduction steps / Explicit stream URLs to test

```
[cli][info] Found matching plugin twitch for URL twitch.tv/crream
[plugin.twitch][info] Attempting to authenticate using OAuth token
[plugin.twitch][info] Successfully logged in as Thinkpad4
Traceback (most recent call last):
  File "d:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 15, in
 <module>
    main()
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 103
8, in main
    handle_url()
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 482
, in handle_url
    streams = fetch_streams(plugin)
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 394
, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", lin
e 328, in get_streams
    return self.streams(*args, **kwargs)
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", lin
e 236, in streams
    ostreams = self._get_streams()
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\twitch.py", li
ne 617, in _get_streams
    return self._get_hls_streams("live")
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\twitch.py", li
ne 581, in _get_hls_streams
    force_restart=not stream_type == "live")
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 2
88, in parse_variant_playlist
    locale = session_.localization
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink\session.py", line 474,
 in localization
    return Localization(self.get_option("locale"))
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\l10n.py", line 1
15, in __init__
    self.language_code = language_code
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\l10n.py", line 1
40, in language_code
    self.language, self.country = self._parse_locale_code(language_code)
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\l10n.py", line 1
25, in _parse_locale_code
    return self.get_language(parts[0]), self.get_country(parts[1])
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\l10n.py", line 1
68, in get_language
    return Language.get(language)
  File "d:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\l10n.py", line 7
5, in get
    l = languages.get(alpha2=language)
  File "d:\Program Files (x86)\Streamlink\pkgs\iso639\iso639.py", line 265, in g
et
    return getattr(self, key)[value]
  File "d:\Program Files (x86)\Streamlink\pkgs\iso639\iso639.py", line 132, in _
_getattr__
    'alpha2': self.part1,
  File "d:\Program Files (x86)\Streamlink\pkgs\iso639\iso639.py", line 105, in _
_get__
    val = self.f(instance)
  File "d:\Program Files (x86)\Streamlink\pkgs\iso639\iso639.py", line 198, in p
art1
    return dict((x.part1, x) for x in self.languages if x.part1)
  File "d:\Program Files (x86)\Streamlink\pkgs\iso639\iso639.py", line 105, in _
_get__
    val = self.f(instance)
  File "d:\Program Files (x86)\Streamlink\pkgs\iso639\iso639.py", line 174, in l
anguages
    l, i, m, p5, p2, p1 = _fabtabular()
  File "d:\Program Files (x86)\Streamlink\pkgs\iso639\iso639.py", line 20, in _f
abtabular
    from pkg_resources import resource_filename
  File "d:\Program Files (x86)\Streamlink\pkgs\pkg_resources\__init__.py", line
48, in <module>
    import six
ImportError: No module named 'six'
```

That is what it is returning with the latest nightly

### Environment details

Windows 7 64bit Latest Nightly

**Comment by Takeoverkyle** [comment]
Getting the same error(while trying different users) on Windows 10 64bit lastest nightly

**Comment by thinkpad4** [comment]
Any luck on figuring out what is causing this error on the latest nightly?

**Comment by beardypig** [comment]
@thinkpad4, no need to tag us - we see it regardless. I'm looking in to it, I'm dunno if anyone else is, but I'm sure if anyone has a solution they'll say...

**Comment by bastimeyer** [comment]
> return Localization(self.get_option("locale"))
> iso639
> ImportError: No module named 'six'

So is this a dependency issue here or a configuration issue (eg. invalid / weird env vars)?

@thinkpad4 What's the value of your `locale` env var?

**Comment by beardypig** [comment]
It appears to be a difference on travis, we are importing `pkg_resources` (which is part of `setuptools`) but for some reason the vendored packages required for `pkg_resources` are missing (`six`, `pyparsing`, etc.). I have _not_ been able to recreate the broken build on a local VM, the versions of `setuptools`, `pip`, etc. were the same, but my local install included the required packages. 

I have created a branch which includes the missing packages, but it's a bit tricky to test as I need to somehow get the build artefact from travis to test it.

**Comment by thinkpad4** [comment]
@bastimeyer My local Env Var?

**Comment by thinkpad4** [comment]
How goes solving the error?

**Comment by Takeoverkyle** [comment]
@thinkpad4 
I found out how to find the env var, it just took me a bit. Here's what you do

- From the desktop, right click the Computer icon and click on properties
- Look for something called "Advanced System Settings
- A window called "Environment Variables" should popup 
- Try and look for the locale variable in "System Variables" (I couldn't find it either honestly)

I've tried using other versions to see if it was maybe 0.6.0 that was having a problem. When trying 0.5.0, it also wouldn't work as I was getting the same error. Tried a few different sites with the current version of Streamlink and got the same errors for all of them as well. With the info I gave thinkpad about the locale thing, I couldn't find it on my computer at all.

**Comment by beardypig** [comment]
@thinkpad4 please don't bump issues, it just clogs up peoples notification lists and doesn't add anything to the conversation - it also might discourage people from actually working on the issue. 

I have created a PR that should resolve the nightly build issues.

**Comment by Takeoverkyle** [comment]
@beardypig 
Thanks for that update. It somewhat helped, but there seems to be another problem that pops up. It's a lot shorter than the other one.

C:\Windows\System32>streamlink twitch.tv/lirik best
Traceback (most recent call last):
  File "D:\Streamlink\bin\streamlink-script.py", line 14, in <module>
    from streamlink_cli.main import main
  File "D:\Streamlink\pkgs\streamlink_cli\main.py", line 3, in <module>
    import requests
  File "D:\Streamlink\pkgs\requests\__init__.py", line 48, in <module>
    import urllib3
ImportError: No module named 'urllib3`

**Comment by beardypig** [comment]
@Takeoverkyle `urllib3` will be covered too, but there is no installer available that includes it yet. The nightly version is still built without the missing modules. The `urllib3` error is new in the last day or so from an updated version of `requests`. You'll have to wait until the fix is merged and the new nightly is available, or build the installer yourself on a Linux/macOS box.

**Comment by Takeoverkyle** [comment]
Oh, not a problem then. Thanks

**Comment by beardypig** [comment]
The next nightly should have this issue resolved.
