### ISSUE TITLE
python traceback error when trying to start any stream

### ISSUE THREAD

**Issue by distommy** [streamlink/streamlink#985]
### Checklist

- [x] This is a bug report.
- [x] I have read the contribution guidelines.

### Description

Trying to run any command gives me a python related error

### Expected / Actual behavior

start a stream, e.g. `streamlink twitch.tv/imaqtpie` doesnt work, gives me an error message (see logs)

### Reproduction steps / Explicit stream URLs to test

1.just try starting any stream
2. error message

### Environment details

 Debian 3.2.88-1 x86_64
 newest streamlink (via pip) and python 2.7
...

### Comments, logs, screenshots, etc.
```
root@vps:/# streamlink twitch.tv/imaqtpie
Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: iso3166
```
...

**Comment by beardypig** [comment]
Try and do `pip install --upgrade streamlink`, to get it to install the missing module.

**Comment by roshavagarga** [comment]
Another option is to completely uninstall, restart and then install streamlink 0.6 and install the latest nightly on top of that. That seemed to fix the problem on my side.

**Comment by distommy** [comment]
Doing `pip install --upgrade streamlink` didnt seem to do anything, everything apparently is up to date
```
root@vps:~# pip install --upgrade streamlink
/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/_vendor/requests/                                                                                                                                                                                                                                                                                                                                                                                                             packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been                                                                                                                                                                                                                                                                                                                                                                                                              made, but the SNI (Subject Name Indication) extension to TLS is not available on                                                                                                                                                                                                                                                                                                                                                                                                              this platform. This may cause the server to present an incorrect TLS certificat                                                                                                                                                                                                                                                                                                                                                                                                             e, which can cause validation failures. You can upgrade to a newer version of Py                                                                                                                                                                                                                                                                                                                                                                                                             thon to solve this. For more information, see https://urllib3.readthedocs.io/en/                                                                                                                                                                                                                                                                                                                                                                                                             latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/_vendor/requests/                                                                                                                                                                                                                                                                                                                                                                                                             packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext ob                                                                                                                                                                                                                                                                                                                                                                                                             ject is not available. This prevents urllib3 from configuring SSL appropriately                                                                                                                                                                                                                                                                                                                                                                                                              and may cause certain SSL connections to fail. You can upgrade to a newer versio                                                                                                                                                                                                                                                                                                                                                                                                             n of Python to solve this. For more information, see https://urllib3.readthedocs                                                                                                                                                                                                                                                                                                                                                                                                             .io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: streamlink in /usr/local/lib/python2.7/dist-pack                                                                                                                                                                                                                                                                                                                                                                                                             ages
Requirement already up-to-date: futures in /usr/local/lib/python2.7/dist-package                                                                                                                                                                                                                                                                                                                                                                                                             s (from streamlink)
Requirement already up-to-date: singledispatch in /usr/local/lib/python2.7/dist-                                                                                                                                                                                                                                                                                                                                                                                                             packages (from streamlink)
Requirement already up-to-date: requests!=2.12.0,!=2.12.1,<3.0,>=2.2 in /usr/loc                                                                                                                                                                                                                                                                                                                                                                                                             al/lib/python2.7/dist-packages (from streamlink)
Requirement already up-to-date: pycryptodome<4,>=3.4.3 in /usr/local/lib/python2                                                                                                                                                                                                                                                                                                                                                                                                             .7/dist-packages (from streamlink)
Requirement already up-to-date: backports.shutil_which in /usr/local/lib/python2                                                                                                                                                                                                                                                                                                                                                                                                             .7/dist-packages (from streamlink)
Requirement already up-to-date: backports.shutil_get_terminal_size in /usr/local                                                                                                                                                                                                                                                                                                                                                                                                             /lib/python2.7/dist-packages (from streamlink)
Requirement already up-to-date: iso-639 in /usr/local/lib/python2.7/dist-package                                                                                                                                                                                                                                                                                                                                                                                                             s (from streamlink)
Requirement already up-to-date: iso3166 in /usr/local/lib/python2.7/dist-package                                                                                                                                                                                                                                                                                                                                                                                                             s (from streamlink)
Requirement already up-to-date: six in /usr/local/lib/python2.7/dist-packages (f                                                                                                                                                                                                                                                                                                                                                                                                             rom singledispatch->streamlink)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python2.7/d                                                                                                                                                                                                                                                                                                                                                                                                             ist-packages (from requests!=2.12.0,!=2.12.1,<3.0,>=2.2->streamlink)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.                                                                                                                                                                                                                                                                                                                                                                                                             7/dist-packages (from requests!=2.12.0,!=2.12.1,<3.0,>=2.2->streamlink)
Requirement already up-to-date: urllib3<1.22,>=1.21.1 in /usr/local/lib/python2.                                                                                                                                                                                                                                                                                                                                                                                                             7/dist-packages (from requests!=2.12.0,!=2.12.1,<3.0,>=2.2->streamlink)
Requirement already up-to-date: idna<2.6,>=2.5 in /usr/local/lib/python2.7/dist-                                                                                                                                                                                                                                                                                                                                                                                                             packages (from requests!=2.12.0,!=2.12.1,<3.0,>=2.2->streamlink)
root@vps:~# streamlink
Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <modul                                                                                                                                                                                                                                                                                                                                                                                                             e>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: iso3166
```
I have a feeling that this is because of my python version (2.7) and maybe updating to 3.6 would help, anyone have an idea?

also, I completely reinstalled streamlinkg and also tried the development version, same error.

**Comment by beardypig** [comment]
What does `cat /usr/local/bin/streamlink` return? Perhaps the `streamlink` script is pointing to the wrong place...

**Comment by distommy** [comment]
Alright I solved it. Seems like installing via pip doesnt do it right, so I did it manually (cloning from git and executing setup.py) and now it seems to work. Thanks for all the help people, its works.

**Comment by distommy** [comment]
@beardypig I know its offtopic here but I didnt want to create another thread: how do I choose ffmpeg as the player rather than vlc?

**Comment by gravyboat** [comment]
@distommy Check out the docs on this: https://streamlink.github.io/cli.html#player-options We just updated them to provide additional examples of using different players.

**Comment by gravyboat** [comment]
Thanks @bastimeyer, a bit early for me it seems as I totally missed ffmpeg...

**Comment by bastimeyer** [comment]
Closing the thread since the issue has been solved.
